### ISSUE TITLE
for internet apis, we are getting error, ERR_CONNECTION_REFUSED is electron app while testing using webdriverio

### ISSUE THREAD

**Issue by raxitpandya** [webdriverio/webdriverio#10453]
for internet apis, we are getting error, ERR_CONNECTION_REFUSED is electron app while testing using webdriverio

**Comment by christian-bromann** [comment]
@raxitpandya thanks for reporting. Unfortunately I can't tell what your problem is and how it connects to WebdriverIO. We recommend to follow our issue templates when filing a bug because it helps us contributor to understand your environment better. For further questions please visit our [Discord](http://discord.webdriver.io/).

**Comment by raxitpandya** [comment]
Let me try to explain here. Our web app is build using electron for desktop use. Our desktop app exe is working fine. But when i tried to test the desktop app exe using test script of WebdriverIO framework. Getting error "ERR_CONNECTION_REFUSED". Below is the devDependencies used.

"devDependencies": {
    "@wdio/cli": "^8.10.2",
    "@wdio/local-runner": "^8.10.2",
    "@wdio/mocha-framework": "^8.10.2",
    "@wdio/spec-reporter": "^8.10.2",
    "chai": "^4.3.7",
    "chromedriver": "^113.0.0",
    "electron-builder": "^23.6.0",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-electron-service": "^4.0.2"
  }
