### ISSUE TITLE
Calamitous HTML 5 dragg/drop

### ISSUE THREAD

**Issue by bondarum** [webdriverio/webdriverio#1058]
I'm aware that this issue was talked through in here about year ago but there was no clean walkaround or solution. Maybe there's one now? In this moment I don't have enough experience to solve it on my own. Any help would be nice ;)

**Comment by ifilatov** [comment]
if it is still valid - there is a solution with easy webdriver.io integration
https://github.com/andywer/drag-mock

**Comment by christian-bromann** [comment]
@ifilatov thanks for sharing. The question is how should WebdriverIO detect whether the drag&drop was successful or not?

**Comment by ifilatov** [comment]
your question seems to be rhetorical :)
you can get an error if something went absolutely wrong or add result verification for each case in the tests, but it's a duck-tape not a fix, I suggested it to @bondarum since it works for me and does not require any experience to integrate to tests

btw, I have just came across the solution that looks like webdriver-based fix - https://github.com/ePages-de/chromedriver-html5-dragdrop (for sorry I have not tried this solution jet, so cant affirm that it works)

**Comment by christian-bromann** [comment]
This should be now possible using the actions command.
