### ISSUE TITLE
[💡 Feature]: Exclude particular test case from spec file

### ISSUE THREAD

**Issue by bhanuagarwal73** [webdriverio/webdriverio#10769]
### Is your feature request related to a problem?

Yes.
We should have a way to exclude particular test case from spec file.

Let say we have 10 test cases in xyz.ts spec but don't want particularly 2 tests to be part of run.

![image](https://github.com/webdriverio/webdriverio/assets/38572421/44a2e693-c2a6-4144-9bd0-c7715d01dbc0)

### Describe the solution you'd like.

It can be:

- If making change in exclude of wdio.conf.ts:
'./src/specs/p1/homePage.test.ts ----mochaOpts.grep "Verify if any broken links on home page"'
![image](https://github.com/webdriverio/webdriverio/assets/38572421/d276c965-3e3a-4fca-b802-96edb1b8089f)

- If running through terminal then:
npx wdio run wdio.conf.ts --exclude './src/specs/bvt/homePage.test.ts --mochaOpts.grep "Verify if any broken links on home page"'
![image](https://github.com/webdriverio/webdriverio/assets/38572421/79f9844c-67ee-41e5-a536-2a7996ec91cd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhanuagarwal73** [comment]
Its working with terminal via mocha.invert as:
npx wdio run wdio.conf.ts --spec bvt.homePage.test.ts --mochaOpts.grep "Verify if any broken links on home page" --mochaOpts.invert

Please add support at exclude level in wdio.conf.ts

**Comment by christian-bromann** [comment]
The exclude property only takes file path and no further arguments. You can set `grep` and `invert` in the [`mochaOpts`](https://webdriver.io/docs/frameworks#grep) of your WebdriverIO config file. Since the `wdio.conf.js` is a normal file you can also always parse your custom arguments and set the value for `exclude` dynamically.

Closing as there is no feature that needs to be added. Please consider to join our  [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.

**Comment by bhanuagarwal73** [comment]
Thanks @christian-bromann for the reply.
I already handled that case with mochaOpts present in wdio.conf.ts file.

I tried over script level as well present in package.json as:
BVT: "wdio run wdio.conf.ts --spec bvt.homePage.test.ts --mochaOpts.grep 'Verify if any broken links on home page' --mochaOpts.invert"

But didn't worked.

**Comment by christian-bromann** [comment]
> But didn't worked.

The way you put it there looks good to me.
