### ISSUE TITLE
Unrecognised syntax using wdio as test runner and mocha framework

### ISSUE THREAD

**Issue by michaelDomingues** [webdriverio/webdriverio#1105]
Hi guys,

I built a sample project using wdio+mocha according the documentation available but I'm getting an error with syntax.

My test case is (e.g: xpto.js):

```
describe('my feature', function() {
    it('will do something', function(done) {
        browser
             .url('http://google.com')
             .getTitle().then(function(title) {
                 console.log(title);
              })
              .call(done);
    });
});
```

How I run:

```
wdio sample.conf.js
```

wdio conf file is as plain as the examples we find. Specs calls the xpto.js. Nothing new until now.

Dependencies versions:

```
    "selenium-standalone": "^4.9.0",
    "wdio-mocha-framework": "^0.2.11",
    "webdriverio": "^4.0.3"
```

Test execution gives a stupid error, total the opposite of the API documentation: 

```
1) will do something:
browser.url(...).getTitle(...).then is not a function
running firefox
TypeError: browser.url(...).getTitle(...).then is not a function
```

Where's the leak ?

**Comment by christian-bromann** [comment]
@michaelDomingues we haven't updated the website yet, so using v4 can lead to confusions. Short explanations: in v4 all commands are running synchronously. You can still chain them as long as they return and object. `getTitle` returns a string though, so that's why it throws that error. You can either 

1. rewrite everything since commands are synchronous:
```js
describe('my feature', function() {
    it('will do something', function () {
        browser.url('http://google.com');
        console.log(browser.getTitle());
    });
});
```

or 2. add `sync: false` to your wdio.conf.js and continue to use promises. [This example](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject) nicely demonstrates how to build up your test suite.

**Comment by fijijavis** [comment]
I've been struggling with the same issue for 2 days and just happened upon this post.  Is there any "what's new" documentation for v4?
