### ISSUE TITLE
chaining in the partial text selector

### ISSUE THREAD

**Issue by rafawalter** [webdriverio/webdriverio#1151]
Please add support for 
`browser.click(".element .childElement*=text")`

Syntax is cleaner than the alternative below, and works with sync syntax like Chimp
`browser.element(“.element”).click(".childElement*=text")`

**Comment by christian-bromann** [comment]
@rafawalter I see that your first example is cleaner but implementing it would take a lot of effort because we would need to come up with a way to perfectly transform css selectors into xpath + consider the partial text selector.

I don't know why the second example doesn't work with chimp but I think it makes more sense to ask for support for it in the chimp project.
