### ISSUE TITLE
Full API documentation

### ISSUE THREAD

**Issue by dcosson** [webdriverio/webdriverio#1167]
I'm just getting started and don't have any experience with Selenium.

I'm having a hard time figuring out the available API's from reading the webdriverio docs. E.g. I don't even see `getTitle()` documented anywhere, I can't figure out what a selector like `browser.element('h1')` should return and how to traverse the DOM to get the text value (it returns some kind of DOM node representation with a pointer to the value not the actual text value), etc.

Is there a thorough list of API methods somewhere that I'm missing? 

Or is this at the Selenium level and not the responsibility of webdriverio to document the available methods? Where can I look for better documentation?

**Comment by christian-bromann** [comment]
> I'm just getting started and don't have any experience with Selenium.

Welcome to the crazy world of automated testing :wink: 

> I'm having a hard time figuring out the available API's from reading the webdriverio docs. E.g. I don't even see getTitle() documented anywhere

Sorry we are currently updating the website. The latest version is more or less beta atm. So I would recommend to go back to v3 to avoid any further trouble. Or you can stick with v4 (here is a bit docu about what has changed: https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/v4.md). Some commands have changed but you can always go on github and to see all available commands there.

> I can't figure out what a selector like browser.element('h1')

Easy in WebdriverIO: 
```js
browser.getText('h1').then(function() {...});
```

> Is there a thorough list of API methods somewhere that I'm missing?

Have you seen http://webdriver.io/api.html?

I am working on getting the website updated so it document the latest commands. It will take some more days. Closing since this issue is known

**Comment by dcosson** [comment]
Great, thanks for the thorough response. Not sure how I missed the API docs page, but it makes a lot more sense now that I know those are all known to be out of date.
