### ISSUE TITLE
Examples fail silently when webdriver isn't available

### ISSUE THREAD

**Issue by also** [webdriverio/webdriverio#1204]
I've tried running the [local example](https://github.com/webdriverio/webdriverio/blob/c9406d0972b0d3404611a264fe0ae1c31aaa8af7/examples/webdriverio.local.js) without a local webdriver running and the [browserstack example](https://github.com/webdriverio/webdriverio/blob/c9406d0972b0d3404611a264fe0ae1c31aaa8af7/examples/cloudservices/webdriverio.browserstack.js) without valid credentials.

They don't log any output, and exit with code 0 which makes it look like they succeeded.

This seems like dangerous examples–code based on them will appear to have succeeded when nothing ran at all.

Adding this to the end makes it behave more like I expected:

```js
    .catch((err) => {
      console.error(err.stack);
      process.exit(1);
    })
```

I'm using webdriverio 4.0.5 on Node.js 4.2.3

**Comment by christian-bromann** [comment]
@also in order to throw an error I would need to do that within the next eventLoop which would destroy the whole error handling of WebdriverIO. Unfortunately I haven't found a good solution for that now. Luckily running automation scripts in a plain node file is not the common use case. Maybe it might sense to delete that example file.
