### ISSUE TITLE
Fibers?

### ISSUE THREAD

**Issue by iliakan** [webdriverio/webdriverio#1207]
I saw that 4.0 uses Fibers.

But the major movement is towards async/await + promises right now. Is the decision to use Fibers strategically correct?

**Comment by christian-bromann** [comment]
I think so. Beginner or people moving from the Java world to Node usually have problems to understand the concept of promises. Also Fibers is getting used by more popular frameworks (e.g. Meteor) and it seems to be pretty stable across operating systems. I personally like Fibers more because you don't have hundreds of `await` words in your spec files when writing highly asynchronous code.

Last but not least, switching back to async behavior if you want to use async/await can be done by just [one parameter](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L91-L94). So I am not afraid to kick Fibers eventually.
