### ISSUE TITLE
Multiremote: How to assert across the browsers

### ISSUE THREAD

**Issue by sahas-** [webdriverio/webdriverio#1224]
## The problem

When using single browser, responses are pretty straight forward. For example, navigating to google and .getUrl() contains response 

` "https://www.google.com/?gws_rd=ssl" `

When using multiremote, responses are bundled into browser profile. For example, navigating to google (from 2 browsers) and .getUrl() contains responses 

`{ browserA: 'https://www.google.com/?gws_rd=ssl',
  browserB: 'https://www.google.com/?gws_rd=ssl' } `

I'm looking for guidance to handle assertions. 
Meaning, if its single browser, I assert like `url.indexOf("www.google.com")>-1`

In multi browser scenario, number of browsers, browser profile name (i.e browserA, browserB) could vary depending on the need. Wondering if there is a generic API to assert across all the browsers.

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: system
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio 
* if wdio testrunner, running synchronous or asnychronous tests: don't know
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
I think you misunderstand the usage of multiremote. It's not to run tests in parallel. It is a tool to run sophisticated e2e tests where you need 2 or more browser in order to test some kind of communication, e.g. a chat application or a webrtc app. If you want to run your tests with wdio in parallel just define multiple capabilities like [here](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.mocha.conf.js#L23-L29)
