### ISSUE TITLE
CPU and memory 100% 

### ISSUE THREAD

**Issue by andremw** [webdriverio/webdriverio#1364]
## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 4.2.6
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Ubuntu MATE

## Details

When I run the tests it opens a lot of browser windows (I think it's one for each test), all the cores jump to 100% usage and in just a few seconds the memory usage starts going up until the OS is completely frozen. It's happening in Chrome, FF and PhantomJS. But it's _not_ happening when I use Chrome passing some args to change its user agent to mobile.
This is not happening in my peers' env (Ubuntu, Mint), but only in my Ubuntu MATE.

## Link to Selenium/WebdriverIO logs

Logs [here](https://gist.github.com/andremw/1bd0cf3d52ad39962e18e8a0665d06e5).

**Comment by christian-bromann** [comment]
I believe if you run tons of test in parallel your CPU will be fully utilised at some point. So I would recommend to set maxInstances to 1 while working on your tests locally. In your CI you should then use Sauce Labs to run everything with concurrency.
Even though we could work on making the testrunner more performant but at the end you won't get around of running browser in the cloud.

**Comment by andremw** [comment]
Sorry, @christian-bromann, I think I didn't make myself clear. In every other computer we just get a single instance running, and the tests all run in a single browser window. In my env it opens many instances. With this maxInstances option set to 1 it stops creating thousands of browser windows but it closes the browser window after each test.
What's weird is this different behavior in different machines, even though we share the same config.

**Comment by andremw** [comment]
@christian-bromann, I installed the version 3 here and it worked normally. I need to check later what was changed between versions 3 and 4. Thanks!

**Comment by christian-bromann** [comment]
@andremw in v4 we spawn a single process for each selenium session (also if maxInstances is set to 1). See also http://webdriver.io/guide/getstarted/v4.html

**Comment by arenacheck** [comment]
This problem is only related with low CPU. I have as example amd 9750 quad-core for this days very bad and I get not only 100% spikes I got real 100% lines over multiple seconds. They only way to fix around this is to disable extensions and features like flash, javascript, webgl, canvas and so on do reduce the browser CPU usage. Then you can use problems like process lasso to manage programs and reduce the usage by define new cores or I/O priority. Notice that if you reduce the resources from node and chrome and all other script related programs you can get freezes or crashes. If you are "lite" edit your browser and disable everything and you still got 100% spikes then you need buy new CPU. However if you have only spikes it should be now problem. Because the delay will be so small that no program will crash.
