### ISSUE TITLE
Implement workaround for moveTo command in Safari

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/webdriverio#1419]
## The problem

I'm consistently getting failures when running the `rightClick` method in Safari 9 (and 6, haven't tried other versions). I don't get these same failures in other browsers.

## Environment

* WebdriverIO version: 4.1.1
* Node.js version: 6.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

Here is the error I'm getting:

```
Unknown command: {"id":"rjli6wikh89u","name":"mouseMoveTo","parameters":{"element":":wdc:1467223117657"}} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'itako47220.prod.miso', ip: '172.20.47.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
```

**Comment by christian-bromann** [comment]
@philipwalton mhm .. apparently Safari doesn't support the `moveTo` command. In order to right click on a specific element we first move the mouse pointer to that element and then call `buttonPress`. According to https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4136 the best thing to do is to simulate the mouse move action (see https://ynot408.wordpress.com/2011/09/22/drag-and-drop-using-selenium-webdriver/) and call `buttonPress('right')`.

I think it it a good idea to add this workaround in WebdriverIO natively.

**Comment by michaelDomingues** [comment]
@philipwalton, try with ´moveToObject´.
It's working nicely in FF, Chrome and Safari with the same wdio version as yours :)

http://webdriver.io/api/action/moveToObject.html

**Comment by christian-bromann** [comment]
Implemented a polyfill for left/middle/right click on safari, will be released with the next version

**Comment by aagrawalQB** [comment]
Hi I am facing issue with moveToObject on safari. It does not work at all? any work around it ?

**Comment by mandy88087** [comment]
Me too, is there any update on this? thanks a lot

**Comment by christian-bromann** [comment]
@mandy88087 yes: the Action API, but it hasn't been implemented in Safari yet

**Comment by mandy88087** [comment]
@christian-bromann , thanks for the immediate reply, i will wait for that.

**Comment by timbru31** [comment]
@mandy88087 Another place to keep an eye out are the release notes of the Safari Technology Preview versions: https://developer.apple.com/safari/technology-preview/release-notes/ - they have a section for WebDriver related things.

**Comment by mandy88087** [comment]
thanks a lot @timbru31

**Comment by git-jiby-me** [comment]
@christian-bromann i ended up here after `browser.moveTo(null, x, y)` failing in safari, because for the polyfill `element` is also required unlike documented.

However i found that, removing the polyfill and just letting `this.requestHandler.create('/session/:sessionId/moveto', data)`, seems to be working in safari now, it seems they implemented `moveto`.

Should we not remove the polyfill in that case ?

**Comment by christian-bromann** [comment]
> Should we not remove the polyfill in that case ?

This command is going to be removed soon anyway.
