### ISSUE TITLE
Fix staleelementretry for standalone mode

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1469]
## The problem

After we've updated the dependencies to use Babel6 the functional test for stale element retries stopped working. After the error is thrown by Selenium it retries it one time but returns with undefined as result.

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 4.4.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: async

## Link to Selenium/WebdriverIO logs

```
staleElementRetry loop cnt: 49, command result: true
staleElementRetry loop cnt: 48, command result: true
staleElementRetry loop cnt: 47, command result: undefined
    1) should not throw stale element error in standalone mode


  0 passing (6s)
  1 failing

  1) staleElementRetry should not throw stale element error in standalone mode:
     AssertionError: expected undefined to be true
```

## Code To Reproduce Issue [ Good To Have ]

just run `npm run test-functional -- --grep "staleElementRetry"`

**Comment by CTaylor1118** [comment]
@christian-bromann In my debugging, it seems that the problem is in the resolve function and the client.next function in webdriverio.js. We starting in the onreject portion of client.next.
```Javascript
 /**
  * this will get reached only in standalone mode if the command
  * fails and doesn't get followed by a then or catch method
  */
   return resolve.call(this, e, null, null, { depth: 0 }) //We are passing in a object with no command history, which will cause the error handler to fail in the onreject
```
 Then in resolve we try to resolve the failed command with the result of the error handler. 
```javascript
this.defer.resolve(Promise.all(internalErrorHandler.map((fn) => {
  return fn.call(context, result) //Context here is bad so if this is a stale element, this will fail
})).then((res) => {
Fixing the context is trivial but the real problem is what happens when we retry. We eventually make our way back to client.next however, this will never complete.
```javascript
/**
 * use finally to propagate rejected promises up the chain
 */
  return this.lastPromise.then((val) => {  //lastPromise now refers to the failed command that is 
//waiting to resolve on the result of the command being retried. We are deadlock becuase this
// command can never complete until the fail command is no longer pending and the failed 
//command will only resolve once this one complete.
```
It seems before you were actually rejecting the failed command and then calling the command to retry (see https://github.com/webdriverio/webdriverio/blob/f94d087912b676cb3bea0fe5b34feb972080165d/lib/webdriverio.js#L104). Is there a reason rejecting wasn't a good solution. It seems that undoing that change would fix this.

**Comment by christian-bromann** [comment]
Fixed by https://github.com/webdriverio/webdriverio/pull/1606
