### ISSUE TITLE
In lib/helpers/errorHandler.js tries access object like array for result of element command.

### ISSUE THREAD

**Issue by CTaylor1118** [webdriverio/webdriverio#1488]
## The problem

The staleElementError error handler tries access the result of the element command as if it were an array. Since the element command just returns an object, this causes an error and can't handle a staleElementError when element is used in a command instead of elements (say for the click command).

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 0.12.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

**Comment by mnaughto** [comment]
I'm running into the same problem. If I add a few additional checks in that code, the stale element error just comes through. How soon might a pull request be accepted if I made one?

**Comment by ebbe-brandstrup** [comment]
Same problem.

Indeed, the ```staleElementError``` is making the mistake of using the result of the WebdriverIO [ELEMENT](http://webdriver.io/api/protocol/element.html) action as an array instead of a JSON object (like the docs state it returns) - just like @CTaylor1118 said. 

I have to revert to an older version of WebdriverIO for the time being. I hope I'll have time to create a PR with a fix shortly though.

### Environment
- WebdriverIO version 4.2.16
- Node.js version 4.5.0
- Standalone mode

**Comment by CTaylor1118** [comment]
I have a fix for this in my fork as well as fixes for a few other bugs. I had to include the build files as we are using node 0.12.7. Eventually I will get around to opening a pull request for the changes after I remove the build files.

**Comment by ebbe-brandstrup** [comment]
I created a PR with a fix now and I included a test that verifies that the error handler doesn't crash when an 'element' command is encountered anymore.

@CTaylor1118, I'd really appreciate some feedback if you also made a test to verify the fix and found some better way to exercise the bug.

**Comment by christian-bromann** [comment]
Thanks @ebbe-brandstrup for the PR and thanks @CTaylor1118 for reporting
https://github.com/webdriverio/webdriverio/pull/1606
