### ISSUE TITLE
Failing before Hook does not report failing describe/filename

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#1490]
## The problem

Where a before hook fails and has called a custom command, wdio does not report the name of the describe block which failed making it impossible to debug where the failure occurred

Ideally we would have the `describe` block name or the `filename` of the testcase
```
1) "before all" hook:
expected false to equal true
running chrome
AssertionError: expected false to equal true
    at Object.<anonymous> (/srv/api/questionsV2/tests/ui/customCommands/customCommand.js:5:22)
    at /srv/api/questionsV2/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:240:29
```
## Environment

* WebdriverIO version: ^4.0.9
* Node.js version: v4.4.7
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): allure, junit, mocha, selenium-standalone

## Link to Selenium/WebdriverIO logs
https://gist.github.com/kevinmcdonnell/5aa10be017dbfe95a03b192f50d56204

## Code To Reproduce Issue [ Good To Have ]

debug.js:
```
describe('Test name should be visible in reporter if before hook fails', function(){
    before(function(){
        browser.customCommand();
    });

    it('My it block name', function(){
        expect(true).to.equal(true);
    });
});
```

customCommand.js:
```
browser.addCommand('customCommand', function () {
    browser.waitUntil(function(){
        return true === true;
    });
    expect(false).to.equal(true);
});
```

**Comment by christian-bromann** [comment]
This is all the stack trace I get from Mocha. Usually everything that throws an error within the wdio config hooks doesn't lead the test to fail because I want to avoid that bad programmed services add flakiness to the tests. So the fact that you even see the error is that the before hook gets executed after Mocha gets initialised. It acts as a `before All` hook. Moving the execution before Mocha initialization, we would not be able to define custom commands in before hooks anymore. So it is a nice compromise for now.

We could add something to the config that allows to register custom commands more easily but I am not sure yet how this should look like. I would recommend to switch to the spec reporter to see suite test has failed.
