### ISSUE TITLE
execute function can't pass a function?

### ISSUE THREAD

**Issue by hitbiter** [webdriverio/webdriverio#1502]
Hi,this is my testcase for experiment：
```js
  return browser
              .pause(1000)
               .execute(function(util){
                   var p=util;
                   console.log('GOing test!!!!')
                   console.log(p);
                   return p;
               },function(){consloe.log('aaaa')})
               .then(function(){

               })
        });
```
and  I  found the logs in terminal --
```
23:38:59.289 INFO - Executing: [execute script: return (function (util){
                   var p=util;
                   console.log('GOing test!!!!')
                   console.log(p);
                   return p;
               }).apply(null, arguments), [null]])
23:38:59.303 INFO - Done: [execute script: return (function (util){
                   var p=util;
                   console.log('GOing test!!!!')
                   console.log(p);
                   return p;
               }).apply(null, arguments), [null]]
```
I found the parameters to pass to execute is null , and i  don't know how to handle it...

**Comment by christian-bromann** [comment]
You can try to stringify the function and use eval on the browser side.

**Comment by fundead** [comment]
That is pretty raw and approaching workaround territory. Any chance of a more idiomatic API?

**Comment by christian-bromann** [comment]
> Any chance of a more idiomatic API?

What do you mean by that?

**Comment by fundead** [comment]
Essentially supporting hitbiter's use case, where a function can be passed in as an arg to `execute`, and called within the Selenium context, without resorting to using `eval`. I'm guessing this is a bit tricky due to it crossing the node/selenium boundary. In any case I managed to implement a workaround by adding the function I needed to call as a referenced script on the page fixture that browser.url loaded, thereby bringing the needed function into scope, so no additional API appears to be required after all. Thanks for you work on this!
