### ISSUE TITLE
override command dont seem to work

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1524]
when i do this:
```
 client.addCommand('launch',function(){
        console.log('launching');
        this.launch();
    },true);
```

the log is not written. 

in my case the log is another action i want to perform always at launch, but simplification also shows the problem.

**Comment by christian-bromann** [comment]
This functionality is tested and should work. I don't understand the code example above. It looks like you always call the launch method recursively which will end up in an endless loop.

**Comment by talarari** [comment]
Ok so i can't override and extend an existing command this way.
My intention was to do an extra thing every time a command is called.
I should give the command another name i guess.

**Comment by christian-bromann** [comment]
> I should give the command another name i guess.

yes or you can use the beforecommand hook to something before certain commands.

**Comment by WadeJohnson** [comment]
This is actually a problem I am running into. I used to be able to override existing webdriverio commands by throwing the `true` flag on `addCommand` and it would use the code in that function instead; this does not seem to work anymore.

```javascript
client.addCommand('newClick', function(selector) {
    console.log('new click');
});

client.addCommand('click', function(selector) {
    console.log('override click');
}, true);
```

In the example above, I would expect a `client.click('foo')` command to do nothing but output `override click` to the console. (Obviously would not do this in the real world, only doing it as an example.) But, that does not happen.
But a call to `client.newClick('foo')` *will* output `new click` to the console.

I can see that a call to `client.click('foo')` is ignoring my custom click command and calling the existing webdriverio click command because putting `console.log('DEFAULT')` at line 11 of `node_modules/webdriverio/build/lib/commands/click.js` will output `DEFAULT` to the console every time `client.click('foo')` is called.

**Comment by monolithed** [comment]
@talarari, @WadeJohnson please see the following issue https://github.com/webdriverio/webdriverio/issues/1539
