### ISSUE TITLE
Using WebElement JSON Objects as Selectors

### ISSUE THREAD

**Issue by ChadKillingsworth** [webdriverio/webdriverio#1588]
[Testing elements in Shadow DOM](https://gist.github.com/ChadKillingsworth/d4cb3d30b9d7fbc3fd0af93c2a133a53) has presented new challenges.

I'd like to be able to use WebElement JSON objects as selectors for further actions.

```js
var button = browser.element('button');
browser.click(button);

//Currently you have to use the following:
browser.elementIdClick(button.value.ELEMENT);
```

While this contrived example doesn't show the true need, it makes much more sense when you are finding an element in a shadow tree, then performing some kind of action on that element.

**Comment by christian-bromann** [comment]
Not an issue, do:

```js
var button = browser.element('button');
button.click();
```

😉

**Comment by pkaske** [comment]
I'm currently trying to test a web component driven web app that makes very heavy use of shadow dom and stumbled upon this issue. I think this issue may got misunderstood by you, @christian-bromann?

Your solution doesn't work as soon as elements are inside shadow roots. The gist provided by @ChadKillingsworth is workaround but comes at the cost of loosing all the niceties webdriver.io build in commands provides.

For example, it is necessary to use `elementIdValue` instead of `addValue`.

If you have somebody like me who's hole app is a web component itself, you can't work with any of webdriver "own" commands.

**Comment by christian-bromann** [comment]
> For example, it is necessary to use elementIdValue instead of addValue.

Why?

**Comment by ChadKillingsworth** [comment]
In certain cases, the internal selector doesn't get properly set. I haven't had time to track down exactly why. It's related to async scripts and `waitFor` type commands.

**Comment by pkaske** [comment]
I really hope I got something wrong... This is how it seems to me:

addValue takes a selector string as it's first arguments, and only a string. Now there is now way to my knowledge to select into a shadow (open) root with css selectors or xpath. And that is good, because one of the main purposes of shadow dom is to encapsulate css.

The script of @ChadKillingsworth is able to travel down the DOM tree into shadow roots and find the element anyway. But as commands like `addValue` only accept a selector string and not a previously queried element they can't be used.

Example:

If have the following simplified tree:

```html
<ev-landing>
  <!--- .... -->
  #shadow-root (open)
    <!--- .... -->
    <input name="email" />
    <!--- .... -->
  # /shadow-root
</ev-landing>
```
Now I try to:  
`browser.addValue('ev-landing input[name="email"]', 'max@example.com');`

This won't work because `An element could not be located on the page using the given search parameters ("ev-landing input[name="email"]").`

And that is expected, because css selectors aren't supposed to pierce into shadow roots.

The the workaround of @ChadKillingsworth:

```js
const input = browser.shadowDomElement(['ev-landing', 'input[name="email"]']);

// works
browser.elementIdValue(input.value.ELEMENT, 'max@example.com');

// but this doesnt', would be much nice, though
browser.addValue(input, 'max@example.com');
```

**Comment by ChadKillingsworth** [comment]
The documentation here could use some help. Because in multiple cases its not clear. But does this work?

```js
browser.shadowDomElement(['ev-landing', 'input[name="email"]'])
    .addValue('max@example.com');
```

Web driver commands which only take a selector can often be called without it. Internally it uses the last valid selector. It's a bit unclear what happens in other cases.

**Comment by pkaske** [comment]
Yes! That works. At least with `addValue` (didn't try other commands jet). Would definitely be great if the doc's could be more clear about that.

I find this not really optimal!? You have to constantly re-select elements, but I guess one can make it work like that. Question is, isn't their quite some space for improvements when it comes to testing inside custom element with shadow dom?

Anyway, thank you very much @ChadKillingsworth. That info helps a lot!

**Comment by christian-bromann** [comment]
> // but this doesnt', would be much nice, though
> browser.addValue(input, 'max@example.com');

I think the docs are clear on that. If you write the command this way the first argument has to be a selector not an object

**Comment by ChadKillingsworth** [comment]
@christian-bromann It's not clear at all though that the selector can be omitted and the last valid selector will be utilized. I've had a hard time finding that and have had lots of engineers working for me ask the exact same question.

**Comment by pkaske** [comment]
My example

> // but this doesnt', would be much nice, though
> browser.addValue(input, 'max@example.com');

was meant as a proposal on how the api would make it easier to work with elements that cannot be selected with a string selector (b/c of shadow dom). I was well aware that the selector can only be a string. That's the limitation that makes it hard to work with shadow dom.

Sorry that I didn't stated that clear enough.

**Comment by pkaske** [comment]
When I get you guys right, @christian-bromann thinks I didn't see that the `selector` argument has to be a string, but the docs are clear on that, while @ChadKillingsworth thinks the docs should mention that the `selector` argument is kinda optional.

My point is, that it would be nice if the `selector` argument could be a programmatically queried element object (using javascript to query into shadow roots), because there is no way to query a shadow dom child with a string selector.

**Comment by ChadKillingsworth** [comment]
> because there is no way to query a shadow dom child with a string selector.

That's a bit beyond the scope of webdriver.io. The [browsers need to solve this](https://bugs.chromium.org/p/chromium/issues/detail?id=633007).

**Comment by pkaske** [comment]
That seems to be an ongoing question. Who should change in order to work with shadow dom. This thread is very interesting regarding this: https://github.com/w3c/webcomponents/issues/78

They're not convinced jet that there is enough of a use case besides testing. @ChadKillingsworth, you even stated that [testing frameworks should change](https://github.com/w3c/webcomponents/issues/78#issuecomment-243017771). I agree with you.

**Comment by ChadKillingsworth** [comment]
> They're not convinced jet that there is enough of a use case besides testing.

It should be solved at the selenium/webdriver layer. That's what the Apple dev was saying. For once I tend to agree.

**Comment by hellolin324** [comment]
@pkaske How have your tests with Shadow Dom go? I am encountering the same problems too, where I can not select the elements inside of a shadow root. For example, in the following html code:

`<input is="iron-input" id="input" type="text" role="combobox" autocomplete="off" autocapitalize="none" aria-autocomplete="list" key-event-target="" class="style-scope vaadin-combo-box" aria-expanded="false" placeholder="" aria-label="Organization">
  #shadow-root(user-agent)
    <div id="inner-editor">some text</div> ==$0
</input>`

When I try to write test code with the selector #inner-editor using webdriverIO, it doesn't work and throws the error "Can not locate element" like you had before. Anyways for me to get over that error using WebdriverIO?

One of the devs here are using WebdriverJS and selenium standalone to get over that problem, but I'd love to stick with WebdriverIO since that is what I have been using.

**Comment by pkaske** [comment]
I didn't continue with to investigate any further with webdriver, sorry.

**Comment by hellolin324** [comment]
@pkaske it looks like I will follow that as well, one of my test engineers figured out how to solve the shadow root problem using Selenium Chromedriver and WebdriverJS instead of WebdriverIO, so looks like I will have to ditch WebdriverIO until it have native support for shadow DOM.

**Comment by ChadKillingsworth** [comment]
If you are using my gist as a guide here, I've updated it: https://gist.github.com/ChadKillingsworth/d4cb3d30b9d7fbc3fd0af93c2a133a53

shadowDom works correctly in webdriver.io. I use it every day.
