### ISSUE TITLE
execute method's element argument is not translated to corresponding dom-element.

### ISSUE THREAD

**Issue by srikanth-nettem** [webdriverio/webdriverio#1625]
When a webElement reference is passed as an argument in **execute** method, it is not converted to the corresponding DOM element in the function script.

* WebdriverIO version: latest
* Node.js version: 6.4.0
* Standalone mode
* Synchronous execution

sample html:
  `<input id='username' type='text'></input>`

sample wdio code:
```
var usernameElement = client.element("#username");
var getTagName = function(arg){return arg.tagName;};
var expectedValue = client.execute(getTagName, usernameElement);
expect(expectedValue).toBe('input');
```

logs:
```
[23:41:24]  COMMAND	POST 	 "/wd/hub/session/077d5714-057c-48a7-8e65-b73f9c20871f/element"
[23:41:24]  DATA		{"using":"id","value":"username"}
[23:41:24]  RESULT		{"ELEMENT":"4"}
[23:41:24]  COMMAND	POST 	 "/wd/hub/session/077d5714-057c-48a7-8e65-b73f9c20871f/execute"
[23:41:24]  DATA		{"script":"return (function (arg){\n            return  arg.tagName;\n            \n        }).apply(null, arguments)","args":[{"state":"success","sessionId":"077d5714-057c-48a7-8e65-b73f9c20871f","hCode":578840789,"value":{"ELEMENT":"4"},"class":"org.openqa.selenium.remote.Response","selector":"#username","_status":0}]}
[23:41:24]  RESULT		null
```

**Comment by christian-bromann** [comment]
A web element reference is a mapping for Selenium to real elements on the page. If you pass in that web element as argument to the website you can't expect that the website knows what this id stands for. Also getting the tag name can be done by using [`getTagName`](http://webdriver.io/api/property/getTagName.html). So the whole assertion can be simplified in the following way:

```js
var usernameElement = client.element("#username");
expect(usernameElement.getTagName()).toBe('input');
```

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by acthp** [comment]
You closed this issue by writing, effectively, "You can't expect this API to do what it is documented to do." It's true, the documentation for execute(), like the the rest of it, is filled with undefined terms, like "JSON objects that define a WebElement reference" (wtf is that, and where do I get one, when the docs make no further mention of it?), but one can reasonably understand from the doc that execute() will convert some ill-defined reference-to-a-DOM-element that exists in selenium, to the actual DOM element in the context of the function call, which happens in the browser. Clearly, the point of opening this issue was that the conversion, as documented, does not appear to work. Closing the issue by saying "there's a simpler way to do this" misses it rather completely: of course there's a simpler way. It's a minimal counter-example to the docs, not a design strategy.

**Comment by srikanth-nettem** [comment]
@acthp, in summary you caught my intention.

**Comment by jardakotesovec** [comment]
@christian-bromann I believe having same issue that `browser.execute` does not convert to dom element.

This is typical workaround for buggy edge driver, which in some cases prevents clicking on some elements and workaround is to do that via javascript. Was using that happily in protractor. But the conversion does not seems to happen. 
```
browser.execute(function(el) {
      el.click();
    }, $('selector'))
```

Getting 
```
unknown error: el.click is not a function
```

**Comment by MarianoSalerno** [comment]
I'm having the same problem as @jardakotesovec, reading the docs I was under the impression that if I pass a webdriverio element the execute function did the conversion to an element I could use in the browser, is it supposed to work that way?

**Comment by erwinheitzman** [comment]
$, $$ and it's equalivants browser.element and browser.elements return WebElement JSON objects.
This kind of object holds a value property that contains the actual element reference.

So in order for this to work you'd apply it like this:
`browser.execute(elem => elem.click(), $('some-selector').value);`
or this:
`browser.execute(elem => elem.value.click(), $('some-selector'));`

and of course for the other types it's possible too:
```
browser.execute((list) => {
    list.forEach(elem => {
        elem.value.click();
    });
}), $$('some-selector'));
```

**Comment by jbildani** [comment]
@srikanth-nettem @christian-bromann , @jardakotesovec  , @MarianoSalerno  ,@erwinheitzman

I have query if you can help in this, i want to getText by using browser.execute() method
I have used in the same approach as mentioned above( by referring click)

const valuesave= browser.execute(elem => return elem.getText(), $('some-selector').value)
but this is not working, can you please help here

**Comment by DmitryShashkov** [comment]
If someone encounters this issue with current version of WebdriverIO (~7.20.1)
`$('some-selector').value` is no longer a thing, you now have to `await` for it (or use `then`) to get it.

For instance, [this article](https://webdriver.io/blog/2019/06/25/file-upload/) has such a code example:
```
const fileUpload = $('.upload-data-file-input');
browser.execute(
    (el) => el.style.display = 'block',
    fileUpload
);
```
It will fail with the error similar to one described above: `javascript error: cannot set properties of undefined (setting 'display')` (because `el` is not an instance of `Element`). For it to work, you have to use it like this:
```
const fileUpload = await $('.upload-data-file-input');
browser.execute(
    (el) => el.style.display = 'block',
    fileUpload
);
```
Hope this helps someone.

**Comment by christian-bromann** [comment]
Thanks for sharing @DmitryShashkov , really appreciate it 👍
