### ISSUE TITLE
Is the `done` callback not supported when using sync tests?

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/webdriverio#1677]
## The problem

The following code shows that `done` callbacks aren't defined:

```js
it('should do something', (done) => {
  console.log(done); // Logs `undefined`.
});
```

I'm running sync tests, but I'm using other normal async code, and it doesn't look like there's support for that. Is that the case?

For example, if I need to make an HTTP request in my test code, how do I wait for the response to proceed?

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 6.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-mocha-framework, wdio-sauce-service

**Comment by christian-bromann** [comment]
The `done` callback is not supported in WebdriverIO by design. You have 3 options to call async code:

1. return promise directly:
```js
before(function () {
    return request(...);
});
```
Each hook or `it` block will resolve the promise first before continuing with the next test.

2. create an async custom command:
```js
browser.addCommand('doStuff', function async (arg1, arg2) {
    return request(...)
});
```
When you apply async as function name for a custom commands, all function behave in async manner. Once you've registered it somewhere it behaves like a synchronous command tho.
```js
browser.url(....);
browser.doStuff(1, 2);
console.log(browser.getTitle());
```

3. Lastly you can create a helper page object and use the call command to wait until the promise has resolved:

```js
var result = browser.call(function () {
    return request(...);
});

return result;
```

**Comment by philipwalton** [comment]
Thanks for the details. It would be great if this were in the documentation, otherwise people are just going to assume it works exactly like regular mocha works.

It's probably also worth getting rid of the mocha errors that contradict what you just said:
<img width="955" alt="screen shot 2016-11-01 at 5 07 46 pm" src="https://cloud.githubusercontent.com/assets/326742/19912249/5390df58-a056-11e6-837b-aaa69dea6720.png">

**Comment by lihan** [comment]
@christian-bromann I need to test something that exists in browser event callback (devtool service)
`browser.on('Network.requestWillBeSent', function(params){
    // Assertions
});`
In this case, I have to use a done method. Or it will ignore the errors after first assertion.
