### ISSUE TITLE
Update config in services.

### ISSUE THREAD

**Issue by nrdobie** [webdriverio/webdriverio#1687]
I was looking to enhance my [wdio-static-server-service](https://github.com/LeadPages/wdio-static-server-service) with port scanning. In theory the service would scan for an open port and then update `baseUrl` with located port. A similar option could be applied to the Selenium service as well. This is coming from our Jenkins server trying to run our E2E's simultaneously and hitting port conflicts, port scanning would bypass this issue. From what I could find there is no way for a service to update the config, using the code below I am successfully finding an open port but `baseUrl` is not propagated to the actual runner.

``` javascript
  getPort() {
    return new Promise((resolve, reject) => {
      if (this.port) {
        resolve(this.port);
        return;
      }

      portfinder.getPort((err, port) => {
        if (err) {
          reject(err);
          return;
        }
        this.config.baseUrl = `http://localhost:${port}`;
        resolve(port);
      });
    });
  }
```

**Comment by christian-bromann** [comment]
See how the sauce service modifies the config:
https://github.com/webdriverio/wdio-sauce-service/blob/master/lib/sauce-launch-service.js#L12-L13

**Comment by nrdobie** [comment]
Must have something to do with the update being in a callback, because in my `onPrepare` function I am setting `this.config = config`.

**Comment by nrdobie** [comment]
Here's all the code related to ports.

``` javascript
export default class StaticServerLauncher {
  onPrepare(config) {
    const { staticServerFolders: folders, staticServerLog: logging = false,
        staticServerPort: port = null } = config;

    // ...
    this.config = config;
    // ...

    return this.getPort().then(usePort => new Promise((resolve, reject) => {
      this.server.listen(usePort, (err) => {
        if (err) {
          reject(err);
          return;
        }

        this.log.info(`Static server running at http://localhost:${usePort}`);
        resolve();
      });
    }));
  }

  getPort() {
    return new Promise((resolve, reject) => {
      if (this.port) {
        resolve(this.port);
        return;
      }

      portfinder.getPort((err, port) => {
        if (err) {
          reject(err);
          return;
        }
        this.config.baseUrl = `http://localhost:${port}`;
        resolve(port);
      });
    });
  }
}
```

**Comment by christian-bromann** [comment]
I am not sure how to help you.

**Comment by mleonh** [comment]
I realize this is a closed issue, but for people running into the same issue: this is still valid. Updating the `config` object from services isn't possible. Any changes to the object (for example in an `onPrepare` hook) are discarded. My guess is that the SauceLabs service works only because it sets `protocol`, `host` and `port`, which are specifically handled in `launcher.js`.

**Comment by robbiewareham** [comment]
Apologies for adding to a closed issue but having investigated why, I wanted to add some more details as to why it is not possible to update configuration in an `onPrepare` function of a service. 

I have observed that when I run my test (via WDIO CLI), the configuration file is loaded via `ConfigParser.addConfigFile` twice; once in `webdriverio/packages/wdio-cli/src/launcher.js` and once in `webdriverio/packages/wdio-runner/src/index.js`.

The `onPrepare` function accesses and updates the configuration loaded by `wdio-cli launcher`, `wdio-runner` executes afterwards and therefore resets any configuration update before the test itself executes.

However, as discussed earlier in this thread, the Sauce Service is able to update configuration.  This is because there is explicit code in `wdio-runner` to account for this;

![image](https://user-images.githubusercontent.com/144734/53018807-381b1000-344b-11e9-8025-8542787ffd7e.png)

http://webdriverio/blob/master/packages/wdio-runner/src/index.js#L53
