### ISSUE TITLE
Rename options waitforInterval and waitforTimeout

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1757]
I believe these options should be renamed to `waitForTimeout` and `waitForInterval`.

**Comment by christian-bromann** [comment]
These are options and I think this could be a good differentiator between option and command.

**Comment by monolithed** [comment]
> These are options

Ok, but `waitfor` looks like a typo

**Comment by christian-bromann** [comment]
I don't see the necessity to rename that option since it was written like that from the beginning. Also I don't really consider it as a typo, as

waitfor - Timeout -> timeout for all waitfor commands
as for
wait - For - Visible -> wait __for__ element to be visible

Other people could thing it is a number to wait for a certain timeout. I don't know. I don't have hard feelings about it but also don't see a reason to change it. It makes sense to me.

**Comment by efx** [comment]
As a developer just starting to use webdriverio, I find the `waitfor` prefixing of the configuration options confusing because the webdriver API has `waitFor` commands that are camel cased. I would favor another prefix to avoid confusion when interacting with the project.
