### ISSUE TITLE
Option to not start new session for every file

### ISSUE THREAD

**Issue by vitalets** [webdriverio/webdriverio#1774]
From docs:
> You might have already recognised that WebdriverIO creates for each spec a single Selenium session

In my tests I realized that all files can be executed in single session. I can just navigate to start url in `beforeEach` hook. I think such option could be useful and will make tests more fast as we will not spent time to start/stop sessions.

What do you think?

**Comment by christian-bromann** [comment]
> What do you think?

I don't think this is a good idea. You are right that booting a Selenium session is time consuming but running all tests in a single process is way more time consuming because tests don't run in parallel. Also getting a new Selenium session is a cleaner start for a test spec. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
