### ISSUE TITLE
waitForExist and waitForVisible after $

### ISSUE THREAD

**Issue by Danter7** [webdriverio/webdriverio#1867]
## The problem

`
$(selector).waitForExist()
$(selector).waitForVisible()
`

We have 2 problems here:

1. It will never success, because it will never refetch element from page.
2. `TypeError: Cannot read property 'selector' of undefined` after fail

## Environment

* WebdriverIO version: 4.5.2
* Node.js version: 7.5.0
* Standalone

## Details

We use WebdriverIO with tape-async like so:
`
yield driver.$(selector).waitForVisible()
`

**Comment by christian-bromann** [comment]
In standalone mode we can not really provide that syntax style as in wdio testrunner mode. So instead of running:

```js
yield driver.$(selector).waitForVisible()
```

do 

```js
yield driver.waitForVisible(selector)
```

Element as first citizen really only works in wdio testrunner context. In standalone mode `driver.$(selector)` returns a rejected promise and propagates the rejected promises to the chain. I would recommend to switch over to use the testrunner or pass in the selector as argument.
