### ISSUE TITLE
Jest Support

### ISSUE THREAD

**Issue by jankcat** [webdriverio/webdriverio#2052]
## The Enhancement

We should add support for [Jest](https://facebook.github.io/jest/).

Yes, I saw your [tweet](https://mobile.twitter.com/bromann/status/860829528314318848).

We have started using it for some UTs on some projects at work too... would be great to expand it into our other tests. 

## Details

With the popularity of React apps growing, Jest is being adopted as a testing framework by many for all kinds of JS testing.

**Comment by webOS101** [comment]
How would you see Jest working with this?  I was hoping I could combine my tests and my React code into a single file, but that's not possible.  The Jest code that manipulates the contents of the DOM, AFAIK, executes in the context of the browser, not in the context of Node, where the webdriver code executes.  I think this would sort of be the holy grail of testing react components if it could be made to happen.

**Comment by ebaranov** [comment]
+1

**Comment by gogoyqj** [comment]
@webOS101  https://github.com/gogoyqj/karma-event-driver-ext could release 'combine my tests and my React code into a single file'  in most of your test

**Comment by webOS101** [comment]
That's certainly one way to go about it, proxying the webdriver commands back to the server.  The API seems a tad cumbersome but it's certainly a nice accomplishment. Well done!

**Comment by KamenB** [comment]
Hi, I'm wondering whether this is currently in development?

**Comment by christian-bromann** [comment]
Not yet

**Comment by KamenB** [comment]
Thank you! :)

**Comment by patriciaorganBV** [comment]
how far off is this milestone?

**Comment by lukeggchapman** [comment]
If it helps anyone, I'm using the jest-matchers expect library so that it aligns closer to my workflow in Jest.

https://www.npmjs.com/package/jest-matchers
```
    before(capabilities, specs) {
        global.expect = require('jest-matchers');
    },
```

**Comment by christian-bromann** [comment]
I doubt this can be realised. Where should some one configure capabilities? Should it be executed with `wdio` or `jest`? In my opinion Jest is great for unit testing. We are using it in v5 for the whole project. However there are different challenges when people do e2e tests with different capabilities and different reporters. I don't see a value of running unit test and e2e test in one run. They should be separated. I would be happy if someone can come up with a solution but it won't be a high priority for us for now.

**Comment by guicejas** [comment]
Hi guys,
Is there any update about this milestone?

**Comment by christian-bromann** [comment]
@guicejas this is not high on my prio list

**Comment by fwouts** [comment]
Here is a minimal example of a WebdriverIO test written with the Jest framework: https://github.com/zenclabs/webdriverio-jest

Because WebdriverIO doesn't support Jest as a first-class citizen, this test suite leverages the
WebdriverIO remote API. This means that we need to do a few things ourselves, such as starting up
Selenium server as well as the browser. It also means that we must to use `async`/`await`
statements. Hopefully that unblocks you!

**Comment by christian-bromann** [comment]
I will have to close this. I hacked together a jest environment to run tests with a WebdriverIO client but unfortunately Jest doesn't allow to run these in parallel. I love Jest as unit test framework but it seems to not be really suited for e2e tests.

For everyone who is looking for writing tests in a jest environment I recommend to use the jasmine framework adapter which make the test look similar to jest unit tests. At this point I don't see any advantage of using the jest cli runner over wdio testrunner.

**Comment by 200even** [comment]
@christian-bromann can you explain in more detail why Jest isn't suited for E2E testing? I ask because we are currently using Jest with the WD.js library for a React Native project. I am evaluating a move to Webdriver.io due to some issues with the other library, but it would involve quite a bit of refactoring at this point and even more to move away from Jest.

**Comment by christian-bromann** [comment]
@jirving looking into this thread is all I need to see many reasons that people are interested into Jest support. If anyone wants to build a webdriverio environment, be my guest. That being said, I already tried to do that and I've seen major flaws using the jest test runner; and again the jest test runner is amazing but doesn't fit for running e2e tests. Here is why:

- tests will be run sequentially because e2e tests take long
- reporters don't give you a clue which environment is connected to which test so if you run (for puppeteer this doesn't matter much because it just runs chrome but in WebdriverIO this matters a lot)
- there is no chance to setup running tests in multiple environments (e.g. locally or in the cloud)
- as mentioned above, none of the unit test features of the test runner make much sense in the e2e test world

Since I've been explaining myself multiple times now I will lock this conversation. You can find us on the Gitter support channel in case you have some other ideas of why this still useful. Anyone is welcome to build a webdriverio jest environment. However the requirements to an unit vs e2e testrunner are quite different and should not be brought together. I understand the desire to run all tests in one unified environment. I know it would be simple and we love simple. That said, unit tests are way different than e2e tests and should not be mixed together. Always make sure you have tons of unit tests that cover all your code and then run just a small amount of e2e test covering your basic usecase scenarios.

**Comment by abjerstedt** [comment]
@jirving In the end it comes down to this: Jest is a test runner that basically implements jasmine and is used for unit testing, mocking and snapshots. Jasmine, mocha and cucumber are all testing frameworks that simply let you organize tests. (As christian said above, you can even write your tests in jasmine).

You can still implement webdriverio into your jest setup using the standalone runner. But we cannot integrate jest (a test runner) into our own test runner.

**Comment by christian-bromann** [comment]
Let's reconsider this.

**Comment by christian-bromann** [comment]
Moved to a project

**Comment by RajaBellebon** [comment]
> After our TSC meeting we agreed to reconsider this. If anyone wants to help, please reach out!

In [Atlaskit](https://atlaskit.atlassian.com/), we did our [integration](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/build/webdriver-runner/) between WebdriverIO and Jest runner - we are more than happy to help or contribute.

**Comment by christian-bromann** [comment]
> In [Atlaskit](https://atlaskit.atlassian.com/), we did our [integration](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/build/webdriver-runner/) between WebdriverIO and Jest runner - we are more than happy to help or contribute.

@RajaBellebon that is awesome! I am still not sure whether to create a `wdio` jest environment or run jest as a framework plugin. I will have a look into your solution and will experiment myself a bit. Thanks for sharing this!

**Comment by DavidPsl** [comment]
¡Hello! Any update about this issue ? @christian-bromann

**Comment by christian-bromann** [comment]
no

**Comment by tikolakin** [comment]
> > In [Atlaskit](https://atlaskit.atlassian.com/), we did our [integration](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/build/webdriver-runner/) between WebdriverIO and Jest runner - we are more than happy to help or contribute.
> 
> @RajaBellebon that is awesome! I am still not sure whether to create a `wdio` jest environment or run jest as a framework plugin. I will have a look into your solution and will experiment myself a bit. Thanks for sharing this!

hi @christian-bromann , do you have any recommendation by now ? 🥇

**Comment by christian-bromann** [comment]
> do you have any recommendation by now ?

We are working on an [assertion lib](https://github.com/mgrybyk/expect-webdriverio) that allows similar assertion than with Jest. This will allow to write tests that look like Jest tests. There is no reason for us to adapt the jest runner as it is not designed to work in an e2e test environment.

**Comment by christian-bromann** [comment]
A blog post about Jest support will be released soon!

**Comment by Geloloboy** [comment]
Do you have any updates on this?

**Comment by christian-bromann** [comment]
Ah, I guess we never got around to write the blog post. Two things on that:

- you can use the Jest testrunner with WebdriverIO, an example can be found here: https://github.com/erwinheitzman/jest-webdriverio-standalone-boilerplate
- you can use the WebdriverIO testrunner (recommended) and use Jests assertion library that we modified for the purpose of e2e testing: https://www.npmjs.com/package/expect-webdriverio

**Comment by munishusa** [comment]
I figure below dependencies are causing the conflict with Jest.

"@wdio/cli": "^6.8.0",
"@wdio/local-runner": "^6.8.0",
"webdriverio": "^6.8.0",

**Comment by waynevanson** [comment]
The template for jest doesn't allow the hooks in reporters to be called (it seems). I can theoretically load this into 

I'd prefer to run tests with Jest as the test runner and us webdriverio to drive the browser. Yes, I saw this is not recommended. 

I'm looking into this for a work project, so if/when I get an adapter together, I'll post it here.
