### ISSUE TITLE
config.baseUrl ignores path

### ISSUE THREAD

**Issue by edwardspec** [webdriverio/webdriverio#2094]
## The problem

In config.baseUrl, only hostname/port seem to be used.
If baseUrl also contains path (http://example.com/rootdir/), this path is ignored in further .url() calls.

## Code To Reproduce Issue

```
var webdriverio = require('webdriverio'),
	options = {
		desiredCapabilities: { browserName: 'firefox' },
		baseUrl: 'https://en.wikipedia.beta.wmflabs.org/w'
	};
webdriverio.remote(options).init().url('/index.php').getTitle().then( function( title ) {
	console.log( title );
}).end();
```

Result (incorrect): visiting [https://en.wikipedia.beta.wmflabs.org/index.php].
Expected result: visiting [https://en.wikipedia.beta.wmflabs.org/w/index.php].

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 5.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone

## Link to Selenium/WebdriverIO logs

WebdriverIO log: https://gist.github.com/edwardspec/a8ecb35c2fad70998d71b9ef4a158213
Selenium log: https://gist.github.com/edwardspec/1d2b8a71ee4c8e3046147d363fdf58e1

**Comment by edwardspec** [comment]
Investigation shows that [webdriverio/lib/protocol/url.js] uses `url.resolve(this.options.baseUrl, data.url)`
This method ignores the path from its first parameter:
```
$ node
> require('url').resolve( 'http://example.com/a/b', '/c/d' )
'http://example.com/c/d'
```

**Comment by re-fort** [comment]
You do not necessary need to start pass with `/`.
```
$ node
> require('url').resolve( 'http://example.com/a/b/', 'c/d' )
'http://example.com/a/b/c/d'
```
See also: https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_resolve_from_to

**Comment by christian-bromann** [comment]
@edwardspec please remove the `/` at the beginning. Thanks @re-fort

**Comment by mattc41190** [comment]
This issue still occurs when using a localhost path.

```
var url = require('url');
url.resolve('http://localhost:8080/friend', '') // 'http://localhost:8080/friend'
url.resolve('http://localhost:8080/friend', 'best') // 'http://localhost:8080/best'
```

**Comment by da70** [comment]
This bug is actually still an issue in webdriverio.
Note there is a subtle difference between the base URL used by @re-fort and that used by @edwardspec.  @re-fort's base URL has a trailing slash: 'http://example.com/a/b/'.  @edwardspec's does not have a trailing slash: 'http://example.com/a/b'.  In fact, this removal of the trailing slash is necessary to produce the desired result.  The removal of the leading slash from '/c/d/' is not enough by itself.

Demonstration:

```
$ node --version
v10.9.0
$ node
> require('url').resolve( 'http://example.com/a/b', '/c/d' )
'http://example.com/c/d'
> require('url').resolve( 'http://example.com/a/b', 'c/d' )
'http://example.com/a/c/d'
> require('url').resolve( 'http://example.com/a/b/', 'c/d' )
'http://example.com/a/b/c/d'
> 
```

Note that the first two attempts fail.  Only the third attempt with the addition of the trailing slash to the base URL and the removal of the leading slash from the path produce what the user expects.

This behavior is explained in the Node documentation for [url.resolve(from, to)](https://nodejs.org/api/url.html#url_url_resolve_from_to):

> url.resolve(from, to)#

> from <string> The Base URL being resolved against.
> to <string> The HREF URL being resolved.
> The url.resolve() method resolves a target URL relative to a base URL in a manner similar to that of a Web browser resolving an anchor tag HREF.
> 
> For example:
> 
> const url = require('url');
> url.resolve('/one/two/three', 'four');         // '/one/two/four'
> url.resolve('http://example.com/', '/one');    // 'http://example.com/one'
> url.resolve('http://example.com/one', '/two'); // 'http://example.com/two'

I encountered this bug while setting up a new WebdriverIO test suite, and adding a trailing slash to the `baseUrl` in the `wdio` conf file fixed the problem (leading slash in the path was already omitted).  The documentation for WebdriverIO `baseUrl` should probably be updated to reflect the above.

**Comment by ELLIOTTCABLE** [comment]
I was also just bitten by this — :+1: for it being added to the docs; as it's fairly unclear right now!

(Thanks a ton, @da70.)

**Comment by tlxtellef** [comment]
There is also this "fun" behavior when scheme is omitted.
```
> require('url').resolve( 'example.com:8080/a/b', '/c/d' )
'example.com:/c/d'
> require('url').resolve( 'example.com:8080/a/b/', '/c/d' )
'example.com:/c/d'
> require('url').resolve( 'example.com:8080/a/b/', 'c/d' )
'example.com:8080/a/b/c/d'
> require('url').resolve( 'example.com:8080/a/b', 'c/d' )
'example.com:8080/a/c/d'
```
Notice that the port number itself is missing from the 2 first ones.

**Comment by redmed86** [comment]
I'm still running into this.
`baseUrl: 'http://localhost:7225/#!/view1'` is outputting `INFO webdriver: DATA { url: 'http://localhost/#!/view1' }`. Can't seem to find a configuration where everything after the colon isn't ignored/cut off.
