### ISSUE TITLE
What I need to do when my custom command wants to throw error?

### ISSUE THREAD

**Issue by seth2810** [webdriverio/webdriverio#2120]
## The problem

Should I just throw an Error or maybe need to import webdriverio module, that looks like monolith , and then call webdriverio.ErrorHandler('CommandError', 'some message')? As I see, ErrorHandler, in second case, works like native Error wrapper https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ErrorHandler.js#L20-L22 and sets type property, that does not specially handle.

**Comment by christian-bromann** [comment]
The error handler is specifically made for Selenium response errors. You don't really need them.

Please don't file an issue when you don't get an answer on the Gitter channel. Sometimes people are just busy and can't answer on all questions. Please hold off and try again after a while. There is no reason to file such issue because it is not an issue. Thanks!
