### ISSUE TITLE
Attach to running session

### ISSUE THREAD

**Issue by alippai** [webdriverio/webdriverio#216]
How can I attach webdriverjs to a running saucelabs instance?
The code below doesn't work for me. :(

```
var client = webdriverjs.remote({
     host: 'ondemand.saucelabs.com',
     port: 80,
     user: "****",
     key: "****",
     logLevel: 'debug'
}).init({
    sessionId: runningInstanceSessId
}).call(function () {
     console.log('done');
});
```

**Comment by Jack-Barry** [comment]
## Goal
I have a testing scenario where a Windows application needs to be open and ideally can remain open for multiple test cases. (If there's an easier way to automate Windows applications in Node, please clue me in. Currently our strategy is to leverage _Appium_ and _WebdriverIO_, which is the closest I can get to something like `pywinauto` in Node.)

## Issue
The solution posted by @christian-bromann does not work for me, likely due to changes in the codebase since almost 5 years ago.

Here is my relevant code in a TypeScript project:

```ts
const { remote } = require('webdriverio')

async start(): Promise<void> {
  const client = await remote(options) // Options defined elsewhere in code
}
```

When I initiate the `client` with an object of options it works, but initiating with a string causes a Promise rejection error and thus I cannot attach to the existing session.

Is there an updated solution to this problem?

**Comment by christian-bromann** [comment]
@Jack-Barry yes, with v5 you can call the [`attach`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/index.js#L44) method that contains the same options as e.g. `browser.config` does including the session id.

**Comment by Jack-Barry** [comment]
@christian-bromann Thanks for the quick response!

I must be missing something, as I'm not quite able to implement this. Here's what I have as a smoke screen:

```ts
async click(sessionID) {
  const opts = Object.assign(options,
    sessionId: sessionID
  })
  const client = await attach(opts)
  await client.click()
}
```
Is that how `attach` is supposed to be used, or am I off base there?

When I call the `click` function with an existing `sessionID`, it throws:

```
(node:14244) UnhandledPromiseRejectionWarning: log.setLevel() called with
invalid level: undefined
```

Does this imply that there is something missing from my `options`, or is there something else going on here?

**Comment by christian-bromann** [comment]
> Does this imply that there is something missing from my `options`, or is there something else going on here?

Seems that the logLevel is missing.

**Comment by Jack-Barry** [comment]
I didn't have that set when calling the `remote` function so I figured it had a default value. After assigning a value of `error` explicitly in my options, I now receive this error:

```
(node:7440) UnhandledPromiseRejectionWarning: TypeError: client.click is not a function
```

**Comment by abjerstedt** [comment]
@Jack-Barry thats because client.click -> is not a function <-

In v5, you cannot interact with an element directly from the browser/client. It has to be called in the element as a first class citizen context: client.findElement(selector).click().

**Comment by Jack-Barry** [comment]
Got it. It's a bit confusing and a little frustrating because the TypeScript declarations in `@types/webdriverio` seem to be out of sync with the current `webdriverio` library, it looks like they are for v4. When I assign a variable as being of type `Client<void>` it says there is a `click` function available.

Still getting errors, but at least they are different errors now. The `findElement` function seems to require two parameters, `using` and `value`, but I can't figure out how to provide accessibility ID as the `using` param.

I'll keep wrestling with it a bit, thanks for your help gentlemen

**Comment by christian-bromann** [comment]
@Jack-Barry don't use `@types/webdriverio` anymore in v5. The latest version of WebdriverIO comes with typings included.

**Comment by Jack-Barry** [comment]
I think there still might be something wrong with the type declarations. If I write the following in a `.js` file (to avoid compile errors from TypeScript)

```js
const wdio = require("webdriverio");
const path = require("path");

async function demo() {
  const options = {
    logLevel: "error",
    port: 4723,
    capabilities: {
      platformName: "Windows",
      automationName: "WinAppDriver",
      platformVersion: "10",
      app: path.resolve("path/to/app.exe"),
      browserName: "",
      deviceName: "WindowsPC"
    }
  };

  const client = await wdio.remote(options);
  console.log(client.sessionId);    // This line prints the session ID
  console.log(client.getSession()); // This line causes an error
}

demo();
```

As I understand it, the `remote` function will return a `Client<void>` object. According to the `Client<void>` type, the `getSession` method is available. However when running this file an error is thrown saying that it isn't. Since I wrote this into a `.js` file that doesn't need to be compiled in `.ts` I took a look at the `client` object and can get the `sessionId` using `client.sessionId`. 

Translating this into a `.ts` file, I get the following:

```ts
import * as wdio from 'webdriverio'
import path  from 'path'

async function demo() {
  const options = {
    logLevel: "error",
    port: 4723,
    capabilities: {
      platformName: "Windows",
      automationName: "WinAppDriver",
      platformVersion: "10",
      app: path.resolve("path/to/app.exe"),
      browserName: "",
      deviceName: "WindowsPC"
    }
  }

  /* 
    The remote function requires a modifier, otherwise I can't compile
    The current documentation seems a little misleading here since it
    only shows an options object as a param. Also, both params are of
    any type which might lead to incorrectly formed objects
    */
  const mod = (o) => { return o }
  const client = wdio.remote(options, mod)

  // sessionId is not available on client so I can't compile
  console.log(client.sessionId)
}

demo()
```

I cannot compile the `.ts` file because it gives the following:

`"Property 'sessionId' does not exist on type 'Client<void>'."`

I'm tempted to go for a plain JavaScript solution to get rid of these headaches but would rather be able to ensure everything is correctly typed now to avoid headaches later. I'm willing to help contribute fixes to the types and docs, just not sure where to start.

**Comment by venoj** [comment]
I tried to access the same session from client in a new thread.
`
        const client = await attach({ sessionId: "..." });
`
Here the session id is valid and active. When I tried to execute anything with this client I got an error that the port is undefined:
`
TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at URLFactory.getInstance (file:///Users/.../node_modules/webdriver/build/request/factory.js:16:20)
    at async NodeJSRequest._createOptions (file:///Users/.../node_modules/webdriver/build/request/index.js:118:30)
    at async NodeJSRequest.makeRequest (file:///Users/.../node_modules/webdriver/build/request/index.js:59:94)
    at async Browser.wrapCommandFn (file:///Users/.../node_modules/@wdio/utils/build/shim.js:92:29)
    at async DeviceRegistry.getClient (/Users/.../deviceRegistry.js:55:20)
    at async swipe (/Users/.../swipe.js:5:24)
    at async /Users/.../test.js:26:13 {
  code: 'ERR_INVALID_URL',
  input: 'http://127.0.0.1:undefined/status'
}
`
I even tried:
`
        const client = await attach({ sessionId: "...", port: 4723 });
`
but it did not work.
I fixed it with hardcoding port to the node_modules file but I am interested if there is a more elegant solution.
For context I use it on an iPhone.
