### ISSUE TITLE
Run specific tests or run entire suite without a browser?

### ISSUE THREAD

**Issue by goyney** [webdriverio/webdriverio#2246]
WebDriver.io is great for UI tests but we would like to include our public facing API tests in our suite. For those, we don't need chromedriver booted up and a Chrome instance started; it is just wasted resources. We would like to keep all of our tests together and unified. We also have a lot of helpers and boilerplate set up we would like to reuse.

That being said, is it possible to indicate a test to not open a browser and simply run the mocha suite?

**Comment by christian-bromann** [comment]
> That being said, is it possible to indicate a test to not open a browser and simply run the mocha suite?

Just run a unit test for your API tests. Webdriver.io is the wrong tool for that

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by cpandith** [comment]
> > That being said, is it possible to indicate a test to not open a browser and simply run the mocha suite?
> 
> Just run a unit test for your API tests. Webdriver.io is the wrong tool for that

I really feel that its good to have option to run Tests without initiating driver

**Comment by christian-bromann** [comment]
> I really feel that its good to have option to run Tests without initiating driver

Can you elaborate? Why would you want to use WebdriverIO if you don't do browser/mobile tests?

**Comment by cpandith** [comment]
> > I really feel that its good to have option to run Tests without initiating driver
> 
> Can you elaborate? Why would you want to use WebdriverIO if you don't do browser/mobile tests?

I agree WebdriverIO is purely a UI Test Automation Framework, But I really feel that we should have option to execute API Tests with the same framework and initiating browser is the only thing which is blocking [Not Completely blocking even though we can execute Tests just by initiating browser (Chrome headless browser is good option) and executing API Tests ]. 

I really love to have option to execute any kind of Tests on one Framework which is more convenient instead of maintaining different framework. I think if we get this option WDIO framework can even more widely used.

**Comment by christian-bromann** [comment]
@cpandith I disagree here. A framework should be focused on one thing and should do that one thing really well. For WebdriverIO it is focused on UI Test Automation and already covers a lot of use cases by doing so.

Also, your API tests should be run before your WebdriverIO UI tests and therefor you should call these tests separately anyway. You can even use Mocha to run these API tests and don't need any additional dependencies. There is no need to maintain another framework.

**Comment by cpandith** [comment]
> @cpandith I disagree here. A framework should be focused on one thing and should do that one thing really well. For WebdriverIO it is focused on UI Test Automation and already covers a lot of use cases by doing so.
> 
> Also, your API tests should be run before your WebdriverIO UI tests and therefor you should call these tests separately anyway. You can even use Mocha to run these API tests and don't need any additional dependencies. There is no need to maintain another framework.

Actually we are using Cucumber to write both UI and API Tests, I felt it would be very nice if we have an option to run tests without driver, for example if i just want to run set of API Tests I can do that easily if i have option to run test without driver. Now, I am initiating driver and just running API Tests when the driver is running in the background.

**Comment by vhanich-es** [comment]
As for me, we run some API setup steps before each UI test too, so it would be nice if there were an option not to open browser on some tests.

**Comment by Vishnu1067** [comment]
Feel to have this feature but understand the concept of wdio. Since it is old post, you guys might found the different approach to deal with this situation or continue api test with wdio in headless mode.

I recently came across this situation and created framework for UI & Api. (Need Api in same framework so that it can be reutilized in some UI tests to prepare test data). For API, I use jest-cucumber and for UI wdio. if have any common methods, we can have shared file and place them there.

Ref: https://github.com/bencompton/jest-cucumber/blob/master/docs/ReusingStepDefinitions.md
