### ISSUE TITLE
WDIO Configuration Helper doesn't work using yarn

### ISSUE THREAD

**Issue by gsccheng** [webdriverio/webdriverio#2319]
## The problem

WDIO Configuration Helper doesn't work using `yarn@1.0.1`.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: n/a
* Additional wdio packages used (if applicable): n/a

## Details
```
11:18 $ ./node_modules/.bin/wdio config

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? jasmine
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  dot - https://github.com/webdriverio/wdio-dot-reporter,  spec - https://github.com/webdriverio/wdio-spec-reporter,  allure - https://github.com/webdriverio/wdio-allu
re-reporter,  json - https://github.com/fijijavis/wdio-json-reporter,  concise - https://github.com/FloValence/wdio-concise-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  selenium-standalone - https://github.com/webdriverio/wdio-selenium-standalone-service,  webpack - https://github.com/leadpages/wdio-webpack-service,  w
ebpack-dev-server - https://gitlab.com/Vinnl/wdio-webpack-dev-server-service
? Shall I install the services for you? Yes
? Level of logging verbosity verbose
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/path/to/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at renderConfigurationFile (/path/to/node_modules/webdriverio/build/lib/cli.js:292:28)
    at /path/to/node_modules/webdriverio/build/lib/cli.js:282:17
    at /path/to/node_modules/npm-install-package/index.js:31:5
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I'm opening this to track the issue that is related to here:
[https://github.com/webdriverio/webdriverio/issues/2215](https://github.com/webdriverio/webdriverio/issues/2215)
[https://github.com/webdriverio/webdriverio/issues/2218](https://github.com/webdriverio/webdriverio/issues/2218)

## Link to Selenium/WebdriverIO logs

N/A
## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment]
@gsccheng please see https://github.com/webdriverio/webdriverio/issues/2218#issuecomment-320152239 .. I was not able to reproduce this. So either you can prepare a PR with a fix or try the suggested workaround. Thanks!

**Comment by tsemana** [comment]
Strange that this isn't reproducible.  Here's a repo with only webdriverio as a dependency:
https://github.com/tsemana/wdio_yarn_error

Doing this fails:

```console
yarn
yarn run wdio

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? cucumber
? Shall I install the framework adapter for you? Yes
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step_definitions/
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  phantomjs - https://github.com/cognitom/wdio
-phantomjs-service
? Shall I install the services for you? Yes
? Level of logging verbosity verbose
? In which directory should screenshots gets saved if a command fails? ./features/errorShosts/
? What is the base url? http://localhost:3000
```

the console message is

```console
Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/tony/Code/Learn/wdio_yarn/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at renderConfigurationFile (/Users/tony/Code/Learn/wdio_yarn/node_modules/webdriverio/build/lib/cli.js:292:28)
    at /Users/tony/Code/Learn/wdio_yarn/node_modules/webdriverio/build/lib/cli.js:282:17
    at /Users/tony/Code/Learn/wdio_yarn/node_modules/npm-install-package/index.js:31:5
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
```

This command, from the base repo, successfully creates the config file:

```console
npm install
./node_modules/.bin/wdio
```

**Comment by fenderil** [comment]
I had reproduced issue using:
`node node_modules/webdriverio/bin/wdio config`
with
yarn@1.0.2
webdriverio@4.8.0
node@8.5.0

Selected for config:
? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? cucumber
? Shall I install the framework adapter for you? Yes
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions
? Which reporter do you want to use? dot - https://github.com/webdriverio/wdio-dot-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?
? Level of logging verbosity verbose
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost:6060

After start of installation wdio had deleted half of webdriverio package.

Possibly, it is associated with files structure, because packages installation with npm had solved this problem.

**Comment by ayoolaao** [comment]
**My observations:**
- You install 'webdriverIO' with yarn and the yarn.lock is updated/created.
- Then you run: './node_modules/.bin/wdio config' and select config options
- I think the issue is that the WDIO configuration helper uses npm to install selected dependencies (e.g spec reporter, jasmine etc), 
- hence creating a package-lock.json file. Causing this issue because webdriverio in yarn.lock and not in the package-lock.json with selected reporters, frameworks etc.

**Walk-around fix:**

1. Install 'webdriverio' with: `yarn add -D webdriverio`
2. Run wdio config helper: `./node_modules/.bin/wdio config
![screen shot 2018-10-17 at 5 00 21 pm](https://user-images.githubusercontent.com/23148951/47121128-a9914a80-d22e-11e8-8b46-401aad9d3e18.png)
`
3. Select desired options but don't the have helper install any of them for you, by responding with 'no' (e.g Shall I install the framework adapter for you? No).
4. Configuration file was created successfully!
5. Manually install the required services, frameworks and/or reporters either by:
	a. Adding them to your package.json file and running yarn install
	b. Yarn add each one of them




```
Desktop/a-yarn ❯❯❯❯❯ yarn add -D webdriverio
yarn add v1.10.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
success Saved 137 new dependencies.
✨  Done in 4.99s.
Desktop/a-yarn ❯❯❯❯❯ ./node_modules/.bin/wdio config

WDIO Configuration Helper

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? jasmine
? Shall I install the framework adapter for you? No
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? No
? Do you want to add a service to your test setup?  selenium-standalone - https://github.com/webdriverio/wdio-se
lenium-standalone-service,  visual-regression - https://github.com/zinserjan/wdio-visual-regression-service
? Shall I install the services for you? No
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Configuration file was created successfully!
To run your tests, execute:

$ wdio wdio.conf.js

Desktop/a-yarn ❯❯❯❯❯                                                                                       26s
```
