### ISSUE TITLE
general fragility

### ISSUE THREAD

**Issue by allan-bonadio** [webdriverio/webdriverio#2389]
## The problem

WDIO fails often for me, for seemingly unpredictable reasons.  The failures tend to be deterministic and repeatable, at least on a given day.  It's not unusual for test scripts that worked last month or last week to suddenly fail.  This is NOT a problem with not waiting long enough for things to be visible; ridiculously long waits don't solve the problem.  Sometimes, rephrasing the selectors solves the problem.  Often I have to use a totally different approach (even for the same situation in a different part of the app).

## Environment

* WebdriverIO version: 4.6.2 and older
* Node.js version: 6.3.1 and probably others
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO test runner
* if wdio testrunner, running synchronous or asynchronous tests:  The app is pretty asynchronous but all my WDIO code runs synchronously, written as top-to-bottom scripts.
* Additional wdio packages used (if applicable): bug happens with both Chrome and Gecko drivers.  No funny add-ons for WDIO.

## Details

The most common problem seems to be finding CSS selections for things that are there in the dom.  A typical message might be 

    Failed: An element could not be located on the page using the given search parameters (\"body .jasmine_html-reporter\").

Now, this resembles a beginner problem where you don't put in the right delays or the right event handling.  Things are asynchronous and you have to tinker to get it all right, OK.  Many times I have these problems that are easily solved; that's not this problem.  With this bug, I've put in delays of several minutes, waiting for something to be visible to WDIO.  It all just sits there, motionless.  It's visible on the screen for the whole time, but the WDIO expression to go get a handle on it bombs and fails the test.

I've had instances where I stop with browser.debug(), right in the middle, before the WDIO code that tries to get a handle on some element in the browser dom.  I can physically see the element on the page on my screen.  I can take the $() expression, copy out of the test source code, paste it directly into the browser debugger (this is interactively on my mac), and see that jQuery can find it fine, given the same selector and same syntax.  So it's not a problem that the selector is bad, the element isn't there, or I didn't wait for WDIO long enough; it's blatantly not working.

Some things I've fixed with execute(), actually running code in the browser, where it runs reliably.  I do simple things  like look for an element and click it or grab the text.  Even this doesn't work all the time.

## Code To Reproduce Issue [ Good To Have ]

The code I'm testing is large and proprietary.  I've tried to get the bug to happen on smaller examples but so far, no luck. 
I've been suffering with this bug for months and management is not pleased with my decision to go with WDIO.  I'm writing new tests without WDIO because even the WDIO test scripts I've written stop working after a while.  It would be great if this stuff worked; it's really great when it runs, it's just a rare moment when a script runs all the way through without getting a failure that has nothing to do with my code.

I'm writing in the hope that you have some ideas for me to try or a plugin or two, with some workarounds, if you recognize this situation.  Or, putting in some trace statements to see what's going on.  Isolating this down to a simple test case will also take a chunk of time that isn't easy to spare these days.  Anything you can do to help would be appreciated.

 I'm at abonadio@neustar.biz , thanks!

**Comment by christian-bromann** [comment]
@allan-bonadio thanks for bringing this up. I think I understand your frustration and I've experienced such issues multiple times. Without any specific examples I can't give any advice here. Your issues might be caused by the browser driver, maybe it is a race condition that happens due to bad network conditions. We try to build WebdriverIO in way that it suppose to work just like that and overcome common issues when writing automated tests. At the end the framework only sends HTTP request to a browser driver which is then executing it on the browser. If you get errors like

```
Failed: An element could not be located on the page using the given search parameters (\"body .jasmine_html-reporter\").
```

it is because the browser actually can't find the selector you are looking for. You have to check in the driver logs why that is. I recommend trying to play around with the WebDriver timeouts or use some of the explicit WebdriverIO wait for commands which you probably did already.

Please reach out with some concrete examples in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Happy to help there at any time.

**Comment by nmehta01** [comment]
I have a similar problem and have tried lots of things similar to @allan-bonadio. I am considering dropping wdio for using selenium directly.
