### ISSUE TITLE
isVisible() failing with "An unknown server-side error"

### ISSUE THREAD

**Issue by mkj28** [webdriverio/webdriverio#2398]
## The problem

Seeing this:
```
node_modules/fibers/future.js:313
						throw(ex);
						^
Error: An unknown server-side error occurred while processing the command.
    at isVisible() - at elements() - isVisible.js:54:17
```

while running tests on SauceLabs. Message I see on SauceLabs side is "Unable to find element with css selector" - and since the isVisible is called in:
```
browser.waitUntil(
      () => this.nextButton.isVisible(),
      '`Next` button was not displayed'
    );
```
I would expect for it to be retried until the element is there (actually it showed up since in SauceLabs I see it in the recording of the screen).

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 7.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): N/A

SauceLabs:
"version": "11.0",
"platform": "Windows 10",
"browserName": "internet explorer",
"iedriverVersion": "3.4.0",
"screenResolution": "1024x768",
"loggingPrefs":{"driver": "ALL",
"browser": "ALL"},
"handlesAlerts":true,
"requestOrigins":{"url": "http://webdriver.io",
"version": "4.6.2", <<--- not sure why it shows 4.6.2?
"name": "webdriverio"},
"seleniumVersion": "3.4.0"

## Details

@christian-bromann just in case it's at https://saucelabs.com/beta/tests/355ab4bb070241fe9fe284d54d064280/commands#825

## Link to Selenium/WebdriverIO logs
https://gist.github.com/mkj28/9f5e75265f1ea7e522af7453425a175c - relevant part closer to the bottom

## Code To Reproduce Issue [ Good To Have ]

Internal app, hard to provide repro case, but will try

**Comment by christian-bromann** [comment]
Can you try to increase the waitUntil interval? It seems that IE is having trouble refetching the element. When it runs the condition the first time it expectingly fails due to:

```
Unable to find element with css selector == .conversation-response-controls .conversationWorkflowButtons-nextButton
```

The second try fails then because of an unknown error:

```
Error: An unknown server-side error occurred while processing the command.
```

Maybe an other option would be to do:

```js
    browser.waitUntil(
      () => this.nextButton.isExisting() && this.nextButton.isVisible(),
      '`Next` button was not displayed'
    );
```

Which would not cause the first error to happen. Closing this after all because it is not an WebdriverIO issue and more an IEDriver issue. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.
