### ISSUE TITLE
Accessing iframe returns not exists error

### ISSUE THREAD

**Issue by arunaousula9421** [webdriverio/webdriverio#2423]
Hi @christian-bromann , I am trying to access an iFrame using browser.frame()
                  
 

```
<div class="mortgage-calculator__input-field ">
                 <label class="mortgage-calculator__input-field-label" for="propertyPrice">Price </label>
                 <input id="propertyPrice" class="mortgage-calculator__input-field-text-input" type="text"/>
                   </div>
```

This is my code
 
```
browser.waitForExist('iframe[id="Price"]');
   var abc = browser.element(('iframe[id="Price"]')).value;
   browser.frame(abc);
```

Everytime it returns element is not visible.
I am trying to get the text in the label class which returns Price
Can someone please let me know how to handle iframes??

**Comment by DDunc** [comment]
I'd like to point out that moving documentation and bug resolution from a persistent and searchable format onto a third-party (effectively) non-searchable and non-persistent format is an anti-pattern. If it's a pure usage question perhaps stack overflow would be a better primary location with the gitter chat provided as secondary resource?

I'm a big fan of this project and the docs are generally way above average, but I was experiencing the same issue as the OP and the way this issue was closed provides no immediately useful information. I'm a little concerned that an issue was closed because it "not necessary an issue", since that reasoning could be used to close literally any issue.

**Comment by christian-bromann** [comment]
@DDunc I usually always provide an high level answer to the question. Not sure why I closed this right away. Probably because it is hard for another person to recreate the problem. If you could provide an example (something I can reproduce on my machine) I am happy to help you out.
