### ISSUE TITLE
setValue is omitting digit 3 while login using selenium and mochajs

### ISSUE THREAD

**Issue by suwarna-wade** [webdriverio/webdriverio#2445]
`loginSU(data) {
		this.withPass.click()
		//const dtls = Object.assign({}, loginDtls)
		b.pause(2000)
		this.phone.setValue("9833445678")
		b.pause(2000)
		this.password.setValue("123456")
		this.loginBtn.click()
	}`

This is my login function which I am calling in my index.js file

`it('should select' +' '+ service + ' '+' service and ask for login if owner is not logged in',()=>{
    if(Homepage.loginModal.isVisible() == true){
      Homepage.loginSU()
      b.debug()
      assert.equal(Homepage.prop_pic.isVisible(), true)
    }
    else{
      console.log('user is already logged in')
    }
  })`

Issue: When I run the test, it enters the number and password omitting digit 3 due to which the test case is filling.
Kindly help with the issue as I do not find any related issue on stack.
<img width="360" alt="screenshot at nov 15 16-23-09" src="https://user-images.githubusercontent.com/24934465/32832437-72eafdac-ca21-11e7-85d1-884ba92a4425.png">

**Comment by christian-bromann** [comment]
Since I don't have any logs for or meta information for this I can just assume that you ran this with Chrome where this error is known and not caused by WebdriverIO. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
