### ISSUE TITLE
Unable to start phantomjs with wdio-phantomjs-service

### ISSUE THREAD

**Issue by fogrizovic** [webdriverio/webdriverio#2495]
## The problem

1. Installed service from instructions [here](http://webdriver.io/guide/services/phantomjs.html) 
2. Set capabilities in wdio.conf.js to
capabilities: [
        { browserName: 'phantomjs' }
    ],
3. Started tests and I get this error:

            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        
This is what I get in [selenium log](https://gist.github.com/fogrizovic/0f82955a9b9e747c073de76b1cb72955) 

## Environment
* Operating system: Windows 10
* WebdriverIO version: 4.9.11
* Node.js version: v8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio-selenium-standalone-service
* Additional wdio packages used (if applicable): wdio-phantomjs-service  0.2.2

**Comment by christian-bromann** [comment]
This has nothing to do with Phantomjs, your spec file is properly wrongly constructed. Since you didn't shared the spec file I can only guess but it looks not like an issue of WebdriverIO. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
