### ISSUE TITLE
Chaining with isExisting gives inconsistent results

### ISSUE THREAD

**Issue by webOS101** [webdriverio/webdriverio#2510]
## The problem

Calling `isExisting()` on a non-existent element when chaining can produce false positives as the chain is disregarded.

## Environment

* WebdriverIO version: 4.9.11 (wdio 1.0.3)
* Node.js version: v8.1.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): both
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): n/a

## Details

HTML source
```html
<html>
	<body>
		<div id="first">
			<div class="class">one</div>
			<div class="class">two</div>
		</div>
		<div id="second">
			 Empty
		</div>
	</body>
</html>
```
REPL output:
```
> $('#second').$('.class').isExisting()
true
> $('#second .class').isExisting()
false
```

Expect both commands to return the same result.

The problem is that once the selector fails, it re-executes with `elements()` at the root scope, returning the array of matching divs.

## Link to Selenium/WebdriverIO logs

Selenium log: https://gist.github.com/webOS101/c55ec4a097dfbdcc2fa49b5e9f82c802

## Code To Reproduce Issue [ Good To Have ]

See above.

**Comment by treyturner** [comment]
I tried patching these changes into 4.13.1, but it didn't resolve my issue. I'm still getting false positives for `.isVisible()` and `.isExisting()` due to the root scope issue. Very much looking forward to a fix. This is purported to be fixed in the v5 beta according to #2571, but I tried `5.0.0-beta14` and the problem persists.

**Comment by webOS101** [comment]
That's sad to hear, on both parts. :(  We haven't updated to 5.0 beta yet so I haven't tested any of my failure cases there.

**Comment by christian-bromann** [comment]
Let's get this fixed then before we release it.

**Comment by treyturner** [comment]
I'm having a hard time figuring out if this is the issue I'm suffering, or if it's something else entirely. In `5.0.0-beta.2`:
```
> // Here's code for a dropdown. When the anchor is clicked, a <ul> appears in div.options.
> apps.settings.window.content.general.locationFormat.dropdown.container.getHTML()
'<td>
    <div class="drop-down-menu undefined">
        <a class="btn selection ">Decimal Degrees</a>
        <div class="options">
        </div>
    </div>
</td>'

> // Check to see if the list exists (it doesn't)
> apps.settings.window.content.general.locationFormat.dropdown.list.isExisting()
true

> // Wait, what exists? Check the object
> apps.settings.window.content.general.locationFormat.dropdown.list
{ type: 'NoSuchElement',
  message: 'An element could not be located on the page using the given search parameters.',
  state: 'failure',
  sessionId: '02fbb40bce8f0e05bb4ba16b32d4f180',
  value: null,
  selector: 'ul',
  _status: 7 }

// Those two responses don't seem to agree, let's check isVisible()
> apps.settings.window.content.general.locationFormat.dropdown.list.isVisible()
[ false, true, false, false, true, true ]
```
So I'm wildly lost now; it seems like `isExisting()` is returning an incorrect response, and `isVisible()` seems to be searching from a higher scope and building an array, which seems doubly wrong since that getter returns `$` as opposed to `$$`:
```
class Dropdown {
  constructor(selector, parent = undefined) {
    this.selector = selector;
    this.parent = parent;
  }
  // Allow optional scope specification when instantiating
  get container() {
    if (typeof this.parent === 'undefined') {
      return $(this.selector);
    } else {
      return this.parent.$(this.selector);
    }
  }
  get subcontainer() { return this.container.$("div.drop-down-menu"); }
  get list() { return this.subcontainer.$("ul"); }
}
```
Nevertheless, if I type `$("ul")` into jQuery on my page, I get 6 hits. I do pass in the parent in this case, so the 6 `<ul>` tags are well outside anything passed into this instance:
```
> apps.settings.window.content.general.locationFormat.dropdown.parent.getHTML()
'<tr id="settings-location-format">
    <td>Location Format</td>
    <td>
        <div class="drop-down-menu undefined">
            <a class="btn selection ">Decimal Degrees</a>
            <div class="options"></div>
        </div>
    </td>
</tr>'
```
I see this issue was put into "To Do" for v5 after the issue was closed. Am I right in thinking this issue describes my problem?

**Comment by christian-bromann** [comment]
> but I tried `5.0.0-beta14` and the problem persists.

Not true, this is fixed with v5. Feel free to propose a fix in the v4 branch.

**Comment by sup-engineer** [comment]
I am using wdio 5.11.0 . while using chained selectors with isExisting() , the result is as expected when the elements (selector1 & selector 2) do exist, i.e. $(selector1).$(selector2).isExisting() = true . However, when the elements do not exist in the DOM (both selector 1 & 2), then instead of getting (selector1).$(selector2).isExisting() = false, I get a run time exception that "Can't call $ on element with selector "selector 1" because element wasn't found"

Using isExisting() on just one of the selectors (either 1 or 2) works fine in the false case. Is this behavior related to the issue mentioned with chaining in this thread?
