### ISSUE TITLE
WebdriverIO does not install extension in chrome

### ISSUE THREAD

**Issue by WarleyGabriel** [webdriverio/webdriverio#2567]
## The problem

WebdriverIO does not install extension in chrome, after configuration wdio.conf.js.
Also, headless mode isn't working.
I use https://github.com/zalando/zalenium

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 5.6.0
* WebdriverIO Testrunner

## Details

Driver is create with log: 
`{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","chromeOptions":{"extensions":["[base64] 217904 bytes"],"args":["--headless","--disable-gpu"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}}}`

## Code To Reproduce Issue [ Good To Have ]

var fs = require('fs');
var Buffer = require('buffer').Buffer;
var extensionChrome = fs.readFileSync('EXTENSION_PATH/EXTENSION_NAME.crx');

```
capabilities: [{
        browserName: 'chrome',
        chromeOptions: {
            extensions: [Buffer(extensionChrome, 'binary').toString('base64')],
            args: ['--headless', '--disable-gpu']
        }
    }
]
```

**Comment by christian-bromann** [comment]
@WarleyGabriel it is not WebdriverIO how is responsible for installing the extension, it is your automation driver (e.g. Chromedriver). So it only passes along the information. if it doesn't work it is either because you have passed these information the wrong way or your automation backend doesn't install it properly.
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by WarleyGabriel** [comment]
Ok, I discovered the problem. 

```
capabilities: [{
        browserName: 'chrome',
        "goog:chromeOptions": {
            extensions: [Buffer(extensionChrome, 'binary').toString('base64')],
            args: ['--headless', '--disable-gpu']
        }
    }
]
```
Now the extension and headless mode is work.
Thanks :+1:
