### ISSUE TITLE
ButtonUp, moveTo... documentation

### ISSUE THREAD

**Issue by Mykybo** [webdriverio/webdriverio#2586]
The documentation for them says:

> This command is deprecated and will be removed soon. Make sure you don’t use it in your automation/test scripts anymore to avoid errors.

but provides no alternative. What should I use if not these?

**Comment by christian-bromann** [comment]
Please use the [actions](http://webdriver.io/api/protocol/actions.html) command. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by christian-bromann** [comment]
Also it says: `It is recommended to use the action command as a replacement for this.`

**Comment by pmerwin** [comment]
... but actions command has not been implemented in chromedriver or geckodriver and is poorly documented.

**Comment by christian-bromann** [comment]
@pmerwin it is implemented in the latest Geckodriver. The poor documentation is not necessarily an issue of WebdriverIO

**Comment by pmerwin** [comment]
hmm I still see unimplemented errors, fair enough on the docs :)

**Comment by phal0r** [comment]
@christian-bromann I see your point, but I run into the same problem like @pmerwin and I know that such a test setup consists of a lot of moving parts and therefor it is hard for developers to get an overview, which part lacks support. I too wanted to use the actions command, since the other ones are deprecated, installed newest webdriverio, newest selenium, newest webdriver and so on and I got the error message `unimplemented command: session/d190433b80f7953fb01550032285ae28/actions`. But for me it was totally unclear, which part lacks support. wdio? a wdio plugin? selenium? the web driver?

So of course, it is not in the responsibility of wdio to update the status for all the webdrivers to show support, but I want to propose to give a hint in the docs and related links like so:

```
Check, if the webdrivers you want to use already have support for the actions command:
ChromeDriver: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/chromedriver_status.md
GeckoDriver: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status
SafariDriver: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/WebDriverEndpointDoc/Commands/Commands.html
```

This won't add load to wdio to update the docs, when a new webdriver version is released and provides enough information for the reader to find the cause of this error
