### ISSUE TITLE
Can I use xpath axes selectors?

### ISSUE THREAD

**Issue by YuxuanLin** [webdriverio/webdriverio#2664]
## The problem

I want to use xpath axes selectors to specify nth element in dom. Like:
`<div>`
       ` <span> 01</span>`
        `<span> 02</span>`
`</div>`

I want to get the second span.
Now if I use '//span[text()="02"]/preceding-sibling::*]' test case will fail with:

invalid selector: Unable to locate an element with the xpath expression //span[text()="Currently Active Promote
Services"]/preceding-sibling::*] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//span[text()="Currently Active Promote Services"]/preceding-sibling::*]' is not a valid XPath expression.

## Environment

* WebdriverIO version: lastest
* Node.js version: 8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Selenoid
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue
console.log(
	browser.element('//span[text()="02"]/preceding-sibling::*]').getText()
);

**Comment by BorisOsipov** [comment]
Your xpath is invalid due to last ] - //span[text()="02"]/preceding-sibling::***]**
the corect one is `//span[text()="02"]/preceding-sibling::*`

Join our [Gitter ](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)for these kind of questions. This is not necessary an issue of WebdriverIO.
