### ISSUE TITLE
What is a WebElement JSON?

### ISSUE THREAD

**Issue by worc** [webdriverio/webdriverio#2728]
I'm looking at the docs for [elements](http://webdriver.io/api/protocol/elements.html) and it says that the function returns an array of WebElement JSON objects. But I'm not finding any other reference on the Webdriver website about what a WebElement is, what shape it takes, or how it can be used within Webdriver.

The docs mention that there's an *element ID* packed into this JSON, but I've tried using that value in follow-on queries and get an `invalid selector: An invalid or illegal selector was specified` error for my troubles.

Is there some other documentation or concise example somewhere that better explains what this object is and how I should be using it?

**Comment by christian-bromann** [comment]
An element id is the id you get when you query an element, e.g.
```js
> var elem = $("body")
> elem
{ sessionId: '43ac0d8e424fa94fbaaf9dfeffdc95ac',
  value:
   { ELEMENT: '0.17104396728038185-1',
     'element-6066-11e4-a52e-4f735466cecf': '0.17104396728038185-1' },
  selector: 'body',
  _status: 0 }
```
The element id here is `0.17104396728038185-1`. You can use that to use protocol commands that require this id like `elementIdClick`, e.g.
```js
> browser.elementIdClick("0.17104396728038185-1")
```
WebdriverIO provides an abstraction around this, so that you can just do `browser.click("body"). It fetches the element under the hood and clicks on it. Notice the difference between selector and element id. You can not use the element id for the click command.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by worc** [comment]
ok, that was my assumption, but i was getting errors when trying to select on those ID strings. if i come across that bug again i'll try to isolate it and post a specific bug report on that. right now this is more of a documentation issue, the elements page didn't really provide any context or valid use-cases for its return value.
