### ISSUE TITLE
ReferenceError: $$ is not defined

### ISSUE THREAD

**Issue by basickarl** [webdriverio/webdriverio#2754]
It states on the first page in webdriverio page:

> With the $ and $$ functions WebdriverIO provides useful shortcuts which can also be chained in order to move deeper in the DOM tree without using complex xPath selectors.

It even states an example:

```
var expect = require('chai').expect;
describe('webdriver.io api page', function() {
    it('should be able to filter for commands', function () {
        browser.url('http://webdriver.io/api.html');

        // filtering property commands
        $('.searchbar input').setValue('getT');

        // get all results that are displayed
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });

        // assert number of results
        expect(results.length).to.be.equal(3);

        // check out second result
        results[1].click();
        expect($('.doc h1').getText()).to.be.equal('GETTEXT');
    });
});
```
I however get the error when running tests via mocha with nodejs locally:

`ReferenceError: $$ is not defined`

All my other tests are working and webdriverio seems to be working as intended.

Using webdriverio 4.12.0 with nodejs.

**Comment by basickarl** [comment]
Ok just found the answer: http://webdriver.io/api/utility/$$.html

`Using the wdio testrunner this command is a global variable else it will be located on the browser object instead.`

**Comment by svaru001** [comment]
ReferenceError: $ is not defined
      at Context.<anonymous> (test1.js:24:16)
I am facing this error, how to resolve?

**Comment by jaffamonkey** [comment]
Another webdriverio issue discussion that disappears into ether ...

**Comment by mgrybyk** [comment]
What do you mean? This was closed because it is not reproducible

**Comment by AzySir** [comment]
> Another webdriverio issue discussion that disappears into ether ...
@jaffamonkey  amazing isn't it. The versions changed every 20 seconds there's constant new issues in the new versions. And the documentation is literally horrible. 

Then they close it - super frustrating isnt it !!!

**Comment by christian-bromann** [comment]
@AzySir can you please be more constructive please?

**Comment by AzySir** [comment]
@christian-bromann  just making an observation - otherwise a fantastic framework. Unfortunately the changes do frustrate me especially during setup I think I've almost learnt a new way to setup every time I've used it.

**Comment by mgrybyk** [comment]
I'd recommend to play around with boilerplate projects, especially if you are new to javascript.

**Comment by christian-bromann** [comment]
@AzySir can you list some specific examples where changes created confusion and problems?

**Comment by AzySir** [comment]
@mgrybyk  @christian-bromann  it could be just me but literally every time I try a boilerplate or a new clean set up I have a different issue. I believe the documentation isn't clear enough then when you look at the GitHub issues they seem to be cut short as jaffamonkey was referring to like there is a minimum standard to understand before you try wdio. 

I haven't touched wdio for around 6-12 months now and I return back to missing frameworks from the initial setups. When I follow the instructions here https://webdriver.io/docs/gettingstarted.html I can get the first half of the instructions working. However the second half after the title "Let's get serious" I seem to encounter issues. Is this from versioning? Is this from bad coding? Possibly however I'm just following in the instructions. 

I copy and paste the code, change the geckodriver dir and use the same directories then hit the issue below.

**Error**
```
2019-05-23T15:37:49.796Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
2019-05-23T15:37:49.896Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "chromedriver"
2019-05-23T15:37:49.927Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-chromedriver-service".
Error: Cannot find module 'chromedriver'
.........
```

Then you might tell me well why don't you install the wdio-chromedriver-service - I did that too and another error. These are all new errors since the last time I used wdio. I am sure the next time I use it there will be more errors again just for the initial setup. Then you're spending time googling it and that's where the frustration kicks in again referring to jaffamonkey's comment "Another webdriverio issue discussion that disappears into ether ..." 

Unfortunately not all of us are constantly using wdio... so we can't stay up to dates with the versions

**Comment by mgrybyk** [comment]
@AzySir yeah, agree, there are some issues with chromedriver service.

Thank you for letting us know. However in order to make thing clearer it would be really awesome to record your steps and post them.

**Comment by AzySir** [comment]
@mgrybyk I'm assuming from an update? Do you guys do a regression test on that "Getting Started" page to see if these issues do come by for anyone using wdio for the first time?

**Comment by mgrybyk** [comment]
I'm going to update getting started.

There is lack of information with chromedriver service and services in general. 
In order to make chromedriver service work you have to install chromedriver and add `path: '/'` to wdio.conf.
Never used chromedriver service before, found out this yesterday and have to agree this is not obvious. 

Alternatively can choose selenium standalone instead, but note that it requires jdk to be installed. I like it more because it work with multiple drivers out of the box, ex firefox, safari, chrome.

**Comment by mgrybyk** [comment]
It's difficult to guess all the combinations people may choose in wdio cli. Ex, I'm using selenium grid instead of services. Because of that I'm not seeing any issues with chromedrivers, etc in my daily work.

**Comment by CrispusDH** [comment]
Sorry for off topic, but @mgrybyk why do you not use Selenoid instead of selenium grid?

**Comment by mgrybyk** [comment]
I have grid configured to run tests in browsers and mobile devices, so I have all the nodes connected to it.

Selenoid doesn't help running appium tests on real android and ios devices. Also, I can't run docker on my mac mini due to lack of resources...

So it was way easier to configure grid, never had any issues with it and browser nodes, most pain comes from appium itself, not even nodes, but that's another story.

**Comment by AzySir** [comment]
> 

> I'm going to update getting started.
> 
> There is lack of information with chromedriver service and services in general.
> In order to make chromedriver service work you have to install chromedriver and add `path: '/'` to wdio.conf.
> Never used chromedriver service before, found out this yesterday and have to agree this is not obvious.
> 
> Alternatively can choose selenium standalone instead, but note that it requires jdk to be installed. I like it more because it work with multiple drivers out of the box, ex firefox, safari, chrome.

Maybe worth providing a table with versioning and dates? Especially on the get started page so that people/beginners will be able to identify a possible version mismatch immediately and use older versions if need be.

If your team integrate a regression test of some sort then you can provide an indicator with regards to that also. 

Just some ideas.

**Comment by mgrybyk** [comment]
We suppose that new comers are using latest version, so no versioning is needed.

Regarding regression testing, I think we are not doing that but automating as much as possible. 
I think no one here is being paid for doing framework, we are implementing things in spare time...

**Comment by erwinheitzman** [comment]
@mgrybyk I like to disagree and say that the documentation clearly states how it should be configured and what it falls back to when possible.
Reference: https://github.com/atti187/wdio-chromedriver-service#readme

KEEP IN MIND: this service is not created nor maintained by us, if we want to be more clear and upfront about things like this we should add a service that is maintained by us instead of the community.

**Comment by christian-bromann** [comment]
> we should add a service that is maintained by us instead of the community.

I disagree on that. We don't need to own a plugin just to make changes. We can propose PRs for that project like on any other project too.

**Comment by mgrybyk** [comment]
Anyway the problem is not with this service or any other. 
I'd like to make some changes to getting started so that there is no need to google for any additional documentation on the first steps

**Comment by mgrybyk** [comment]
https://github.com/webdriverio/webdriverio/pull/4014

**Comment by AzySir** [comment]
> @mgrybyk I like to disagree and say that the documentation clearly states how it should be configured and what it falls back to when possible.
> Reference: https://github.com/atti187/wdio-chromedriver-service#readme
> 
> KEEP IN MIND: this service is not created nor maintained by us, if we want to be more clear and upfront about things like this we should add a service that is maintained by us instead of the community.

If you're going to be expecting people to refer to the GitHub immediately then I suggest referencing it immediately also. 

@mgrybyk  Thanks for hearing out my feedback! Keep up the great work team!
