### ISSUE TITLE
browser.moveToObject() not scrolling the element into view

### ISSUE THREAD

**Issue by seemacalibrecode** [webdriverio/webdriverio#2776]
## The problem

I am running my WebdriverIO tests on Jenkins server which is Ubuntu and using Chromedriver 2.37.
## Environment

* WebdriverIO version:4.12.0
* Node.js version: 8.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable):

## Details

In my Application, I can add multiple rows of work history. The tick icon to save is on top of the table where we enter data. When the tests enter data, the page scrolls down automatically and the tick button is hidden in the top. So the click on the tick icon always fails with message that the element is not clickable. I tried using browser.scroll(0,-500). Also tried using browser.moveToObject'id')

## Link to Selenium/WebdriverIO logs

unknown error: Element <button id="submit-work-history" class="btn btn-box-tool btn-sm margin-right pull-right text-success check-save-btn" style="padding: 0px 5px; line-height: 1.3em; height: auto; font-size: 15px;">...</button> is not clickable at point (1116, 158). Other element would receive the click: <div id="user-top" class="affix">...</div>

## Code To Reproduce Issue [ Good To Have ]

```
    browser.moveToObject("button#submit-work-history");
    Chat.saveWorkHistory.waitForVisible();
    Chat.saveWorkHistory.click();```

**Comment by erwinheitzman** [comment]
Please make sure to always use the latest driver version that is supported by your browser version before creating these kind of issues.

chromedriver.chromium.org

**Comment by seemacalibrecode** [comment]
I am using wdio-selenium-standalone-service version 0.0.10, which is the latest version. https://github.com/webdriverio/wdio-selenium-standalone-service/releases

This automatically considers chrome driver version as 2.37

**Comment by christian-bromann** [comment]
@seemacalibrecode this is not something we can fix on the webdriverio side (even though we will try to implement an autofix into the webdriverio core with the next major version). Please try to click on an element somewhere close to that target element so that the browser scrolls up again. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and let me know if that works for you. Thanks!
