### ISSUE TITLE
`browser.getLocation`, `browser.getElementSize`, `browser.execute`is not working in IE 11.

### ISSUE THREAD

**Issue by ho-dieu-it** [webdriverio/webdriverio#2803]
## The problem
`browser.getLocation`, `browser.getElementSize`, `browser.execute` is not working in IE 11.

## Environment

* WebdriverIO version: 4.11.0
* Node.js version: 8.11
* Browser: IE 11
## Details

I would get element size and location and I use 2 functions (`browser.getLocation`, `browser.getElementSize`). But they did not work.
However, they work on Firefox and Chrome.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Since there are no logs I can look into I assume that something is up with the IEDriver maybe not supporting this commands. Definitely not an issue with WebdriverIO. Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions like that.
