### ISSUE TITLE
How to Force fail the test in afterTest hook in wdio.conf

### ISSUE THREAD

**Issue by breinjhel** [webdriverio/webdriverio#2843]
## The problem
I have a test where I check if an element is present and if it does I would fail the test. I added that checking in the afterTest hook in wdio.conf and no matter what assertion error I throw there It wouldnt fail the test. Is there a way to do that? It would save lots of time to just add test checking on hooks rather than copy pasting on all existing tests

**Comment by christian-bromann** [comment]
> s there a way to do that?

You need to add the check in your test, not in the hook. I guess it can be useful however to allow assertions in afterTest hooks. Feel free to provide a PR.

**Comment by mharrell** [comment]
@breinjhel 
Any updates on this? I'm in the exact same position and this functionality would be super helpful!

**Comment by kunwardeep** [comment]
I run a visual testing check in the afterTest hook. I want the test to fail if my visual comparison fails. It is counter-intuitive to add an additional function call to each test to run this test. I wanted to do this in the afterTest hook. Looks like it hasn't been implemented yet :(

**Comment by kunwardeep** [comment]
I believe this functionality is there in mocha itself as pointed here 
https://github.com/mochajs/mocha/wiki/HOW-TO:-Conditionally-fail-a-test-after-completion

**Comment by mgrybyk** [comment]
There is one more alternative to copy paste, maybe it can help, rough example:
```
const scenarios = [{
  name: 'test 1',
  data: { selector: 'body' },
  assertion () { /* do something */ },
}, /* other scenarios */ ]

scenarios.forEach(s => {
  it(`should ${s.name}`, () => {
    const el = $(s.data.selector)
    s.assertion()
  })
})
```

Following approach data -> action -> verification point.
It might help if you have an array of images, links, text fields or even more complex objects you want to do assertion against.

**Comment by mgrybyk** [comment]
closing this for now because it is possible to fail test in afterTest and afterHook hooks at least for mocha.

You can do something like this
```
afterTest (test, context, result) {
    context.test.callback(new Error('oh no'))
},
```

Or if you prefer to fail test from afterEach hook
```
afterHook (test, context, result) {
    context.test.error(new Error('oh snap'))
},
```

Anyway there is access to mocha context and it is possible to do everything that is allowed by test framework itself

**Comment by vgrigoruk** [comment]
I've tried to use the code from last answer and unfortunately it doesn't work as expected
a) with `afterTest` hook like this
```js
afterTest (test, context, result) {
    context.test.callback(new Error('oh no'))
},
```
I see the following in stdout:
```
[0-0] Error in "some test"
oh no
[0-0] Error in "some test"
done() called multiple times
``` 
Test is failed as expected, but I guess wdio test runner shouldn't call mocha's `done()` callback in this case.

b) `afterHook` wdio test runner hook is called only if you have hooks defined in your test spec file.
For example, `afterHook` hook won't be called for this test suite: 
```js
describe('foo', function(){
  it('works', function(){}); 
}
```

**Comment by johan** [comment]
I'm sadly in the same boat as @vgrigoruk – my app has a DOM element for error messages that I want to probe after the completion of each test, and fail said test with that error message, if present, but the best that seems possible to do today is to `console.log` it in `afterTest` with some findable marker in log output, as it will be buried in other log noise rather than end up in the final summary.

I guess we can call `context.test.callback` to produce the `done() called multiple times` error and learn to search for the marker when you get that error message. 😓
