### ISSUE TITLE
@wdio/logger not upgraded from v5.0.3 to v5.1.0

### ISSUE THREAD

**Issue by jlchereau** [webdriverio/webdriverio#3207]
Breaks statement that "_Going foward the version number of all packages are now pinned to each other; meaning that you should always have the same versions for all "official" WebdriverIO packages that you use_". Source: https://webdriver.io/blog/#new-package-structure

**Comment by christian-bromann** [comment]
Lerna doesn't update packages if there is no change in it. For example, if I change something in `@wdio/local-runner` a version bump would only happen in that package because it is not a dependency of any of the other packages. However if I would change something in `@wdio/logger` all packages would be updated because it is a dependency of all packages.
