### ISSUE TITLE
v5 Test Runner reports no specs found to run when no capabilities property set

### ISSUE THREAD

**Issue by naddison** [webdriverio/webdriverio#3289]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.11.2
 - **NPM version:** 5.8.0

**Describe the bug**
I used the configuration file that was generated for me using the WDIO CLI. I then commented out the capabilities section.

**Expected behavior**
I expected that an error telling me clearly I am missing a capabilities section, and will not run my tests. Instead I got the error message:

`2019-01-09T20:32:39.686Z ERROR wdio-cli:Launcher: No specs found to run, exiting with failure`

which makes me think the pattern in my specs property is wrong.

**Comment by ratbeard** [comment]
I also encountered this and was confused by it.

I was trying to get `chromeOptions` working, which I eventually found needs to be `goog:chromeOptions` in #3238.  Some old gists and posts related to java talked about using `desiredCapabilities` instead of `capabilities`, and I saw `desiredCapabilities` is a valid property in `Options` in the `webdriverio.d.ts` file, so I tried that.

**Comment by christian-bromann** [comment]
Let's continue convo in #3535
