### ISSUE TITLE
Simplify xPath selectors to enhance selector strategies

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#331]
xPath is sometimes confusing. WebdriverIO should help devs by simplifying that to provide extended selector strategies like:

- `ul li:nth-child(2)` => `/ul/li[position()=2]`
- `a=my text` => `//tag[normalize-space() = "my text"]`
- `a*=my text` => `//tag[contains(., "my text")]`
- `a.myclass=my text` => `//tag[contains(@class, "myclass") and normalize-space() = "my text"]`
- `a.myclass*=my text` => `//tag[contains(@class, "myclass") and contains(., "my text")]`
- `.someElem:not('.someOtherElem')`

Goal should be to enable most (not necessarily all) [Pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) and be able to combine them with other queries like containing text.

**Comment by christian-bromann** [comment]
will get shipped with `v2.5.0`

**Comment by christian-bromann** [comment]
There will be more like `input:not(:checked)` etc.

**Comment by inspiraller** [comment]
Thankyou for providing alternative solutions to xpath above for webdrive io. This has helped me worked with the selenium language. 

However, In response to the following statements:

_**xPath since it is way more cross browser compatible.**_ 
This statement is redundant and not the reason to favour xpath over css

Older browsers are declining, and it is expensive supporting them and building for them as much as building more future proof code. It is more sensible to write in a language that is easier, more cost effective, and more readable. Also it is easier and cheaper to recruit testers/developers who share a common language.

**If xPaths allows us to query really specific elements we can't get with simple css selectors, we shouldn't be afraid to us it.**

This statement implies that css is not enough and xpath provides for greater specific testing. 
1. CSS can do anything xpath can do, only it is easier to read when testing things like attributes
2. There has been a wrong attitude for many test writers, who write tests to the nth specifity and it limits the evolution of code changes by making it unnecessarily nested. It is more efficient, more flexible, more exact to be target only the necessary page component contents - ie .somecomponent .childItem rather than /div/div[@class=x]/span/div/etc...
Unfortunately not all the pseudo selectors work with the webdriver io at the moment and using something like jquery, which supports most of them if not all, and provides its own would be a much more sensible choice. The documentation is excellent and, despite the trend towards developing with frameworks, jquery still enjoys a massive following because of it's ease of use.

**Comment by sohailsomani** [comment]
I can confirm that I am using a ton of `execute("$(...).foo()")` in order to work around xpath + css limitations. It would be great if a "jQuery" mode was supported.
