### ISSUE TITLE
Create a flow chart describing how packages interact with each other

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3387]
Based on [this](https://github.com/webdriverio/webdriverio/pull/3381#discussion_r249968090) feedback it would be nice for developers to have some sort of flow chart describing how packages interact with each other. That would help onboard people quicker and allow them to make more in depth changes.

**Comment by jdavis61** [comment]
I would be interested in helping with this task. I will post what I have for a flowchart within the next seven days.

**Comment by christian-bromann** [comment]
I love this flow chart. Some things I've seen that could be changed:

- correct package names (e.g. @wdio-runner -> @wdio/runner and others)
- in `@wdio-runner index.js run()` we could add _"fetches logs from driver and writes reporter result files"_
- `@wdio/jasmine-framework` has no dependency to `@wdio/cli`
- you can leave out `@wdio/lambda-runner` for now until it becomes a "thing"

This is a great start and I would love to have a deeper technical documentation. What would you suggest?

**Comment by jdavis61** [comment]
> I love this flow chart. Some things I've seen that could be changed:
> 
> * correct package names (e.g. @wdio-runner -> @wdio/runner and others)
> * in `@wdio-runner index.js run()` we could add _"fetches logs from driver and writes reporter result files"_
> * `@wdio/jasmine-framework` has no dependency to `@wdio/cli`
> * you can leave out `@wdio/lambda-runner` for now until it becomes a "thing"
> 
> This is a great start and I would love to have a deeper technical documentation. What would you suggest?

I think describing how events are emitted and processed would increase the technical nature of any WebdriverIO flowcharts. For example the @wdio/cli flowchart would explain how the launcher.js message, error and exit listeners interact with the WebdriverIO ecosystem.

lines 296 - 312 launcher.js
```
        const worker = this.runner.run({
            cid,
            command: 'run',
            configFile: this.configFile,
            argv: this.argv,
            caps,
            specs,
            server,
            execArgv,
            retries
        })
        worker.on('message', ::this.interface.onMessage)
        worker.on('error', ::this.interface.onMessage)
        worker.on('exit', ::this.endHandler)

        this.interface.emit('job:start', { cid, caps, specs })
        this.runnerStarted++
```
I will create another @wdio/cli flowchart, this time that includes events and post here for review. 

Cheers!

**Comment by naddison** [comment]
@jdavis61 Are you still making these? If yes/no can I be of assistance? I am very interested in this effort.

**Comment by jdavis61** [comment]
@naddison i started trying to add events to the @wdio-cli flow chart but have not had any free time to finish. Go for it! ;)

**Comment by jdavis61** [comment]
Hello @naddison and @christian-bromann, I will post what I have for my @wdio/cli flowchart within a couple of days (should be done by Wednesday 6/12). 

I am thinking if we can create an accurate @wdio/cli flow-chart, explaining package interaction should be easy / easier. (Let's hope at least!).

**Comment by christian-bromann** [comment]
Thanks so much @jdavis61

**Comment by jdavis61** [comment]
Hello, see attached pdf's for what I have for flow charts. I am hoping they will help developers understand how all the packages interact with each other. I definitely learned a lot creating them.

[webdriverio-packages-high-level-overview.pdf](https://github.com/webdriverio/webdriverio/files/3274546/webdriverio-packages-high-level-overview.pdf) - Very very high level overview of how the packages interact with each other.
[1-wdio-cli-run.pdf](https://github.com/webdriverio/webdriverio/files/3274537/1-wdio-cli-run.pdf)- High level flow chart describing @wdio/cli index.js and run.js.
[2-wdio-cli-launcher.pdf](https://github.com/webdriverio/webdriverio/files/3274541/2-wdio-cli-launcher.pdf) - Describes launcher process and the interaction between @wdio/local-runner and @wdio/runner.
[3-wdio-runner.pdf](https://github.com/webdriverio/webdriverio/files/3274544/3-wdio-runner.pdf) - Provides a very high level overview of what happens when @wdio/runner index.js is executed. @wdio/runner index.js is extemely important. I look forward to understanding the process in this package a lot better.

Please review and provide feedback.

**Comment by jdavis61** [comment]
I am going to start working on the flow charts again within the next couple of days. I would like to try and consolidate what I have to one flow chart. WebdriverIO definitely has a lot of moving parts! :)

For the month of September I will spend a few hours a week trying to figure this framework out. Hopefully the 3 week break will make things easier.

Cheers!

**Comment by jdavis61** [comment]
@UnityOfFairfax, @naddison  and @christian-bromann, I combined the original 3 flow charts into one. This version is more technical than the first version, hopefully less verbose than the second.

See [wdio-high-level-overview.pdf](https://github.com/webdriverio/webdriverio/files/3638139/wdio-high-level-overview.pdf) for the new version.

Also I believe [webdriverio-package-high-level-overview.pdf](https://github.com/webdriverio/webdriverio/files/3638140/webdriverio-package-high-level-overview.pdf) is still valid and/or not so incorrect that corrections may be added easily.

**Comment by jdavis61** [comment]
Hi @christian-bromann, 

I am thinking the flow chart(s) could be displayed on the website in a folder named flowcharts and accessed via a url like http://localhost:3000/docs/flowchart/flowchart.html. 

The below image is an example of what the flow chart page would/could look like. Or do you think one page is good enough? I personally feel it would be difficult to create one flow chart for the entire system, maybe have 2-4 or 2+ pages?

![possibleFlowchartPage](https://user-images.githubusercontent.com/16749810/66257623-993ced00-e769-11e9-98e0-b9a53afe0d39.png)

Miscellaneous notes regarding any potential flow chart page:
- The flow charts will be displayed on the page as an image because docusaurus does not allow inline pdf's (that I know of). These images would be stored the `website/static/img/flowcharts` folder.
- The flow chart pdf's should be stored in a folder named `website/static/pdf/flowcharts` . A download flowchart link will appear on each page and link to these pdf's.
- PDF is a format that is supported by most flow chart software, e.g. LucidChart / Visio, we should not save the charts using a propertitary format, e.g. Vizio. 
- To update any flow chart, the pdf will be loaded in the flow-chart software, updates made. After the updates are complete the file is saved as a pdf then re-uploaded to the website. 
- Any flowchart should have a maximum width of 750 or 800 px to ensure the image is displayed correctly on the website. Maybe a smaller width as well?
- Try to minimize whitespace in the flowchart, use the space as efficiently as possible.

**Comment by christian-bromann** [comment]
Let's continue convo in #4579

**Comment by jdavis61** [comment]
Hello I am still working on this ticket, unfortunately the task is a lot harder than I originally thought. 

To create the flow charts, I am stepping through the code using the VSCode debugger then making notes for the most important functions. I am posting my VSCode debugger setup because I feel **stepping through the code** is the easiest way to **grok** the system. 

**Setting up debugger with VSCode**
1. Add `--inspect-brk` to  ./node_modules/.bin/wdio.cmd (or wdio for linux). 
2. Add the below configuration to your local VSCode launch.js. 

**wdio.cmd**
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\@wdio\cli\bin\wdio.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node --inspect-brk  "%~dp0\..\@wdio\cli\bin\wdio.js" %*
)
```

**launch.js**
```
{
    "version": "0.2.0",
    "configurations": [
        {
           "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "port": 9229,
            "name": "WebdriverIO",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio.cmd"
            },
            "timeout": 100000000,
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "args":[
                "--mochaOpts.timeout=99999999",
                "--spec", "${workspaceRoot}/<path to test>",
                "${workspaceRoot}/wdio.conf.js"
            ],
        }
    ]
}
```

Adding note to ticket as an FYI for anyone that has or will view this ticket in the future. As mentioned before IMO **stepping through the code** is the easiest/best way to **grok** the WebdriverIO system. 

I hope this message helps anyone struggling to learn the WebdriverIO. Awesome work WebdriverIO team,

PR# [4747](https://github.com/webdriverio/webdriverio/pull/4747) is the latest PR for this issue.

**Comment by christian-bromann** [comment]
This is very helpful! Let's put it into the docs.

> Hello I am still working on this ticket

We really appreciate your work on this!

**Comment by jdavis61** [comment]
Latest PR = https://github.com/webdriverio/webdriverio/pull/4873
