### ISSUE TITLE
multiply tabs are not switching and closing wrong one

### ISSUE THREAD

**Issue by fat-troll** [webdriverio/webdriverio#350]
Hello!
I have a page with 4 links, which I'm opening one by one. The links are really heavy and it takes a lot of time to load them fully. After opening links I look for there ids 

.getTabIds(function(err,response){ gtabIDs=response; console.log(gtabIDs);}) 

and try to switch to another tab

.switchTab(gtabIDs[1])

but it's impossible to switch to them, i'm always on my current tab, I checked with something like (is it dependant on a tab is loaded or not?)

.getCurrentTabId(function(err,response){console.log(response);})

The other problem is I can't close tab with .close(gtabIDs[1]) , because the only closing tab is current one

So the questions are:
1) Am I switching tabs wrong?
2) Am I closing tabs in a wrong way?

PS I'm using mocha & chrome

**Comment by christian-bromann** [comment]
Haha. I now see the problem, make that mistake also every time. `switchTab` doesn't work because the variable `tabs[1]` is undefined in that moment you call that command. The variable `tabs` gets changed in the callback that gets executed after WebdriverIO put `switchTab` in its command queue. That's the burden of asynchronicity ;-)
