### ISSUE TITLE
Rename logger names to represent NPM package name

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3616]
Currently all logger names are based on the internal naming structure (e.g. `wdio-sauce-service`). Since these logs are user facing logs they should actually named like the NPM package name. Therefor we should rename all loggers to reflect the NPM package name.

**Comment by mgrybyk** [comment]
also, lets make sure that each package uses its own logger instead of reusing logger of another package.

Example: allure reporter should have its own logger instead of reusing runner reporter

**Comment by baruchvlz** [comment]
@mgrybyk I'm guessing this should be taken care of in a different PR instead of the same one that changes the names for the loggers? (I don't want to bite off more than I can chew)

@christian-bromann Question. Some loggers, like the cli, use `wdio-cli:run`, should this be renamed to `@wdio/cli:run` or `@wdio/cli` ?

**Comment by christian-bromann** [comment]
> Question. Some loggers, like the cli, use `wdio-cli:run`, should this be renamed to `@wdio/cli:run` or `@wdio/cli` ?

@baruchvlz I think we should keep the pattern that is `<package-name>:<sub-component-of-package>` so `@wdio/cli:run`

**Comment by mgrybyk** [comment]
@christian-bromann can this one be closed?

**Comment by christian-bromann** [comment]
Yes
