### ISSUE TITLE
Use Reacts Virtual DOM to select elements in React apps

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3721]
**Is your feature request related to a problem? Please describe.**
If you want to test React applications that have generated class names and ids then it is really hard to select elements on the page.

**Describe the solution you'd like**
We should enhance the selector mechanism to support the virtual DOM of react applications so user can select by prop name or maybe even state of an react element.

**Describe alternatives you've considered**
We could check out how Testcafe has implemented this: https://github.com/DevExpress/testcafe-react-selectors

**Comment by emilyrohrbough** [comment]
This is a neat idea! I would be curious if this implementation would be possible when the react components are using css-custom properties to have locally-scoped class names. They  mention on limitation with minified assets that remove the original class name.

**Comment by baruchvlz** [comment]
> I would be curious if this implementation would be possible when the react components are using css-custom properties to have locally-scoped class names

@emilyrohrbough You mean like styled components? Or?

So far, I've been able to find the class names 2 ways

I did this with a `create-react-app` component:

1. Use the `type` property with the component's props. The only downfall I've found for this is when using functional components that use hooks. I get a React error saying that hooks can only be used inside components.

```javascript
const root = document.querySelector('#root');
const App = root._reactRootContainer._internalRoot.current.child;

const appType = App.type(App.memoizedProps);
/*
outputs:
{  
   "type":"div",
   "key":null,
   "ref":null,
   "props":{  
      "className":"App",
      "children":{  
         "type":"p",
         "key":null,
         "ref":null,
         "props":{  
            "children":"My App"
         },
         "_owner":null,
         "_store":{  

         }
      }
   },
   "_owner":null,
   "_store":{  

   }
}
*/
console.log(appType.props.className) // App
```

2. Recursively iterating through the components `child` property, looking for `stateNode` property and inside there we can find `className`.

![image](https://user-images.githubusercontent.com/14321495/54291254-964f9480-45ac-11e9-909d-a7a3a0ecc908.png)


The latter works fine with functional components.

**Comment by baruchvlz** [comment]
>  I would be curious if this implementation would be possible when the react components are using css-custom properties to have locally-scoped class names.

@emilyrohrbough You mean like styled components? Or?

**Comment by emilyrohrbough** [comment]
yes styled components that use css modules to locally scope class naming: https://github.com/css-modules/css-modules

**Comment by baruchvlz** [comment]
@emilyrohrbough  This wouldn't affect the idea of selecting React components based on the component name. Like you said, those libraries affect classNames and this is why we have to think of a different way of selecting React components. When you define a component in react, either functional or class, the library will add a property `type` to the element's VirtualDOM with a reference to the function or class. For example:

```javascript
import React from 'react';

const WorldComponent = () => (<div>World</div>);

export default WorldComponent;
```
In the VirtualDOM, the object looks something like:

<img width="826" alt="Screenshot 2019-03-15 at 16 51 46" src="https://user-images.githubusercontent.com/14321495/54444270-b1eca380-4742-11e9-90da-8e0ac817fbfc.png">

We will use `componentInstance.type.name` to match the selector. The only downfall to this is that it won't work with anonymous components, but we shouldn't worry about this because 1) it's bad React practice to have anonymous components (example: `export default class extends React.Component {}`) and 2) even React Dev Tools has issues managing anonymous components.

Now, we can use the selector function like so:

```javascript
react$('WorldComponent')
/*
outputs: 
{
  node: HTMLElement,
  props: Object,
  state: Object,
  selector: string
}
*/

// for query all

react$$('WorldComponent')
/*
outputs: 
[
  {
    node: HTMLElement,
    props: Object,
    state: Object,
    selector: string
  }
]
*/
```


Eventually the API will allow you to do:

```javascript
react$('WorldComponent')
  .byProps({ myProps: true })
  .byState({ someState: false })

// or

react$$('WorldComponent')
  .byProps({ myProps: true })
  .byState({ someState: false })
```
And this will filter out any component instance that doesn't match the props and state arguments.

I think it's also a good idea to note that I had a talk with @christian-bromann about this yesterday and we came to the conclusion that it's best to support React v16 +.

---

Somewhat of a todo list (so far):

- [x] add `react$` 
- [x] add `react$$`
- [ ] nested selectors (i.e. `react$('WorldComponent div div')`)
- [ ] filter by props
- [ ] filter by state

I'm hoping to have all 5 items done by next week.

**Comment by aluedeke** [comment]
@baruchvlz i guess the waitForReact method from TestCafe would be super useful as well. Not a selector, but not being able to do synchronise on this causes random test failures in my selenium tests.

**Comment by christian-bromann** [comment]
I would propose to create new selector commands similar we have for shadow DOM, e.g.

```js
const reactComponent = react$('MyComponent', { byProps: { foo: 'bar' }})
// would do `await resq$('MyComponent').byProps({ foo: 'bar' })`
```

**Comment by CrispusDH** [comment]
> @baruchvlz i guess the waitForReact method from TestCafe would be super useful as well. Not a selector, but not being able to do synchronise on this causes random test failures in my selenium tests.

I don't like this idea. In my opinion you should wait an element instead of waiting framework ready state. Users will not wait before some requests were finished or components will get some states, etc. I think we have to simulate user as much as we can, so for example "click" action should be done when element is clickable instead of adding some additional React waiter before clickable check.

**Comment by baruchvlz** [comment]
@CrispusDH The idea is to utilize the virtual dom to query for react components by their name. This is not possible unless React has rendered into the HTML node via `ReactDOM.render`, this function will attach the virtual dom to the given element and then the library gives the virtual dom instance for the root of the application [here](https://github.com/baruchvlz/resq/blob/master/src/waitToLoadReact.js#L23)

> I think we have to simulate user as much as we can, so for example "click" action should be done when element is clickable instead of adding some additional React waiter before clickable check.

If you have a button inside a React component, this button won't be clickable (or visible) until React loads anyway. Like I said, we check if React is loaded only once.

**Comment by baruchvlz** [comment]
@aluedeke Sorry I had missed your comment. This is something that I thought about while building the library and right now it's a concern. The only reason we use `try/catch` is to wait for the App to load, everything else in the library is synchronous. With this said, I've thought about exposing the `waitToLoadReact` function which can be used inside the `beforeAll` hook like so:

**Comment by baruchvlz** [comment]
@aluedeke Sorry I had missed your comment. This is something that I thought about while building the library and right now it's a concern. The only reason we use `try/catch` is to wait for the App to load, everything else in the library is synchronous. With this said, I've thought about exposing the `waitToLoadReact` function which can be used inside the `beforeEach` hook like so:

```javascript
import { waitToLoadReact } from 'resq'

beforeEach(async () => {
    try {
        await waitToLoadReact(2000)
    } catch (error) {}
})
```

What @christian-bromann suggested by mimicing the shadow DOM API is also possible. And another idea would be to wait for react to load synchronously and not have to expose any promises.

The latter is what I'm aiming for as it will reduce the size of the library as well.

The first item in the `optional` list on this issue https://github.com/baruchvlz/resq/issues/11 refers to something similar to what being discussed. I would suggest keeping this conversation in that issue or making a new one in that repository so we can keep things related to this separate from WDIO and it's later implementation of the library.

**Comment by christian-bromann** [comment]
This has been merged and will be released with the next version.
