### ISSUE TITLE
Make webdriverio fibers aware in standalone mode

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#3734]
**Is your feature request related to a problem? Please describe.**
I want to be able to run webdriverio synchronously in standalone mode.

**Describe the solution you'd like**
If you create a `remote` or `multiremote` within a fiber context, webdriverio should automatically detect the fiber context (`Fiber.current` is set) and rather then returning a promise, make the fiber wait and return the resulting value synchronously.

**Describe alternatives you've considered**
I wrote a wrapper around webdriverio that makes it fibers aware. If there is no current fiber it returns a promise and otherwise it is using the fiber. However, I don't see why webdriverio shouldn't support this internally. If `@wdio/sync` is installed and `Fiber.current` is set, I think it is safe to assume that the user wants to run wdio synchronously. If not, we could always put an option in the configuration to disable (or enable) this behaviour.

**Additional context**
When using the test runner with `@wdio/sync`, webdriverio is already fibers aware. When executing a command outside of the fibers context, it defaults back to returning the promise. I've seen this with `deleteSession` for instance. I don't see why wdio couldn't always be fibers aware, even in standalone mode. It shouldn't be too much effort to change this.

**Comment by christian-bromann** [comment]
> It shouldn't be too much effort to change this.

Well there is a little bit more work and complexity around this as you think. You have to also wrap all exposed client commands so that they run with Fibers. Also you need to make sure that all internal commands (see webdriverio commands) are continue to return a promise. If you can provide a patch that would allow people to to the following:

```js
import { wrap } from '@wdio/sync'

wrap(() => {
    const client = remote(...)
    client.url('...')
    // ...
}).then(...)
```

I would be happy to merge it. With that being said, there a lot of other things I am more interested in getting implemented than that. So feel free to tackle this.

**Comment by mgrybyk** [comment]
@christian-bromann haven't you fixed this one?

**Comment by christian-bromann** [comment]
Yes, docs to this can be found here: https://webdriver.io/docs/setuptypes.html#standalone-mode
