### ISSUE TITLE
How can we see the failed/passed test cases in console with Webdriver V5

### ISSUE THREAD

**Issue by aish-blr** [webdriverio/webdriverio#3848]
I am using Mocha framework
With Webdriver V4, after executing a script, suppose within a describe block, I have two it statements like this
it('User is taken to Landing page after a successful login', function () {

})
it('I should be able to create a component ', function () {

})
In V4, after executing the test, say for example i might see 
1 passed - User is taken to Landing page after a successful login
1failed - I should be able to create a component 

After moving to V5, I do not see this.
Changing the log level to error/debug/trace in wdio.conf.js also does not help.

Can you please tell how I can get this type of logging enabled in V5

**Comment by christian-bromann** [comment]
I am not sure what kind of logging you are talking about but you need to have reporter set up in order to see any result.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by aish-blr** [comment]
Thanks @christian-bromann. I chose to raise a "Question" instead of bug since this was a query.
Can i continue to raise "Questions" in this channel if they would not be counted as defects. I am seeing resolutions here quite faster than Gitter.

**Comment by christian-bromann** [comment]
Please raise questions in Gitter first as there are more people that can immediately help you out. Thanks!
