### ISSUE TITLE
error on setValue ?

### ISSUE THREAD

**Issue by pronebel** [webdriverio/webdriverio#386]
when the input is readyonly, there is an error:

As below:

---------------------------------------
 Uncaught RuntimeError
     (InvalidElementState:12) An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element).
     Problem: invalid element state: Element must be user-editable in order to clear it.

     Callstack:
     -> elementIdClear("4")
     -> setValue("#J_planEndDate","2015-01-13")

----------------------------------

But the input is readonly,not disabled.when an input is readonly, it need to be setted value.
in my project ,it's a time control, The input is readonly,but it can be setted by the date-widget-control.

sorry ,my english is not good. i hope you understand what I say.

thanks.

**Comment by fat-troll** [comment]
Selenium behaves in most cases like a simple user and setValue() is like user, tries to input something in an editable field. So, a simple user can't just edit that field, because it's readonly. The most possible solution for you is to use js for fitting the element or to interact with js calendar (if it's possible in your case). By the way, I don't see code from your first example.

**Comment by christian-bromann** [comment]
@fat-troll great explanation!

@pronebel if you want to brute force that, you can do it via `[execute](http://webdriver.io/api/protocol/execute.html)` which executes javascript on the page. Try this:

```js
client.execute(function() {
     document.querySelector('#J_planEndDate').value = "2015-01-13";
}, null);
```

P.S. the `null` at the end is usually not necessary but since 2.4.0 there seems to be a problem with that. I am on it to fix this.

**Comment by kevinmcdonnell** [comment]
Is there a way to wait for an input to be user-editable?

**Comment by christian-bromann** [comment]
sure, with waitUntil, just check if it fulfills the condition of being user editable

**Comment by campside** [comment]
Interesting... 
`browser.addCommand('loginEmail', function(email, password) {

    this.moveToObject('.profile-link');

    this.waitForVisible(menu.loginButtonClass);

    this.click(menu.loginButtonClass);

    this.waitForVisible(modal.modalClass);

    this.setValue(modal.authModalEmailInput, email);

    this.click('button.auth-block__form-button');

    this.waitForVisible(modal.authModalEmailPasswordInput);

    this.click(modal.authModalEmailPasswordInput);

    this.setValue(modal.authModalEmailPasswordInput, password);

    this.click('button.auth-password-block__form-button');
});`

I'm ALWAYS get this error on the second setValue, if I replace it with .click + .keys it works...
