### ISSUE TITLE
Watch command doesn't close the sessions properly

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3919]
If I run the `--watch` mode and I ctrl+c to end the sessions, it doesn't properly end them.

**Comment by mgrybyk** [comment]
@christian-bromann what if we just remove this condition?
https://github.com/webdriverio/webdriverio/blob/bbe8f8e47f86a18c533462f8f5b5173f7fa9f36f/packages/wdio-runner/src/index.js#L137

For me it makes no sense to open empty browser tab instead of closing session in watch mode. 
Situation gets even worse if there are multiple tests to watch as far as all the browsers instances are hanging.

We can just end session for all modes.

**Comment by christian-bromann** [comment]
The advantage of watch mode is that we not close the session so rerunning something will be super fast. The problem I am outlining here is that there are issues closing the session when someone exists the watch mode again.

**Comment by mgrybyk** [comment]
Got it. Do you mind opening blank page before spec instead of after?

It looks really useful for me because I can debug something, look for selectors, etc on my site.

**Comment by christian-bromann** [comment]
> Got it. Do you mind opening blank page before spec instead of after?

Sounds like a good idea!

**Comment by mgrybyk** [comment]
hey, can we merge https://github.com/webdriverio/webdriverio/pull/3958 before fixing this to reduce conflicts amount?

**Comment by mgrybyk** [comment]
Found a way how to make it work for single instance as well as for multiremote, last one is especially painful because it is required to attach to every browser session in order to kill it.

Maybe it would be a good idea to do some refactoring one day to make framework work as Multiremote by default, but that's another topic.

Going to create branch based on #3958 for now
