### ISSUE TITLE
Promise chain error

### ISSUE THREAD

**Issue by syzer** [webdriverio/webdriverio#402]
Promise chain error:
```js
client
            .url(sid.url)
            .then(client.waitFor('.result', 5000))
            .then(client.getValue('#SSID'))
            .then(function(sid){
                 console.log('resolved', sid);  // here gets resolved ass [].length =4
                 return sid;                          // should be a SINGLE element     
             })
```
i guess in this last promise if the would be 
10 calls to webdriverio
the resolved promise would have array of 10 elements.

right now i workaround this by flattening an array.

```js
respSid = _.isArray(respSid) ? _.first(respSid) : respSid;
```

help is very much appreciated

**Comment by syzer** [comment]
Is is possible this lib would pass Promise\A+ spec in foreseeable future?
https://github.com/promises-aplus/promises-tests

**Comment by christian-bromann** [comment]
@syzer thanks for pointing out that compliance test suite. This will be a good addition to the existing tests. In general WebdriverIO is more a chained callback based library. So the idea is that your selenium tests should look like this:

```js
it('test something', function(done) {
    client
        .command()
        .command()
        .getAttribute('selector', 'attribute', function(err, value) {
             assert(err, undefined);
             assert(value, 'something');
         })
         .call(done);
});
```

Because this is a little bit verbose I implemented a promised like behavior just for the sake of using promised based assertion libraries, so we are able to do:

```js
it('test something', function(done) {
    client
        .command()
        .command()
        .getAttribute('selector', 'attribute').should.eventually.become('something')
        .call(done);
});
```

I am looking forward to improve the promise handler so we can do more sophisticated promise workflows.

**Comment by syzer** [comment]
Yeah, 
but as i mentioned WebdriverIo could be so much more.
Monadic/promise based behaviors is mostly for compose ability
fact that the code looks nicer is just byproduct.

now:

```js
// only client
client
        .command()
        .command()
        .getAttribute('selector', 'attribute').should.eventually.become('something')
        .call(done);
```

into this

```js
client
        .command()
        .command()
        .then(OtherLib.doPredictionAnalytics)
        .then(mathLib.calcBestUrl)  //=> url  / returns url
        // now back in webdriverio!!!!!
         .then(url=>{
               return client.url(url);
         })
        .getAttribute('selector', 'attribute').should.eventually.become('something')
         // this cathes from webdriverIo AND OtherLib AND mathLib
         .catch(function(err){
                fail(done);
          })
        .call(done);
```

**Comment by syzer** [comment]
Do you need a help with this one?
I kinda need this for my day job :)

Tho `q` was one of first opensource alternative to `async`
`q` was/is? not valid Promise/A+ / monad
`Bluebird`, or `when` I think they are.

Was trying to use bluebird promisify function, q( has denodefy or sth)
To use with WDIO
But 
1. u/we have Async? in exported function names
2. some of WDIO function don't resolve to 
   cb(err, value)
3. i look into WDIO internals.. and `async` lib is kinda old shool... like 2010/2011?

how u abbreviate Webdriver.io? WDIO?

**Comment by christian-bromann** [comment]
> how u abbreviate Webdriver.io? WDIO?

wdio is a nice abbreviation

Any help is always appreciated! 

> 1. u/we have Async? in exported function names
What do you mean by that?

> 2. some of WDIO function don't resolve to cb(err, value)
Currently all protocol commands (see `lib/protocol`) return with cb(err, res). WebdriverIO is using these protocol commands to build useful "action" commands. E.g. the `click` combines `element` + `elementIdClick` to click on something. All those commands (see `lib/commands`) return like cb(err, result, responses) whereby result is the sanitised command end result and responses are all responses we got from the selenium server to get that result.

> 3. i look into WDIO internals.. and async lib is kinda old shool... like 2010/2011?
You might be right but it does what it has to do right and thats all what matters imho. Any other lib in mind?

**Comment by syzer** [comment]
ad1.
TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
ad2. does click return cb(err, response) ?
ad.3 promise/q gives same thing as async + more.

**Comment by maxbrunsfeld** [comment]
I'm getting bitten by this too. I really like this library's chaining-based API, but there is a *very* confusing bug in the current behavior of the `.then` method:

Example code:

```js
// Suppose there are two windows.
client
  .windowHandles()
  .then(function(result) {
    return result.value;
  })
  .then(function(windowHandles) {
    console.log(windowHandles);
  });
```

Expected output: an `Array` containing both window handles:

```
["CDwindow-E7129659-BD49-4EE8-999B-3B7004C4CE78", "CDwindow-E7129659-BD49-4EE8-999B-3B7004C4CE79"]
```

Actual output: a `String` - just the first window handle:
```
CDwindow-E7129659-BD49-4EE8-999B-3B7004C4CE78
```

**Comment by syzer** [comment]
This is quite easy bug, just do _.first(output)
But question remains.. is there enough ppl/willpower to rewrite some stuff to pass A+ promises?

**Comment by syzer** [comment]
Also throw Error()
.catch() would be nice

**Comment by christian-bromann** [comment]
@maxbrunsfeld Interesting.. haven't tested that use case. It works if you return a promise though. Will fix that.

@syzer the basic idea behind WebdriverIO promises is that something like this is possible:

```js
client.getTagName('#elem').should.become('div');
```

Since WebdriverIO is based on ChainIt (callback based chaining) it is not quite straightforward to put promises on top of that and sometimes a little bit hacky. There is definitely room for improvements. I would like to keep ChainIt and the way how WebdriverIO queues commands.

> .catch() would be nice
Should be supported, see [here](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/PromiseHandler.js#L126)

**Comment by maxbrunsfeld** [comment]
> This is quite easy bug, just do _.first(windowHandles).

This doesn't help because I need all of them.

**Comment by syzer** [comment]
@christian-bromann i do get it u would like to keep as much as possible intact :)

Tho using callback to control 30 clients is a nightmare!.
I switched to java for that :(
Not happy about that....
 
100% agree that putting promises can be hacky.
But if all exported methods uses same node-like callback style you can promisify all methods.

So question is.. shall we spend manpower on pushing to full/good promise/composable behaviour?

**Comment by syzer** [comment]
@maxbrunsfeld  you can overwrite  the wd.io method to return _.first()
just make a decorator on top of wd.io, and/or send us patch :-)

**Comment by maxbrunsfeld** [comment]
I don't `_.first`. I want the array.

**Comment by syzer** [comment]
return [ _.first(response) ]   ?

**Comment by maxbrunsfeld** [comment]
I want every element of `response` (e.g. the second, the third, the fourth). `_.first` would not be helpful to me in any way.

**Comment by syzer** [comment]
ok i get it: 
.windowHandles()
returns  []
is that correct?
the methods of wd.io i use, returns SINGLE element,
so i can q.all them

**Comment by christian-bromann** [comment]
> But if all exported methods uses same node-like callback style you can promisify all methods.

They do: callback(error, result) is the scheme for all commands

> So question is.. shall we spend manpower on pushing to full/good promise/composable behaviour?

Definitely yes!

> Tho using callback to control 30 clients is a nightmare!.

WebdriverIO has unfortunately not a good support to run tests in parallel. Next step in my imaginary roadmap is an cli tool alá protractor. Some issue are already proposing functionality. Feel free to drop ideas

**Comment by syzer** [comment]
promises is my first 20 ideas...
that allows execution code in prallel and sequentionaly, or any other humanly visionable way

27 of this month we have a hackaton... we could hack thru wb.io
tho a lot of changes would be required.... 
ex: q=> some lib that is A+promise spec(like when, or bluebird)
would you be interested?

also we would need a suit of failing promise-based tests.

**Comment by christian-bromann** [comment]
> also we would need a suit of failing promise-based tests.

I tried to embed https://github.com/promises-aplus/promises-tests for the sake of promise testing. Got it working though it was pretty hacky.

> we could hack thru wb.io

sounds awesome

> q=> some lib that is A+promise spec(like when, or bluebird)

According to https://promisesaplus.com/implementations Q is a conformant promise A+ implementation

**Comment by syzer** [comment]
ad.Q: ok maybe is now.. it was not the case year or two ago.
also Q was performing quite poorly in terms of performance in VERY poorly in terms of RAM usage, is it passable now?
also the thow Error was not passed to .catch()
and also it required calling 
.done()
to make sure catch was invoked properly

ok i will PM and try to get your skype and if we find 1 or 2 more guys we will go thru A+ promises.

**Comment by christian-bromann** [comment]
> also Q was performing quite poorly in terms of performance in VERY poorly in terms of RAM usage, is it passable now?

mhm .. haven't found any statistics that compare Q > v1.0

> try to get your skype

I send a request

> if we find 1 or 2 more guys we will go thru A+ promises

Sounds awesome!!

**Comment by Robinfr** [comment]
More problems with promises:

	client
		.waitForExist('.certain-thing', 1000)
		.then(function(exists){
			if(exists){
				return driver
					.waitForExist('.certain-other-thing, 5000)
			}
		})
		.click('.another-thing')

It calls .click straight away instead of waiting for the inside promise to finish. Note: it DOES work when you put another .then in between click and the then call. Even if that other .then only contains a console.log.

**Comment by syzer** [comment]
yes,
also catch is not handled properly
who wants to rewrite PromiseHandler?

**Comment by christian-bromann** [comment]
I already made some progress and fixed problems like this. I am currently working on a complete different solution and will share my result soon

**Comment by syzer** [comment]
Remember you can always come to Basel for hackergarden and we could refactor together.

**Comment by Robinfr** [comment]
@maxbrunsfeld I've found the problem (since I was having the same issue where only the first element was returned). The problem is on line 60 in the PromiseHandler. Since it doesn't make an array out of it when it's already an array. Now this is nice for webdriverio, however, this breaks normal promises that return an array..

```
!(result.value instanceof Array)
```

should be removed. However, then we also have to fix the rest of the library to return proper promises.

**Comment by Robinfr** [comment]
The chaining of promises is biting me in the ass so hard.. I'm really considering to switch to the normal selenium-webdriver since there is not enough work being done to fix these kinds of critical issues.

There is no way to properly build something more complex then a simple .click().getAttribute() and test the attribute. If I want to get the attribute of something and then do a dynamic action based on that, it becomes extremely complex since the promises don't work properly at all..

**Comment by christian-bromann** [comment]
@Robinfr 

Could you give me an example of one of your complex tests?
Please bear with me, I currently rewrite the whole core to make everything monadic. I don't want to waste time on improving the current solution because this would never work out in the end.

**Comment by Robinfr** [comment]
@christian-bromann That's fine, but please give more updates on this so we can also track the progress.

As for a more complex scenario:

```js
var specialModel = {
1: 'foo'
2: 'bar'
};

driver
	.getAttribute('.draggable-object', 'data-special')
	.then(function(specialId){
		return driver
				.dragAndDrop('.draggable-object[data-special="' + specialId + '"]', '.droppable-object[data-special2="' + specialModel[specialId] + "]');
	})
	.continueWithWhatever();
```

This is a real case that I'm having at the moment, I retrieve a property and match it with an object to find a different DOM element and drag one to the other. However, at this moment, it won't wait until the dragAndDrop is finished, it will simply continueWithWhatever() straight away. Normally when you return a promise from within a promise, the next promise won't execute until the returned promise has been completed.

**Comment by christian-bromann** [comment]
I know it's ugly but in these cases please make use of callbacks:

```js
driver
	.getAttribute('.draggable-object', 'data-special', function(err, specialId){
             driver.dragAndDrop('.draggable-object[data-special="' + specialId + '"]', '.droppable-object[data-special2="' + specialModel[specialId] + "]');
	})
	.continueWithWhatever();
```

**Comment by Robinfr** [comment]
@christian-bromann yes that does seem to work. But it's not clear for me at all why this works, since some functions seem to be asynchronous and other (I'm guessing here) dragAndDrop are not? Any idea on when this new version will be finished? Because I'm really looking forward to that.

**Comment by christian-bromann** [comment]
> some functions seem to be asynchronous and other [...] are not
All commands are async http calls. WebdriverIO is based on [ChainIt](https://github.com/vvo/chainit) which takes care of the execution flow. If you execute a command it will put the request into a queue and executes it once all previous commands are done. It also allows nested calls like the example above. It's almost like execution code sequentially like in Java ;-)

> Any idea on when this new version will be finished?
Honestly no! I made some progress over the last couple of days. The new monadic structure is awesome. It returns a new webdriverio object after each call. That means that you can do something like this in the future:

```js
function MyPageObject(path) {
    this.header = client.element('header')
    this.loginButton = client.element('#login');

    this.login = function() {
        client.click(this.loginButton).setInput(...)
    }

    // ...
}
```

The Problem with the current solution is that promises get overwritten each time you call a new command because we are working on the same object over the whole session. Even if I would fix the issues on the PromiseHandler we would never be able to assign promises to an variable like in the example above.

**Comment by Robinfr** [comment]
> WebdriverIO is based on ChainIt which takes care of the execution flow. If you execute a command it will put the request into a queue and executes it once all previous commands are done.

See this would've been very handy to have documented and clearly visible because it changes the way you build the tests completely. Since reading this it's been much easier to work around the problems I was having.

> Honestly I don't know! I made some progress over the last couple of days. The new monadic structure is awesome. It returns a new webdriverio object after each call.

This sounds awesome, but it does look a lot like how the selenium-webdriver is doing it. What are the advantages in your way of doing things?

> The Problem with the current solution is that promises get overwritten each time you call a new command because we are working on the same object over the whole session. Even if I would fix the issues on the PromiseHandler we would never be able to assign promises to an variable like in the example above.

Honestly, your monadic way looks very cool, but promises are amazing as well (when they work properly). You don't usually assign promises to a variable like that, so I'm not sure that would be a problem. With promises you simply chain all the actions you want, using intermediate steps when necessary (using a .then statement for example).

All in all I'm looking forward to your progress, would be nice to be able to help you out on this. Do you have any plans on open sourcing this during development? Or will you wait until it's finished?

**Comment by syzer** [comment]
I looked to that and was manually patching some parts of PromiseHandler.. but the metaprograming that is used is quite hardcore. I'm wiling to help. Anyone wants to team up and fix it for good?

**Comment by christian-bromann** [comment]
@syzer @Robinfr please check out my [v3 branch](https://github.com/webdriverio/webdriverio/tree/v3). I've completely replaced the core in favour of a [monadic based](https://github.com/webdriverio/webdriverio/blob/v3/lib/webdriverio.js) object structure. I got rid of chainIt and the good old PromiseHandler as well as callbacks. `v3` will not support callbacks anymore. If you are interested in the response, call `then`.

My next steps are rewriting all commands to return a promise instead of calling the callback function. I can need as much help as possible. Would you guys help me?

**Comment by syzer** [comment]
@christian-bromann told you: come to hackergarden we will provide pizza + help
BTW also API can support both callbacks and promises.
I will look to v3

**Comment by Robinfr** [comment]
@christian-bromann do you have any command already rewritten so I have an idea of what you're going for? Then I might be able to lend a hand :smiley:

**Comment by christian-bromann** [comment]
Those problems will be history in `v3` ;-)

**Comment by christian-bromann** [comment]
@syzer thanks for all your input! Feel free to help @Robinfr and me moving the `v3` branch forward. As of today I got a pretty stable promise support implemented using a monadic approach and Q promises. Any help from your site is highly appreciated! Hit us up on [![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by syzer** [comment]
+1

On Sat, Apr 18, 2015 at 7:39 PM, Christian Bromann <notifications@github.com
> wrote:

> @syzer <https://github.com/syzer> thanks for all your input! Feel free to
> help @Robinfr <https://github.com/Robinfr> and me moving the v3 branch
> forward. As of today I got a pretty stable promise support implemented
> using a monadic approach and Q promises. Any help from your site is highly
> appreciated! Hit us up on [image: Gitter]
> <https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdriverio/webdriverio/issues/402#issuecomment-94186655>
> .
>



-- 
--Lukas 'SyZer' Gintowt

**Comment by maxbrunsfeld** [comment]
Are you going to publish an npm release from `v3` sometime soon?

**Comment by christian-bromann** [comment]
Hi @maxbrunsfeld,

I hope so. Though it will take some time to rewrite all commands as they are now based on promises (callbacks will still be supported). We also need to update quite a few docs, so not until next week or so. I stopped making prediction on releases. Any help will help us to make that release happen sooner ;-)
Just ping me on [![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by maxbrunsfeld** [comment]
@christian-bromann sounds great! Thanks for the update.
