### ISSUE TITLE
An option excludes success tests in specFileRetries

### ISSUE THREAD

**Issue by aha-oretama** [webdriverio/webdriverio#4148]
**Is your feature request related to a problem? Please describe.**
For example, if you have three flaky tests (named `A`, `B` ,`C`) in a spec file and `specFileRetries = 2`, in this situation, it is possible that `A` fails in the 0th retry, `B` fails in 1st retry, `C` fails in 2nd retry.
Then, this spec file results in a failure.

**Describe the solution you'd like**
I want to increase the success rate of a spec file. In above example, if we can exclude success tests in retries, the spec file results in a success because only `A` reruns in the 1st retry and `A` will succeed in the 1st retry.

To realize that, I suggest adding an option `isFiltered` in `specFileRetries` like this. Then, we can exclude success tests in retries.
```
   specFileRetries: {
       retries: 2,
       isFiltered: true // default: false
   }
```

**Describe alternatives you've considered**
Any solution to exclude success tests in `specFileRetries`.

**Additional context**

**Comment by PippoRaimondi** [comment]
@christian-bromann this would also help me. Assign this one to me, I will have a crack at it and give feedback of the progress sometime this week.

**Comment by PippoRaimondi** [comment]
I finally got time to work on this! will start today and keep you posted!

**Comment by PippoRaimondi** [comment]
Quick update: I started having a go at this initially for `mocha` as it's the default runner.

My understanding is that anything to do with the test level rather than spec level is out of reach of `wdio` given it's the spec runner framework responsibility to handle it (correct me if I am wrong, please).

Good news is that mocha has a `retry` mechanism for the test level (haven't tested it yet but I assume it works), which could be used in these cases, we then could have a `testRetries` flag that could be used instead of `specFileRetries`. This would require an update in a couple of packages, which includes `wdio-mocha-framework`...

Not so good news is that I couldn't easily find the `retry` capability exposed in mocha's interface, I will work on this a bit more tomorrow to scope what is needed for this to work...

**Comment by PippoRaimondi** [comment]
@aha-oretama 
@christian-bromann 

Short answer:
An issue needs to be opened in mocha's codebase to remove successful tests from a spec run on a spec level retry...

The closest you can get for now is retry at test level in wdio.conf.js:

```
  mochaOpts: {
    timeout: 60000,
    retries: 2,
  },
```

Long answer:
wdio sends a list of spec files to mocha in order for them to be executed, at this point mocha has no mechanism to return successful/failed test result, nor an interface to execute a named test within a spec which would allow us to somehow manipulate the subsequent run. 

Either way, it feels right that this level of test management should be dealt by the third party test runner as long as we are using one, in this case mocha. Having our adapter manipulate test runs seems wrong.

**Comment by mgrybyk** [comment]
@PippoRaimondi will you be able to submit issue to mocha?

Closing this one as far it is not wdio related, please reopen if I'm wrong

**Comment by PippoRaimondi** [comment]
> @PippoRaimondi will you be able to submit issue to mocha?
> 
> Closing this one as far it is not wdio related, please reopen if I'm wrong

Yes, I will open an issue against them and work closely to get that functionality added.

**Comment by neo-punit-patel** [comment]
@PippoRaimondi Would you happen to know the status of this functionality? I can't find anything in mocha repository. :)
