### ISSUE TITLE
Allow custom keys from wdio.conf file to be transmitted to browser.options

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/webdriverio#4182]
**Is your feature request related to a problem? Please describe.**
In v4, additional properties setup within wdio.conf.js file were transmitted over to browser.options. This is no longer the case in v5.
I am migrating my test suite from v4 to v5 and thus I am wondering if this change is intentional or not.

**Describe the solution you'd like**
wdio.conf.js
```
exports.config = {
  /* official conf ..
  */

  // custom conf
  myCustomConf: 'hello'
}
```

testFile.js
```
// do something with browser.options.myCustomConf
```

**Describe alternatives you've considered**
I could change my code to setup those properties on browser.options within the webdriverio "before" hook.

**Additional context**
For example one of my custom parameters is about which backend environnement my test should target. This is a static config that is common to all tests. It feels a bit counter intuitive to me that I should setup this configuration in the webdriverio "before" hook. That being said I already do a bunch of similar things in this hook, such as loading my custom commands and page objects, so that would only add one more.

Thanks for reading me :)

**Comment by christian-bromann** [comment]
See https://webdriver.io/docs/browserobject.html#get-config-options 

```js
browser.config.myCustomConf
```

**Comment by Kignuf** [comment]
Oh I missed than one, thanks !

**Comment by ashishgoel88** [comment]
@christian-bromann Hi, Is it still valid? 
I am unable to open this link.

**Comment by christian-bromann** [comment]
Nope, `browser.config` was removed the `browser` object in v8. We don't recommend to set custom configurations that aren't wdio related. Better to host such information in custom capabilities.

**Comment by nikhilgupta1789** [comment]
@christian-bromann how can we use custom configuration from wdio config file, for an example earlier we were able to use browser.config['customer_user'], but now since config replaced with options then I am not able to fetch details from wdio config file using browser.options['customer_user'], purpose of doing this If we're running locally we fetch details from config file and if we're running through CI/CD pipeline then we're dynamically replacing the username/password and other details in command prompt. Can you tell me how can I achieve this using browser.options I am stuck after migrating webdriverio from version 7 to version 8. It's little urgent.

**Comment by christian-bromann** [comment]
@nikhilgupta1789 it is not recommended to mix WebdriverIO configurations with custom properties. I recommend store the data in an external file and import it in your test.

**Comment by andrius-vetrenka** [comment]
Its possible to override wdio.config (services),  directly from test. I need to use devtools  service only for one specific test?
