### ISSUE TITLE
Click and wait for results

### ISSUE THREAD

**Issue by getub** [webdriverio/webdriverio#429]
I want to iterate through a list of checkboxes, selecting them one at a time, wait for the animation to finish, verify some changed values and so on. 

This is what I have so far. It doesn't work because the driver keeps clicking the boxes whereas the animation hasn't finished. How do I `click, wait, verify, repeat`? (preferably without async library, just using webdriverio). I've seen some examples that wait for element to appear etc. However, in my case, some visual state change happens which is harder to track. I'd just prefer to insert a pause. 

    client.elements('.chk-box', function(error, result){
        result.value.forEach(function(box, index){
            client.elementIdClick(box.ELEMENT, function(){
                client.pause(1000);
                verifyLoadedData(index);
            });
        })
    });

**Comment by christian-bromann** [comment]
Hi @getub,

`addCommand` is always a good idea to use when it comes to these kinds of scenarios because it can encapsulate a certain action into a command and provides a callback that stops the queue until it got called. I don't know how your animation looks like. I assume it is an element (e.g. ".animationElement") that pops up and disappears. Also I presume that `verifyLoadedData` is synchronous.

```js
client.addCommand('clickAndVerify', function(checkbox, index, done) {
    client
        .elementIdClick(checkbox.ELEMENT)
        .waitForVisible('.animationElement', 5000, true) // wait until ".animationElement" is not visible anymore
        .call(verifyLoadedData.bind(null, index))
        .call(done);
});

// somewhere in your test
client.elements('.chk-box', function(error, result){
    result.value.forEach(function(box, index){
        client.clickAndVerify(box, index);
    });
});
```

Try this and let me know if this works for you.

**Comment by getub** [comment]
This is very helpful, thank you. I saw some examples of `addCommand` in the issues section but missed the part about using bind to send arguments. I think it would be nice to put together some of these examples from issues into a cookbook on the documentation page.
