### ISSUE TITLE
getAttribute('innerHTML') returns null for Firefox browser

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4331]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Firefox 65-68
 - **Platform name and version:**  Windows 10

**Describe the bug**
`element.getAttribute('innerHTML')` returns null on Firefox but works on chrome

**Additional context**
Found work around which works
```
browser.execute(function (element) {
      return $(element).html()
    }, element.selector)
```

> Please use the correct markdown

**Comment by mgrybyk** [comment]
Please use gitter for such questions, this is not necessarily a defect.

**Comment by mgrybyk** [comment]
You are mixing lots of stuff here. First of all you are not able to use nodejs variables inside execute functions because they are executed in web browser scope.

Secondly there is no `html` method neither in wdio element nor in web browser.

Finally, here are two examples on how it should look:

```
const tableRow = $('tr')
// https://webdriver.io/docs/api/browser/execute.html
browser.execute(function (el) {
    // you are interacting with DOM here. `this` is web browser's `window` object
    return el.innerHTML
}, tableRow)

```
const tableRow = $('tr')
// https://webdriver.io/docs/api/element/getHTML.html
tableRow.getHTML()
```
