### ISSUE TITLE
"/wd/hub/session/{session id}/actions" puzzle

### ISSUE THREAD

**Issue by shinxi** [webdriverio/webdriverio#4380]
One question for curious, under the same chrome driver(76.0.3809.68), looks the "/wd/hub/session/{session id}/actions" API works differently on webdriverio v4 and v5, i.e., **browser.performActions** works well via 5.4.19, while on the other hand its counterpart **browser.actions** throws **UnknownCommand** via 4.14.4.
v5
```js
browser.performActions([
      {
        type: "pointer",
        id: "finger1",
        parameters: { pointerType: "mouse" },
        actions: [{ type: "pointerMove", duration: 0, x: 150, y: 150 }]
      }
    ]);
```
v4
```js
browser.actions([
      {
        type: 'pointer',
        id: 'finger1',
        parameters: { pointerType: 'mouse' },
        actions: [
          {
            type: 'pointerMove',
            duration: 0,
            x: 150,
            y: 150,
          },
        ],
      },
    ]);
```
And after set the `w3c = false` at `chromeOptions` setting, v4 also works well.
```js
{
    browserName: 'chrome',
    chromeOptions: {
      args: [`--window-size=${windowSize}`],
      w3c: false,
    },
  }
```

I'm kind of puzzled, why the same API works differently on two versions? Any magic be made for v5?

Thanks in advance.

**Comment by christian-bromann** [comment]
> **browser.actions** throws **UnknownCommand** via 4.14.4.

Probably because you are using a Chrome setup where this command is not supported.

> And after set the `w3c = false` at `chromeOptions` setting, v4 also works well.

I doubt that. If you set `w3c = false` it should not support the actions command at all.

> Any magic be made for v5?

No, we literally just send an HTTP request. The driver handles it differently based on your capability setting.

For further questions please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by shinxi** [comment]
> Probably because you are using a Chrome setup where this command is not supported.

I found that's due to v4 doesn't pass capabilities when creating a session, see https://github.com/webdriverio-boneyard/v4/pull/32. @christian-bromann Can we merge that pr so that for people who are still using v4 can be able to use w3c commands.
