### ISSUE TITLE
Can't get shadow element with devtools

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4484]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 77
- **Devtools:** 5.13.0-alpha.0

**Config of WebdriverIO**
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
Unable to find shadow element

**To Reproduce**
get some shadow element and try interacting with it
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("https://fiddle.jshell.net/falafelsoftware/KmmnK/show/")
        $("#result iframe").waitForDisplayed()
        browser.switchToFrame($("#result iframe"))

        const shadowButton = $('#img-caption-widget').shadow$('button')
        shadowButton.waitForExist()
    })
})
```

**Expected behavior**
should be possible to interact with shadow dom elements

**Log**

```
element ("function() {
      // element has a shadowRoot property
      if (this.shadowRoot) {
        return this.shadowRoot.querySelector('button')
      }
      // fall back to querying the element directly if not
      return this.querySelector('button')
    }") still not existing after 12000ms
```

**Comment by maxevilmind** [comment]
facing the same issue

**Comment by diervo** [comment]
After a long debugging on the internals of webdriverio, I was able to understand the issue, however I believe the fix will require a significant refactor on the way webdriverio has implemented a lot of the internals . 

I will try to articulate the problem:

They way webdriverio implements the devtools protocol its by calling pupeteer primitives, and store the Puppeteer native handlers as an abstraction and passing some reference to the webdriverIO element.

For example let's walk through an example: 
```js
it('test', async () => {
    await browser.url('https://rawgit.com/ebidel/2d2bb0cdec3f2a16cf519dbaa791ce1b/raw/fancy-tabs-demo.html');
    const fancyTabs = await browser.$('fancy-tabs');
    const attribute = await fancyTabs.getAttribute('selected'); // this will work
});
```

1. When invoking the `$` function on webdriverio, ultimately the devtools protocol calls the puppeteer [page selector primitive](https://github.com/puppeteer/puppeteer/blob/v3.0.4/docs/api.md#pageselector), that calls returns an ElementHandler which is the Puppeteer representation on a [DOM Element](https://github.com/puppeteer/puppeteer/blob/v3.0.4/docs/api.md#class-elementhandle). That reference gets stored in an internal Map in the DevTools object.

2. When applying any operation from the context of that element, same dance: Ultimately it will use the previous ElementHandler to perform native operations if that element context, and everything works as long as puppeteer returns an ElementHandler back.

3. However the problem is that the shadow commands require to`executeScript` to [traverse the shadow](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/scripts/shadowFnFactory.js).

4. The call to executeScript doesn't return a HandleElement, but rather a POJO serialization of it (a JSON object) which is useless since you can't reference anything back with it. The way webdriverio tries to solve this and reify back that element is by [adding an opaque attribute to the element](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/scripts/executeScript.js#L27) if the return of the execution call is an HTML Element. However this approach is very brittle and is fundamentally incompatible with shadow DOM.

5. So at this point webdriverio will try to find the element by `$('data[opaque-magical-id]')` which of course will fail since you can reach any element that is inside a shadow. So any operation within the shadow will be broken.

The fix is not theoretically hard: We need to change the reification method and use the [correct handler mechanism](https://github.com/puppeteer/puppeteer/blob/v3.0.4/docs/api.md#elementhandleevaluatehandlepagefunction-args) so you will always return the "live" version.

However as far as I digged into the code, the fix will require significant changes in a lot of packages and files, and it will need to also add a bunch of tests to make sure this doesn't happen again. (I hope i'm wrong here and is an easy refactor for someone who knows better the internals)

Unfortunately I don't have the time and focus that this fix will require, but in order to help anyone running into this and also to help people understand better the issue, I have created a hacky workaround that at least unblocks anyone running into this the issue is being addressed.

I'm hopeful that the webdriverio community will have time to tackle this problem soon.

```js
function monkeyPatchShadow() {
    const elementProto = require('webdriverio/build/commands/element');
    elementProto.shadow$ = async function _monkeyPatchedShadow() {
        const { sessionMap } = require('devtools');
        const { ELEMENT_KEY } = require('webdriverio/build/constants');

        const sessionObj = sessionMap.get(browser.sessionId);
        const driver = sessionObj.session;
        const elementStore = driver.elementStore;
        const elementReference = this[ELEMENT_KEY];
        const puppeteerHandle = elementStore.get(elementReference);

        const elementHandle = await puppeteerHandle.evaluateHandle(function (element) {
            if (element.shadowRoot) {
                return element.shadowRoot.querySelector('#tabs');
            }
        }, puppeteerHandle);
        
        if (elementHandle) {
            elementStore.clear();
            const newElementReference = elementStore.set(elementHandle);
            this[ELEMENT_KEY] = newElementReference;
            this.elementId = newElementReference;
        }

        return this;
    }
}

describe('test',() => {

    beforeAll(async () => {        
        monkeyPatchShadow();
    });

    it('PageObject is created correctly', async () => {
        await browser.url('https://rawgit.com/ebidel/2d2bb0cdec3f2a16cf519dbaa791ce1b/raw/fancy-tabs-demo.html');
        const fancyTabs = await browser.$('fancy-tabs');
        const tabs = await fancyTabs.shadow$('#tabs');
        const id = await tabs.getAttribute('id');
        expect(id).toBe('tabs'); // works

    });
});

```

As a side note, this was also a problem with the selenium-driver where you had to reify manually elements returned from executeScript, although it was simpler to fix. Hopefully this gets fixed as part of this too.

**Comment by christian-bromann** [comment]
Thanks so much @diervo , great writeup. I unfortunately currently also have no time available to look into this but someone who does can use your description to work on a fix. Cheers!

**Comment by ashokkumarg** [comment]
I have followed the thinds from this [WebDriverIO Shadow DOM Link](https://webdriver.io/blog/2019/02/22/shadow-dom-support.html)

But still I am still facing the same issue, Do I miss anything here? What is the fix that I need to do from my end?


```
class loginPage{

    get loginForm(){ return browser.$('body'); }
    get username() { return this.loginForm.$('#username') }
    get password(){  return this.loginForm.$("//input[@id='password']") }

    LoginWithCredentials(_username,_password){
        this.username.shadow$('div').setValue(_username);
        this.password.shadow$('/div').setValue(_password);
    }
}
export default new loginPage();
```
**DOM**
![image](https://user-images.githubusercontent.com/7566850/84623574-33f6e980-aefd-11ea-8834-ecb70ba17ca9.png)


**Exception:**

> Can't call setValue on element with selector "function() {
>       // element has a shadowRoot property
>       if (this.shadowRoot) {
>         return this.shadowRoot.querySelector('div')
>       }
>       // fall back to querying the element directly if not
>       return this.querySelector('div')
>     }" because element wasn't found

**Comment by blyakhmanv** [comment]
Hi all,

Are there any updates on this issue? Do we have any workarounds which can replace shadow command?

**Comment by christian-bromann** [comment]
> Are there any updates on this issue? Do we have any workarounds which can replace shadow command?

Please see the issue labels. If you want to work with shadow DOM please use the [WebDriver protocol](https://webdriver.io/docs/automationProtocols.html) as apparently it is not supported in Puppeteer atm.

**Comment by christian-bromann** [comment]
This will be improved with introducing the deep selector in #6709
