### ISSUE TITLE
Define proposal for sample files generation

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4502]
## Goal

Ultimately the goal of this feature is to allow users to auto generate a minimal sample project to get started easily. The ideal workflow should be:

1. `npm install @wdio/cli`
2. call `npx wdio init` where `init` is the same as `config` (maybe it is worth renaming the config command to be init and allow user to interactively modify their config using the `config` command but this is a different discussion)
3. go through set of questions where one is `Do you want to import sample files (yes/no)?`
4. Generate config files including sample files (if answered with yes)

The question I have is how much configurable do we want to make these sample files. Everyone has a different idea about an ideal setup. I can see this to be a new type of wdio plugin e.g. `wdio-cucumber-boilerplate`. We already have a [big list](https://webdriver.io/docs/boilerplate.html) of boilerplate projects which is great. We could implement this feature so it leverages these as new "plugin".

However I feel like a lot of these boilerplates come with a lot of opinions so the other option I would consider is to build 3 minimal templates within the `@wdio/cli` package with one or two page objects that really just provide a minimal structure.

What do you think?

**Comment by mgrybyk** [comment]
I'd generate minimum required files that atomic and reusable across for every test framework as much as possible. 
For example page objects and actions can be the same and then used in spec or given / then / feature files.
Lots of work here because it would be nice to bootstrap project for
- browser testing with selenium standalone or chromedriver
- mobile testing with appium (ideally both app and browser) 
- spec/feature file examples for other services, ex image comparison, devtools service 

I'd also do a better filtering of incompatible services here, ex devtools automation protocol with selenium standalone, etc.

As far as there are lots of examples to be generated I'd build easily extendable architecture here (avoid painful refactoring when adding new example for one of services, etc).

Here is how I see a flow:
1. I choose framework, services, etc in configurator
2. Sample project files are generated
3. I'm able to run some basic tests out of the box (browser, appium, etc)

Also I'd have some super simple config based on devtools automation project where I can skip annoying questions (maybe we have such already, not sure), so when I run wdio cli it would ask a question build generate default project files or you want to configure everything? It should be a good starting point for newcomers who want to have first running test out of the box, like with Cypress

**Comment by luiscspinho** [comment]
I think that this is a really good idea. Some things that come immediately to mind:
1. Choose framework, services (like @mgrybyk said, it would be nice to have some kind of indicator about mutually exclusive services), option to choose between device emulation/browser
2. After this, a basic `spec` would be generated with a sample Page Object and some config files for wdio (something like `wdio-dev`, `wdio-debug`, `wdio-grid` etc)


Anyone can now run the test locally, agains a remote selenium grid, local device etc etc

I don't see extra value in adding a lot of services that may lead people into confusion. If anyone can run a test locally or against a device/grid and see a report (`spec-reporter`) I think that it's more than enough for people to start digging deeper into the framework.

**Comment by jrobinson01** [comment]
I'd definitely like to see a generated config for services like browserstack and saucelabs. Have you considered the `npm init @wdio/boilerplate` approach?

**Comment by christian-bromann** [comment]
> Have you considered the `npm init @wdio/boilerplate` approach?

What do you mean by that?

**Comment by jrobinson01** [comment]
https://docs.npmjs.com/cli/init

**Comment by jrobinson01** [comment]
I don't know that many folks will start a project though from a webdriverio boilerplate. It's generally something you add to a project after you've gotten started.

**Comment by christian-bromann** [comment]
A proposal was made in #5590.
