### ISSUE TITLE
Is the documentation of custom services completely wrong?

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#4639]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [x] Other

**Description of the improvement / report**
The documentation on how to write custom services seem to be completely wrong: https://webdriver.io/docs/customservices.html

I tried following it and nothing was working. It was as if my service didn't exist. The hooks are simply not getting called. I looked at an existing service to get a clue about what I was doing wrong and the structure is completely different from the documentation. For instance https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-sauce-service/src has a launcher and a service and they exported like this:

  
    import SauceLauncher from './launcher'
    import SauceService from './service'

    export default SauceService
    export const launcher = SauceLauncher

The documentation doesn't say anything about launchers and services or about this way of exporting them. I'm still trying to figure out how it works, so I can't propose an improvement myself.

Could someone please explain the difference between a launcher and a service and why they are exported this way?

**Comment by christian-bromann** [comment]
@codiophile can you check https://github.com/webdriverio/webdriverio/tree/master/examples/wdio/custom-service which is an example of a test suite with a custom service.

**Comment by erwinheitzman** [comment]
I just tested the documentation and it seems correct to me when using https://webdriver.io/docs/customservices.html

Simple example (no Babel / TypeScript):
```
module.exports = class CustomService {

    constructor(options) {
        this.options = options;
    }

    onPrepare(config, capabilities) {
        console.log('options: ', this.options);
    }

    onComplete(exitCode, config, capabilities) {
        // TODO: something after the workers shutdown
    }

    // ...
}
```

And my config:
```
    services: [
        'selenium-standalone',
        [ CustomService, { someOption: true } ]
    ],
```

**Comment by christian-bromann** [comment]
@codiophile can you provide a reproducible example? Otherwise we have to close this since we can't really reproduce the issue.

**Comment by codiophile** [comment]
@christian-bromann I abandoned the project, but unlike the example from @erwinheitzman I was including the service by name in the config. I assume that's what makes the difference. Not sure why you would want two different behaviours, but that seems to be how it is.

When adding the service by name in the configuration it seems like the launcher instantiates the `launcher` and calls `onPrepare` and `onComplete`. The runner seems to instantiate the `default` and calls the rest of the hooks. This behaviour is not at all mentioned in the documentation.

**Comment by PabloHidalgo** [comment]
Hi @codiophile,

I have been working lately building some custom services (with their respective launchers) for our custom test runner based on top of WebdriverIO 5, and although the documentation does not show clearly the differences between them, you can deduce it through the name and seeing the code of different custom services.

- Launcher for launching processes you are going to use all over the lifecycle of your e2e tests through onPrepare and onComplete hooks. Selenium and appium services only have a launcher.

- Services for interact (for example), through custom cucumber/webdriverio hooks, with the processes previously launched. [Testing bot service](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-testingbot-service) have both launcher and service.

If you don't need to launch any extra process, or you don't need to interact with frameworks/runner lifecycle hooks, only use what you need.

On the other hand, if you include the service name in the config instead of the code, you must stick to 'npm' convention as stated here: https://webdriver.io/docs/customservices.html#npm - it's working fine :)

Disclaimer: We are following the same architectural design (mono repo with lerna, separate packages for cli, services, ...), compiler (babel), as WebdriverIO 5 project.

**Comment by codiophile** [comment]
@PabloHidalgo If you have to deduce how it works by reading the code of existing services, then arguably the documentation isn't good enough. 

Based on @erwinheitzman's comment, the behaviour is different depending on wether you import the service yourself or you list it by name and let wdio import it for you. It seems reasonable that this difference should be documented, because following the documentation, nothing was working for me and I had to read the code of other services to figure out how to make it work.

**Comment by mgrybyk** [comment]
Feel free to improve the doc

**Comment by codiophile** [comment]
Considering that the pull request has been merged, I will close this.
