### ISSUE TITLE
Selenium vs. PhantomJS

### ISSUE THREAD

**Issue by dschinkel** [webdriverio/webdriverio#468]
I'm very confused.  Your doc example here says to install selenium and start it: http://webdriver.io/guide.html

I'm using PhantomJS.  So your example here makes more sense to me: https://github.com/webdriverio/webdriverio/blob/master/examples/cucumber/features/step-definitions.js

so which is it, do we need selenium AND phantom running or is Phantom used as an alternative to Selenium or what?

**Comment by christian-bromann** [comment]
PhantomJS is just a browser that can get instrumented by Selenium. If you just want to run your tests with `PhantomJS` (by executing `$ phantomjs --webdriver=4444`) then you don't need to have a Selenium server running.
Selenium gets useful if you want to test your app on different browser. Instead of starting the desired driver (chromedriver, phantomjs, safaridriver, iedriver etc) everytime again you can just let Selenium do that work for you. So it checks which capabilities you want and starts the desired driver.

**Comment by dschinkel** [comment]
That's what I thought, thanks for verifying.
