### ISSUE TITLE
Jasmine test and result object on afterTest hook have wrong properties set

### ISSUE THREAD

**Issue by carlos-gva** [webdriverio/webdriverio#4743]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.15.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.16.3]
 - **NPM version:** [5.8.0]
 - **Browser name and version:** [Chrome 78]
 - **Platform name and version:** [macOS Mojave 10.14.6]
 - **Additional wdio packages used (if applicable):** [@wdio/jasmine-framework, @wdio/spec-reporter]

**Describe the bug**
When a test fails with an expectation, the `passed` property of `test` and `result` objects is set to `true`.

test object:
```js
{ id: 'spec2',
  description:
  'Test 1',
  fullName:
  'Suite 1 - Test 1',
  failedExpectations:
  [ { matcherName: 'toEqual',
    message: 'Expected true to equal false.',
    stack:
    'Error: Expected true to equal false.\n    at ...,
    passed: false,
    expected: false,
    actual: true } ],
    passedExpectations: [],
    deprecationWarnings: [],
    pendingReason: '',
    duration: 1871,
    start: 1573046624244,
    title:
    'Test 1',
    fullTitle:
    'Suite 1 - Test 1',
    error: undefined,
    passed: true 
  }
```

result object:
```js
{ error: undefined,
  result: undefined,
  duration: 1295,
  passed: true }
```

**To Reproduce**
Add an `expect(true).toEqual(false);` on your test and run it.

**Expected behavior**
I was expecting that the property `passed` was set to `false` when a test fails due to a failed expectation.

**Additional context**
This works properly if the test fails due to a timeout instead of an expectation.
For example reaching a timeout on a `waitForDisplayed` condition, correctly set the `passed` property to `false`.

**Comment by christian-bromann** [comment]
Patch with a fix is proposed in #4823.

**Comment by venkatrvaradhan** [comment]
Hi, Has this issue been resolved? I'm facing this with the WebdriverIO version **8.16.4**. Please let me know.

**Comment by venkatrvaradhan** [comment]
Hi @christian-bromann, Thanks for the reply. Please find below a reproducible example.

Environment (please complete the following information):

WebdriverIO version: 8.16.4
Framework: Jasmine
Language: Javascript
Mode: [WDIO Testrunner]
If WDIO Testrunner, running sync/async: [async]
Node.js version: [18.15.0]
NPM version: [9.5.0]
Browser name and version: [Chrome 118]
Platform name and version: [Windows 10]
Additional wdio packages used (if applicable): [@wdio/jasmine-framework, @wdio/spec-reporter, @wdio/allure-reporter]

**Describe the bug**

We have a test suite file containing multiple specs and in the afterTest() hook in the wdio.conf.js file, we are trying to capture the result of each spec and increment the pass/fail count based on the result (true/false). However, if the spec fails due to the Expectation failure, the results passed value shows as true instead of false. Could you please help me to overcome this issue?

Note: if the spec fails due to the timeout, then the value of the results passed is captured as false correctly. 

I executed 2 specs here, where 1 passes and 1 fails. Below are the results printed in the console:
**Passed spec results:** 
 {
 retries: { attempts: 0, limit: 0 },
 error: undefined,
 result: undefined,
 duration: 275,
 passed: true
 }

**Failed spec results:** 
 {
retries: { attempts: 0, limit: 0 },
error: undefined,
result: undefined,
duration: 153,
passed: **true** (This must be false, but true)
}

Please let me know if you need any additional information. Thanks!

**Comment by christian-bromann** [comment]
@venkatrvaradhan a minimal reproducible example would be very helpful in this case.

**Comment by venkatrvaradhan** [comment]
@christian-bromann I'm sorry, I didn't get your above question. Are you expecting a sample project with all the report details?

**Comment by venkatrvaradhan** [comment]
Hi @christian-bromann, Please find below a sample project created for this issue. We have two specs created out of which 1 will get passed and the other will get failed. But the afterTest() hooks results passed show as true for both the specs. Please lmk if you've any questions. Thanks!
[JasmineProject.zip](https://github.com/webdriverio/webdriverio/files/13053036/JasmineProject.zip)

**Comment by christian-bromann** [comment]
@venkatrvaradhan I can't really say when I get the chance to look into this. Any contributions with a bug fix would be appreciated.

**Comment by venkatrvaradhan** [comment]
Hi @christian-bromann, sorry I was not available in the past week. It'd be great if this issue could be prioritized ASAP as this is blocking my automation works. Also kindly let me know if I need to open a new ticket for this issue. Thanks!
