### ISSUE TITLE
Using ErrorHandler to reveal webdriver callstack in custom error handler

### ISSUE THREAD

**Issue by richsilv** [webdriverio/webdriverio#481]
To avoid throwing an error in my Node process (which I don't want as I'm using Meteor), I'm capturing Webdriver errors as follows:

```
browser.on('error', function(e) { 
  console.log('***** Webdriver Exception:  *****')
  console.log(e.body.state);
  console.log(e.body.value.class);
  console.log('ERROR IS', e.err);
  console.log(new wd.ErrorHandler(e));
  console.log('');
});
```

I can see that if I *don't* include this event handler then when the node process throws an error it also logs the details for the webdriver callstack: 

> W20150401-11:54:13.042(1)? (STDERR)      Callstack:
W20150401-11:54:13.042(1)? (STDERR)      -> elementIdClick("12")
W20150401-11:54:13.043(1)? (STDERR)      -> click("[slideinbutton=\"true\"]")

It's clear that EventHandler is being used to generate this information, but my question is how I can do this myself - i.e. how can I handle errors in a callback as above, but access information about the webdriver commands that have caused the exception?  All I can generate at present is:

> I20150401-12:05:06.160(1)? ***** Webdriver Exception:  *****
I20150401-12:05:06.160(1)? element not visible
I20150401-12:05:06.160(1)? org.openqa.selenium.ElementNotVisibleException
I20150401-12:05:06.160(1)? ERROR IS null

This is obviously not terribly helpful as it's impossible to know which element it is that isn't visible.

Thanks

**Comment by hanneshal** [comment]
I had the same problem and came up to use the functions of my test suite (mocha). I believe the problem is that webdriver.io only catches on selenium server errors and not JS errors. I needed to geht the exact line because I resuse several elements for my tests in external helper methods and can't find the right line without an extensive search. Now I get a full stack trace, incl. the corresponding line number.

Mocha is able to catch those errors because it runs the JS scripts which run the tests. This Should be the same in Meteor. 

Johannes

**Comment by richsilv** [comment]
I've resolved this for the time being by catching `command` events and assuming that the errors relate to the most recent of those.  Doesn't seem totally satisfactory as there must surely be the potential for a race condition here, but it's working.
