### ISSUE TITLE
Appium (Android/iOS) reload session with new capabilities

### ISSUE THREAD

**Issue by daemontoxa** [webdriverio/webdriverio#5019]
**Describe your question with as much detail as possible**
Hi,

Is it possible to reload the current Appium session (Android/iOS) with the new set of capabilities?

Currently, I'm automating a mobile app that can take different process arguments and for some test, I want to reload app with new set of arguments that help to restart the app/clear data, etc.

Thanks.

**Comment by wswebcreation** [comment]
Hi @daemontoxa 

This is more a question for our Gitter channel. But to answer your question, I've never tried it and as far as I know you're not able to do this without "releasing" the session.

Have you also looked into the 
http://appium.io/docs/en/advanced-concepts/settings/ -api? You might be able to do with it what you want, if you look at Appium Desktop you will also see you have session and device settings you might change (in the Advanced tab).

Closing it for now because it's not a WebdriverIO related issue.

**Comment by mgrybyk** [comment]
@daemontoxa see https://github.com/webdriverio/webdriverio/issues/4061#issuecomment-499414737

There is an example that might help you

**Comment by daemontoxa** [comment]
@mgrybyk @wswebcreation Thanks for suggestions. I will also try to "play" with --session-override appium config flag
