### ISSUE TITLE
Not getting suite name in beforeSuite Hook

### ISSUE THREAD

**Issue by KumarSumitD** [webdriverio/webdriverio#5302]
Hi,
I have added beforeSuite hook in wdio config 
defaultConfig.beforeSuite = function(suite) {
    console.log(suite);
  };

and then i am running the tests
npx wdio wdio.conf.js --baseUrl=[my base url] --suite=[configured suite]

But on suite console.log - i am getting 
{ type: 'beforeSuite',
  title: 'Jasmine__TopLevel__Suite',
  fullName: null,
  file:
   '[suite files]' }

Why the fullName is null, shouldn't display the name of suite which is passed ?

**Comment by christian-bromann** [comment]
> Why the fullName is null, shouldn't display the name of suite which is passed ?

Because you are receiving the top level suite from Jasmine not the first suite you have defined in your test. Also note that a suite in the hook is something different than the suite parameter. The suite parameter just groups multiple tests into a group.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
