### ISSUE TITLE
Be more expressive when DevTools service can't connect to browser

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5374]
**Is your feature request related to a problem? Please describe.**
Currently if someone uses the DevTools service chances are that that person experiences an error like

```js
browser.cdp is not a function.
```

because Puppeteer is not able to connect with Chrome or uses a different browser that is not supported.

**Describe the solution you'd like**
Always register the custom commands from the DevTools service but throw with an error message if for some reason no connection could be established. The error message should be meaningful.

**Describe alternatives you've considered**
none

**Additional context**
Many user have experienced this issue and reported it in the support channel.

**Comment by pjcalvo** [comment]
Hi @christian-bromann . I was looking at where this issue came from:

![image](https://user-images.githubusercontent.com/7219896/83173836-b6e30c00-a0d6-11ea-85e7-a375ce7cfd95.png)

The developer here is not declaring devtools as a service. So he is getting the error. 

If you look at the code there is already a validation for non supported browsers.

![image](https://user-images.githubusercontent.com/7219896/83173998-f14ca900-a0d6-11ea-9f38-b033002acbf3.png)


I have tried to find reproducible steps to actually find a situation where the cdp command is not registered on the browser but no luck.

**Comment by christian-bromann** [comment]
@pjcalvo thanks for looking into this. You bring up a good point. What happens if someone doesn't have the devtools service set up. I thought about maybe adding the command in WebdriverIO by default and then have the service overwrite it but then I would need to maintain service commands in services which I would rather avoid.

**Comment by pjcalvo** [comment]
Oh I got your point now. But that would mean that we need to implement default commands for every other custom service command.

I vote for closing this issue. And enforce the explicit setup of each of the service.

**Comment by christian-bromann** [comment]
@pjcalvo something that we could still do is to define the command in the service constructor and in case the browser [is not supported](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/index.js#L24) or the connection to the Chrome DevTools Protocol could [not be established](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/index.js#L74) we still have the command defined and it would throw an  error instead of not being defined.

**Comment by christian-bromann** [comment]
Was re-checking the service and found that it now throws:

> The @wdio/devtools-service currently only supports Chrome version 63 and up, and Chromium as the browserName!

Closing.
