### ISSUE TITLE
Add option to not print cid

### ISSUE THREAD

**Issue by RafalSkorka** [webdriverio/webdriverio#5479]
**Is your feature request related to a problem? Please describe.**
I am running my tests always with a single worker instance so all of the logs are prepended with the [0-0] or [0-1] etc. As I checked the sources this is called 'cid' and is prepended in RunnerTransformStream class. However, for unknown reason sometimes the cid is not prepended and the log looks like this:

```
[0-1] 2020-06-10T06:51:40.670Z INFO E2E: ✓ ------------------------------------------------------------
2020-06-10T06:51:40.670Z INFO E2E: ✓ Running: Assure Upload settings are correct
[0-1] 2020-06-10T06:51:40.671Z INFO E2E: ✓ ------------------------------------------------------------
```

**Describe the solution you'd like**
I'd like to have an option to not print these values as they have no meaning for me and only make the logs bigger and less readable.

**Describe alternatives you've considered**
I tried to set the JEST_WORKER_ID environment variable but that has other consequences.

**Additional context**
The missing cid happens for me on Windows 10 and also on Ubuntu 16.

**Comment by christian-bromann** [comment]
> However, for unknown reason sometimes the cid is not prepended

This happens if the lines are printed at the same time part part of the same buffer stream.

> an option to not print these values as they have no meaning for me

How do they have no meaning for you? They tell you which instance is printing this log line? How are you differentiating who is logging what?

I don't think removing these is a good idea. The only thing one could do is to check if we can backfill the missing cids in the lines.

**Comment by RafalSkorka** [comment]
no longer needed :(
