### ISSUE TITLE
Allure report suites display only 45 out of 56 run specs for some reason when remotely run. 

### ISSUE THREAD

**Issue by lemoncypress** [webdriverio/webdriverio#5546]
- **NPM version:** 6.4.1

**Description**
There seems to be a cap on number of specs that can be displayed on these reports when remotely run. Locally I see all 56 specs being executed.

**Comment by dimkin-eu** [comment]
for sure some dataprovider used? allure loves to combine tests with non-unique names into retries

**Comment by christian-bromann** [comment]
@lemoncypress why didn't you follow the [issue template for bug reports](https://github.com/webdriverio/webdriverio/blob/master/.github/ISSUE_TEMPLATE/--bug-report.md) here because this issue misses a lot of information like which version of Allure you are using as well some screenshots or a more descriptive report of your setup. This makes it difficult to make any statement at this point.

**Comment by lemoncypress** [comment]
You were right! Thanks..All I had to do was make the suite names unique... :)

**Comment by lemoncypress** [comment]
> @lemoncypress why didn't you follow the [issue template for bug reports](https://github.com/webdriverio/webdriverio/blob/master/.github/ISSUE_TEMPLATE/--bug-report.md) here because this issue misses a lot of information like which version of Allure you are using as well some screenshots or a more descriptive report of your setup. This makes it difficult to make any statement at this point.

My bad I should have included more details.. I didn't have all the information handy. Will do next time.
