### ISSUE TITLE
Trying to detect/wait for page navigation

### ISSUE THREAD

**Issue by kierenj** [webdriverio/webdriverio#582]
I'm trying to detect or wait for page redirects and location URL changes.  I'm basically trying to check that accessing URL "x" in fact directs the user back to URL "y".

I had a couple of ideas for approaching this:
1. Wait for page nav, wait for title change, wait for URL change - all not possible?
2. Wait for a H1 element to appear with the text "Something from page Y"

This seems to be possible using an expected wait condition with WebDriver.

At the same time, I can't see how to build a wait for a certain element to have a certain value.  For example, an asyncy form submission which updates an area of the screen to say "Complete" - I can only get the text once.

Could this have something to do with the implicitWait - the documentation just says "DEPRECATED!!!"?  In the examples I see mixed approaches - some tests use .pause(), some simply navigation with url() then getTitle() immediately.  In either case isn't that depending on some magical timing?

As I say, opening an issue since it seems a bit of an omission.  If there's a way I can help implement this, I'll give it a crack - what would you like the API to look like?

**Comment by christian-bromann** [comment]
In `v3` it would look like this:

```js
browser.waitUntil(function() {
    return browser.url().then(function(url) {
        return url.indexOf('/y') > -1;
    });
}, 5000);
```

Wait until the url contains "/y". In the current version you can make use of `waitForExist` to wait on an element that only exists in y but not in x. I guess this would be the easiest solution.

**Comment by kierenj** [comment]
Ah I see - that looks good thanks.  What kind of state is v3 in, something I should/could be using?

waitForExist doesn't seem to throw any error if the element doesn't exist:

`.waitForExist('//h1[text()="Your Account zanzibarextratext this step continues fine"]')`

The documentation isnt super clear if you don't mind me saying - I can pass a callback but the parameters aren't documented.  Do I need to assert in the callback?

**Comment by christian-bromann** [comment]
`v3` will get published this week. You don't need to do any assertions within the callback. The queue continues ones that element you are waiting for you reached the timeout

**Comment by monolithed** [comment]
Maybe it would be interesting for someone how to implement `waitForUrl`:

```js
/**
 * @alias browser.waitForUrl
 * @param {string|RegExp|Function} value
 * @param {number} timeout — ms
 * @param {number} revert
 * @returns {boolean}
 */
browser.addCommand('waitForUrl', function (value, timeout, revert) {
	let url, actual;

	try {
		return this.waitUntil(() => {
			url = this.getUrl();
			actual = value === url;

			if (typeof value === 'string' && !value.endsWith('/')) {
				url = url.replace(/\/$/, '');
			}

			if (typeof value === 'function') {
				actual = value(url);
			} else if (value[Symbol.match]) {
				actual = value.test(url);
			}

			return value && actual && !revert;
		}, timeout, '');
	} catch (error) {
		let message = 'Could not wait for the required url:';
			message += `\n\tActual: ${url}`;
			message += `\n\tExpected: ${actual}`;

		throw new Error(message);
	}
});
```

**Comment by Miladinho** [comment]
I'm relatively new to webdriverio. I have code that looks like this:

`describe('web page', function() {
    before(function() {
        browser.url('/');

        if (isOnLoginPage()) {
            signInWithDefaultCreds(DEFAULT_EMAIL, DEFAULT_PASSWORD);
        }

        console.log(new Date().getTime()," beforeWait");
        browser.waitForExist('svg', 30000);
        console.log(new Date().getTime()," afterWait");

        console.log(browser.getText('body').includes('Dispatch'));
    });
    it('should be logged in', function () {
        expect(isOnLoginPage()).to.be.false;
    });
    it('should not crash when clicking on random reports tab', function() {
        browser.url('/titan/#/reports').waitUntil(function() {
            url.includes('reports');
        }, 30000);
        //console.log(browser.getText('body'));
        //browser.waitForExist('div', 30000);
        expect(browser.getText('body')).to.include('Reports');`

My issue is that our web page take s awhile to load, and the testrunner does not wait until the full page is loaded on a browser.url(). I got the login to work using waitForExist but that wont help me when I load another url because we are using webpack so there are no static class names to reference and wait for on elements. Waiting for an "svg" element work when I loaded the main application but it wont work when I want to see other tabs within the application for example, because the tab bar has svg icons and is present in every view.

I currently get a timeout error 
`Timeout of 30000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.`

**Comment by Miladinho** [comment]
I'm going to post my issue here because it may be related. Essentially I am not understanding how the waitFor/waitUntil calls are working. I am using the webdriver testrunner and I know that it runs synchronously.
Note:
I am using 'waitForExist' in the before hook which works fine, but I cant use it in the second test case (reports page) because the code is not properly tagged with ids, and once I enter the main application there is a big tab bar with svg logos and everything else on the page is a collection of divs. Classnames also don;t work because webpack dynamically makes weird names for element classes.

Code:
`describe('web page', function() {
    before(function() {
        browser.url('/');
        if (isOnLoginPage()) {
            signInWithDefaultCreds(DEFAULT_EMAIL, DEFAULT_PASSWORD);
        }
        console.log(new Date().getTime()," beforeWait");
        browser.waitForExist('svg', 30000);
        console.log(new Date().getTime()," afterWait");
    });
    it('should be logged in', function () {
        expect(isOnLoginPage()).to.be.false;
    });
    it('should not crash when clicking on reports links', function() {
        browser.url('/reports');
        // browser.waitUntil(function() {
        //     browser.getText('body').includes('Reports');
        // }, 20000);
        synchronousTimerHack(2000);
        //console.log(browser.getText('body'));
        expect(browser.getText('body')).to.include('Reports');
    });
});
function signInWithDefaultCreds(email, password) {
    $('#field-email').setValue(email);
    $('#field-password').setValue(password);
    var button = $('button');
    button.click();
}
function isOnLoginPage() {
  return browser.getText('body').includes('SIGN IN');
}
function synchronousTimerHack(milliseconds) {
    const time = new Date().getTime();
    while(new Date().getTime() < time+ milliseconds) {}
}
`

I'd like to know why the code below is working CONSISTENTLY, while the other examples after it do not work sometimes or not at all:

`    it('should not crash when clicking on reports link', function() {
        browser.url('/reports');
        synchronousTimerHack(2000);
        expect(browser.getText('body')).to.include('Reports');
      })
`

Case 1:
`    it('should not crash when clicking on reports links', function() {
        browser.waitUntil(function() {
          browser.getText('body').includes('Reports');
        }, 20000);
        expect(browser.getText('body')).to.include('Reports');
`
Error 1:
`1) web page should not crash when clicking on random links:
An element could not be located on the page using the given search parameters ("body").
running firefox
Error: An element could not be located on the page using the given search parameters ("body").
    at elements("body") - getText.js:18:17
    at getText("body") - errorHandler.js:112:39`

Error 1.2:
``

Case 2: 
`    it('should not crash when clicking on reports link', function() {
        setTimeout(function() {}, 2000);
        expect(browser.getText('body')).to.include('Reports');
      });`
Error 2: Basically not waiting long enough, same error when I increase timeout time by 10x to 20,000 ms
`1) web page should not crash when clicking on random links:
expected '' to include 'Reports'
running firefox
AssertionError: expected '' to include 'Reports'`

**Comment by bay-qa-alexey** [comment]
browser.waitUntil(function () {
    	  return $( your_locator_here ).isVisible()
    	}, 5000, 'Error: waitUntil');

    	$( your_locator_here ).click();

**Comment by Mufeez** [comment]
i have a toggle button on the same page which once clicked change its icon and text from disable to restore but once you click on that button same page get reloaded but assertion is failing ,may be its reading from previous dom and not refreshed dom . How can i know that page is refreshed successfully.

i cannot use waitforexist as the elements are present on the same page before and after

it('Disable Application', () => {
        DevPortal.newApplication.disableApplication();
        DevPortal.newApplication.restoreApplicationButton.waitForDisplayed();
        browser.waitUntil(() => {
            return (DevPortal.newApplication.restoreApplicationButton.getAttribute('title').toString() === ('Disable the Application'));
        }, 2000);
        expect(DevPortal.newApplication.restoreApplicationButton.getAttribute('title').toString()).toBe('Disable the Application');
    });

**Comment by mgrybyk** [comment]
How about adding some hidden element to the dom just before clicking that button, and then waiting for that element to be not existing?
