### ISSUE TITLE
Tracking doc: rewrite `@wdio/config` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5831]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-config` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-config` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by Y4suyuki** [comment]
@christian-bromann Hi, I would like to work on this issue!
This is my first time contributing to open source projects but I checked out related issues and PRs and I think I'm good to go.

**Comment by christian-bromann** [comment]
@Y4suyuki awesome, let me know if you need any help. Feel free to rather make PRs for individual files rather than the whole package. Makes reviewing of PRs easier.

**Comment by christian-bromann** [comment]
@Y4suyuki do you have any updates or need any help?`

**Comment by Y4suyuki** [comment]
@christian-bromann 
Hi, sorry for not updating for long time. I'm working on wdio-config/src/utils.js (https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/utils.js).
And yes I need some help.
I started working on utils.js, spent some time to catch up code base and I have problems typing `validateConfig` and `detectBackend` in utils.js.
- For detectBackend, I need [ConfigParser._config](https://github.com/webdriverio/webdriverio/blob/4d01a5b7efae9f0677c90722ce175a5d148a1575/packages/wdio-config/src/lib/ConfigParser.js#L17) to be typed. First I have bit stucked wondering how this config is typed and used. I searched in the source code for the spec and usage about config and found [ConfigurationFile.md](https://github.com/webdriverio/webdriverio/blob/master/docs/ConfigurationFile.md) (just few minutes ago :sweat_smile: ). With ConfigurationFile.md I think I can type config and move on. Do you think ConfigurationFile.md have sufficient information to type config? And also Do you think that there is anything I have to check out for typing config?
- For validateConfig, I found [webdriver package](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/types.ts) is already defined types for parameters of validate config like [Options](https://github.com/webdriverio/webdriverio/blob/4d01a5b7efae9f0677c90722ce175a5d148a1575/packages/webdriver/src/types.ts#L492). I want use these types but I can't import it from webdriver package since webdriver package import wdio-config package and it makes mutual dependency (or is it just OK? I don't have an experience to work on multiple package project). So do you have any suggestion how to work on this? I think we need some types like Options typed in wdio-config package and imported in other packages or make another package just for types used in other packages.

**Comment by christian-bromann** [comment]
> * Do you think ConfigurationFile.md have sufficient information to type config? And also Do you think that there is anything I have to check out for typing config?

Nothing in particular that would pop up in my mind. It should be possible to type that file.

> * So do you have any suggestion how to work on this?

I think we got around this by just adding `webdriver` to the `types` list in the `tsconfig.json`.

**Comment by abdatta** [comment]
Hi, I'm trying to rewrite `lib/ConfigParser.ts`. Had a question.  Is there any documentation anywhere on what is expected to be the structure of `fileConfig`?
I can see from code that it should have a `capabilities` property and many hooks as properties, but I would like to provide a stricter type if I can find some documentation on the expected structure of config.

**Comment by abdatta** [comment]
I read the above comments and found the `Options` interface within `webdriverio-core.d.ts`. I realised importing this within `@wdio/config` would result in unnecessary circular dependency. I tried adding `webdriver` and `webdriverio` in types in the `tsconfig.json` of this package, but it fails to recognize the types.

I think, maybe we can consider moving the `Options` interface altogether into the `@wdio/config` package, and make the other places import it from here instead. It makes more sense since `@wdio/config` is already a dependency of `webdriverio` package so it can import from there without any circular dependency.

**Comment by christian-bromann** [comment]
> I think, maybe we can consider moving the `Options` interface altogether into the `@wdio/config` package

Sounds reasonable to me. Note that there are different layers of options:

- WDIO testrunner options that contains options of the `webdriverio` and `webdriver` package and related to the testrunner, e.g. `specs`, `services`, `framework` etc.
- `webdriverio` package options that are related to run WebdriverIO as a standalone package (e.g. `baseUrl`, `waitforTimeout` etc.
- `webdriver` package options that are related to the protocol binding, e.g. `hostname`, `port`, etc.

So far I see one option (`capabilities`) that is differs when used in `webdriver` or `webdriverio` in standalone mode (`capabilities` as an object`) vs. in wdio testrunner mode (`capabilities` as an array of capabilities). It would be great if we could clean this up and have these options defined where they belong.

**Comment by abdatta** [comment]
Yes, I am currently stuck at trying to type capabilities properly. I see there are two types of capabilities:
In `webdriver/webdriver.d.ts` ([link](https://github.com/webdriverio/webdriverio/blob/6f7a0c932f7cda50979f733616cf0b4c9f1d0b42/packages/webdriver/webdriver.d.ts#L612))
```
capabilities?: WebDriver.DesiredCapabilities[] | MultiRemoteCapabilities;
```
and in `webdriverio/webdriverio-core.d.ts` ([link](https://github.com/webdriverio/webdriverio/blob/6f7a0c932f7cda50979f733616cf0b4c9f1d0b42/packages/webdriverio/webdriverio-core.d.ts#L158))
```
capabilities?: DesiredCapabilities | W3CCapabilities;
```
@christian-bromann Can you let me know which ones to use in [ConfigParser.js](https://github.com/webdriverio/webdriverio/blob/6f7a0c932f7cda50979f733616cf0b4c9f1d0b42/packages/wdio-config/src/lib/ConfigParser.js#L43)?

**Comment by christian-bromann** [comment]
> @christian-bromann Can you let me know which ones to use in [ConfigParser.js](https://github.com/webdriverio/webdriverio/blob/6f7a0c932f7cda50979f733616cf0b4c9f1d0b42/packages/wdio-config/src/lib/ConfigParser.js#L43)?

it should be:

```js
capabilities?: (DesiredCapabilities | W3CCapabilities)[] | MultiRemoteCapabilities;
```

because the wdio testrunner takes a list of capabilties to run tests in parallel or multiremote capabilities to run multiple browser in one spec file.

**Comment by abdatta** [comment]
Thanks @christian-bromann . Can you also help me understand the types for the various hooks? Some seem to be arrays while others are just functions. How do we know which one should be array and which ones should be just a function?
The `websriverio-core.d.ts` defines:
```
type _HooksArray = {
    [K in keyof Pick<HookFunctions, "onPrepare" | "onWorkerStart" | "onComplete" | "before" | "after" | "beforeSession" | "afterSession">]: HookFunctions[K] | Array<HookFunctions[K]>;
};
type _Hooks = Omit<HookFunctions, "onPrepare" | "onWorkerStart" | "onComplete" | "before" | "after" | "beforeSession" | "afterSession">;
interface Hooks extends _HooksArray, _Hooks { }
```
But the `DEFAULT_CONFIG` in `@wdio/config` doesn't exactly follow the same. ([Link](https://github.com/webdriverio/webdriverio/blob/b54edafa6551158a64eda24837a8f42f8196d175/packages/wdio-config/src/constants.js#L42)) It has all the hooks initialised to empty arrays, even ones that are not expected to be arrays.

**Comment by christian-bromann** [comment]
Currently you can pass in hooks in `wdio.conf.js` as arrays as well as functions, e.g.:

```js
onPrepare: [() => console.log(1), () => console.log(2)]
// same as
onPrepare: () => {
	console.log(1)
	console.log(2)
}
```

So it needs to be both.

**Comment by abdatta** [comment]
Thanks, I have typed that accordingly. One small question:
In `webdriverio.d.ts`, `Options.specFileRetryAttempts` is typed as `readonly`. ([Link](https://github.com/webdriverio/webdriverio/blob/b54edafa6551158a64eda24837a8f42f8196d175/scripts/templates/webdriverio.tpl.d.ts#L177))
```ts
readonly specFileRetryAttempts?: number;
```
Is there any reason to specifically type it as `readonly`? I am facing some issues in reusing that `Options` interface because of that. Is it OK if I remove the `readonly` from that typing?

**Comment by christian-bromann** [comment]
This is an internal flag that should not be exposed to users. I would even say we should remove it. In the `@wdio/runner` we then need to create an interface that extends the public types with these private types.

**Comment by abdatta** [comment]
I have raised a PR for the rewrite of `utils.ts` and `constants.ts`. #6123 
Rewrite of `configParser.js` is gonna take some more time, I'll raise a PR for that later.

**Comment by abdatta** [comment]
Hi, I think this should be moved to `In Progress` in the [Typescript Rewrite Project Dashboard](https://github.com/webdriverio/webdriverio/projects/14).
