### ISSUE TITLE
Tracking doc: rewrite `@wdio/reporter` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5842]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-reporter` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-reporter` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by suniljaiswal01** [comment]
@christian-bromann  I would like to give a try for this

**Comment by christian-bromann** [comment]
🎉 @suniljaiswal01 go for it

**Comment by christian-bromann** [comment]
@suniljaiswal01 did you already start with this? What is your state? During the 1:1 pairing session with @ablok we identified that working in `@wdio/reporter` is a good start to unblock the reporter rewrite. Do you have any current state?

@ablok didn't see that someone claimed this already 😞  maybe no harm/work has been done yet.

**Comment by ablok** [comment]
Started a first attempt PR here: https://github.com/webdriverio/webdriverio/pull/5909
I am sorry, don't know how to use this issue as a basis for the PR.

**Comment by suniljaiswal01** [comment]
I have done almost all the changes, there is just one place where i am facing issue and not sure how to resolve it. Should i continue on this or not? If yes, could you please help me resolve that issue so that  i can raise a PR for the same

Issue Detail:
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/src/index.js#L64 In this line we are passing parameter to onSuiteStart method , however in https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/src/index.js#L209 this line, the method does not accept any parameter. Should i remove the passing parameter?
Below is the screenshot of the error message i am getting:

![image](https://user-images.githubusercontent.com/45997477/94760686-dbbaf900-03c0-11eb-817b-10cdb72175fc.png)

**Comment by ablok** [comment]
@suniljaiswal01 just create a draft PR. Any outstanding issues can be discussed there.

**Comment by christian-bromann** [comment]
Closing, as we have already 2 PRs for this: #5909 and #5912
