### ISSUE TITLE
click() method unable to click on Specified xOffset or yOffset

### ISSUE THREAD

**Issue by hetsaliya** [webdriverio/webdriverio#5877]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.3
 - **NPM version:** 6.14.4
 - **Browser name and version:**  Chrome  85.0.4183.102
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**
```
     browserName: 'chrome',
     'goog:chromeOptions': {
        w3c: false,
}
```

**Describe the bug**
When Passing a value of ` x` and `y `parameter in `click()` method then it clicked on the middle of the element but not at the specified xoffset and yoffset.

**To Reproduce**
set the `w3c: false` in 'goog:chromeOptions' and pass  xoffset and yoffset parameter in `element.click({ x : xoffset, y : yoffset })` method.

**Expected behavior**
click at a specified xOffset and yOffset from the center of the element.

**Comment by christian-bromann** [comment]
I will close this due to inactivity. We recommend to use the W3C protocol for browser automation moving forward. It is hard to tell whether this is a problem in WebdriverIO not using the [moveToElement](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto) command correctly or a problem with the driver not properly running the command.
