### ISSUE TITLE
Sauce Service - set cacheId automatically

### ISSUE THREAD

**Issue by IevgenRagulin** [webdriverio/webdriverio#5908]
**Is your feature request related to a problem? Please describe.**
Sauce Labs supports setting cacheId property. It's pretty easy to set it if tests are running with a concurrency of 1, but managing cacheIds becomes tricky when we are running, say, 10 tests with a max concurrency of 3 (using maxInstances capability). 

**Describe the solution you'd like**
Add a boolean argument named autoSetCacheId in the config file. If this argument is set to true, reuse same 3 devices for those 10 tests with the help of cacheId.

**Describe alternatives you've considered**
- An alternative would be to not use maxInstances capability, and just run each test in a separate process (essentially having my own maxInstances implementation in bash)
- Implement this feature ourselves in our project. Something like: have an array of "released cacheIds". Whenever a new test starts, we can check if there is a cacheId available in that array. If there is, use it. If there isn't, generate a new one. 
 Whenever the test finishes, add the cacheId used in that test to that array.

**Comment by christian-bromann** [comment]
I think this makes totally sense. I am not much familiar with RDC testing. Would you be interested taking a stab at this. You should find all information on how to contribute in our [contribution guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md). I am also happy to support with any questions you have.

**Comment by wswebcreation** [comment]
@IevgenRagulin 

I'm looking into this and I was wondering what you exactly expect here. The `cacheId` can be a random string. The combination of real device capabilities and `cacheId` needs to be the same every time you start a new session after the previous one finished.
You could provide it to your framework capabilities as three unique strings (can be the same over different builds, as long as the capabilities + `cacheId` are not the same for 2 builds that start at the same time), what would be the advantage of the Sauce service to have this?

**Comment by IevgenRagulin** [comment]
@wswebcreation ,

it's been a while since I created this issue, and I'm off that project now, so forgive me if I don't remember some context.

As far a I remember, with appium/webdriverio a new session is started for each test file. What we would like to be able to do is to run those X sessions on Y devices, and it would be very helpful if webdriverio could set those cacheIds for us automatically, instead of us having to track which of the `cacheIds` has become available after each test has finished, and then telling the next session to use it. 

The motivation here - iff we can reuse the same X devices to run Y tests on them, tests would be faster (which means cheaper). We could implement this on our side, but it seemed like something others could take advantage of.

**Comment by wswebcreation** [comment]
Hi @IevgenRagulin 

Thanks for taking the time. Here are my answers and 2-cents

> As far a I remember, with appium/webdriverio a new session is started for each test file.
Correct

> instead of us having to track which of the cacheIds has become available after each test has finished, and then telling the next session to use it.
That's not what WDIO is doing. As long as you provide a `cacheId`, which can just be a fixed string (but needs to be different for each initial device you are calling) Sauce will give the same device to you. 
Here's an example

Imagine you have 10 specs,  set `maxInstances` to 3 and these are your capabilities
```js
capabilities: [
  {
     deviceName: 'iPhone 8',
     platformName: 'iOS'
     cacheId: 'ios-1'
  },
  {
     deviceName: 'iPhone XS',
     platformName: 'iOS'
     cacheId: 'ios-2'
  },
  {
     deviceName: 'iPhone SE2020',
     platformName: 'iOS'
     cacheId: 'ios-3'
  },
]
```

When for example spec 1 is done on the iPhone 8, then spec 4 will be started by WDIO and it request to be executed on the same iPhone 8 capability. Sauce will then determine if the exact same device will be reused when:
1. the new session is started within 10 seconds after the previous requested one
2. the capabilities are exactly the same 
3. the `cacheId` is the same as the previous requested on

Based on this I'm not seeing a reason for the Sauce Service to add this cap because this is already handled by Sauce if the `cacheId` is provided

**Comment by IevgenRagulin** [comment]
I see, thank you! Probably I had things set up wrong then. Closing the issue.
