### ISSUE TITLE
Consider removing fibers dependency

### ISSUE THREAD

**Issue by mjhenkes** [webdriverio/webdriverio#6292]
**Is your feature request related to a problem? Please describe.**
The WebdriverIO Sync package has a [dependency](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/package.json#L32) on [fibers](https://github.com/laverdet/node-fibers) version 4.0.1.

The fibers package versions seem to have a narrow range of node versions that they support and fails to install outside of those ranges (at least in my experience).

* Fibers 3.0 supports node 8-10
* Fibers 4.0 supports node 10-12
* Fibers 5.0 supports node 12-14

This is somewhat documented here: https://github.com/laverdet/node-fibers#supported-platforms

The dependency on the fibers package prevents projects that depend on wdio from being able to use the latest version of node.

Additionally node fibers has been updated with a note of obsolescence and 
>The author of this project recommends you avoid its use if possible.

**Describe the solution you'd like**
I know I'm minimizing the amount of work required, but removing the fibers dependency would decouple wdio from the node requirements of fibers and allow wdio to support a greater range of node versions.

**Describe alternatives you've considered**
To support node 14 without removing the fibers dependency would require another major version of wdio because (i think) it would require dropping node 10 support.

**Additional context**

Thanks for providing WDIO 😃

**Comment by christian-bromann** [comment]
@mjhenkes thanks for raising the issue. We will continue support Fibers for people that like to use the `@wdio/sync` packages because it enormously simplifies how tests are written with WebdriverIO. You are not forced to use it and to have Fibers as dependency. If you remove `@wdio/sync` from your dependency list and write WebdriverIO tests with `async/await` you do not depend on Fibers.

I am happy to continue the discussion this but users do not depend on Fibers when using WebdriverIO, only if they like to write their tests in a synchronous fashion for which Fibers is required.

**Comment by mjhenkes** [comment]
@christian-bromann Thanks for the information! I appreciate the response 😄
