### ISSUE TITLE
[Question / Help] Is there a way get the network requests from sauce services?

### ISSUE THREAD

**Issue by NareshMurthy** [webdriverio/webdriverio#6335]
I am using sauce-service to run android web browser tests on sauce labs virtual devices (emulator).
Is there a way i can intercept and read the network requests going out of the web page?
Thanks!

**Comment by wswebcreation** [comment]
Hi @NareshMurthy 

Currently Sauce Labs doesn't support this and if it would, it would be supported within Sauce Labs, not with the Sauce Service itself. 
I know there was an experiment with Android emulators and Chrome to provide the capability `extendedDebugging:true` to capture network traffic in a har file (which could be downloaded from the Metadata-tab, but I'm not sure if that went to production for all Android versions. You could check that.

Going to close it for now because it's not related to this service. If you need support for this feature, then please contact support from Sauce Labs
