### ISSUE TITLE
useCucumberStepReporter: true is giving warning of allure-js-commons: Unexpected endStep(). There are no any steps running

### ISSUE THREAD

**Issue by halukbaysal** [webdriverio/webdriverio#6523]
**Environment:**
 - **WebdriverIO version:** [7.0.7]
 - **Mode:** [WDIO Runner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [v12.18.3]
 - **NPM version:** [6.14.6]
 - **Browser name and version:** [Chrome 88.0.4324.192]
 - **Platform name and version:** [MacOS Catalina]
 - **Additional wdio packages used (if applicable):** [@wdio/allure-reporter, @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/browserstack-service, @wdio/cucumber-framework, @wdio/devtools-service, @wdio/spec-reporter, @wdio/local-runner]
 
**Describe the bug**
If `useCucumberStepReporter: true` is set in the reporter, allure is giving the warning of `allure-js-commons: Unexpected endStep(). There are no any steps running`

**Comment by christian-bromann** [comment]
@halukbaysal can you provide a minimal project that reproduces this problem?

**Comment by halukbaysal** [comment]
Our project is internal so I can't share but I will try to create a similar framework

**Comment by halukbaysal** [comment]
@christian-bromann I have created a high-level framework which is similar to what we are using in the project. 

Could you please check https://github.com/halukbaysal/wdio_v7 

when you run the `test` script you will see the error. If you remove `useCucumberStepReporter`, the warning disappears but the report is not showing as expected.

**Comment by christian-bromann** [comment]
@halukbaysal thanks for providing the reproducible example. I am not sure when I will be able to pick this up but if anyone else want to have a look, feedback and suggestions are welcome!

**Comment by halukbaysal** [comment]
@christian-bromann Thank you. I will also look for a solution.

**Comment by staizen-alexm** [comment]
@christian-bromann, i tried whacking on this. i couldn't find exactly why (im guessing because of async mode and/or webdriver steps reporting) but there are instances when `endStep` is being called on a `suite` that doesn't have a proper `Step` instance. 

This looks to be the cause of that seemingly harmless warning.

e.g.
![image](https://user-images.githubusercontent.com/81152923/127644132-6de590ba-c108-4754-a6e9-142c42e4ca90.png)

vs

![image](https://user-images.githubusercontent.com/81152923/127644223-48f37d59-5f4c-4c02-b540-63cf28738d89.png)

i noticed that there are already type/instance guards for `currentStep` scattered on the `AllureReporter` class so i figured just adding it on a couple more methods.

I raised https://github.com/webdriverio/webdriverio/pull/7208 for review.

PS - 
I didn't try various cases but I'm not getting said issue on `sync` mode or when setting the `disableWebdriverStepsReporting` option to true.

**Comment by christian-bromann** [comment]
@staizen-alexm thanks a lot for picking this up. Great find! Let's continue our conversation in #7208
