### ISSUE TITLE
Make `scrollIntoView` possible for mobile

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6537]
It seems that within mobile `isDisplayed` returns false if the element is not within viewport.

@wswebcreation can you confirm this?

~Therefor it would be useful to integrate the `checkIfDisplayedWithScrollDown` into `isDisplayed`. I suggest the following interface:~

~- `isDisplayed(opts: isDisplayedOpts): boolean`~
~- where `isDisplayedOpts = { maxScrolls: number, amount: number }`~
~- both `isDisplayedOpts` properties should default to `0`~
~- docs should clarify that these are only relevant for mobile environments~

Let's enhance the `scrollIntoView` command to also support mobile environments and using the swipe functionality from #6536 and swipe until the element is within the view.

**Comment by wswebcreation** [comment]
@christian-bromann 

> It seems that within mobile isDisplayed returns false if the element is not within viewport.

Correct

> Therefor it would be useful to integrate the checkIfDisplayedWithScrollDown into isDisplayed

I would say no, and would suggest to integrate this into https://webdriver.io/docs/api/element/scrollIntoView/. Imho isDisplayed should reflect what it describes, check if it's displayed, not scroll.

**Comment by christian-bromann** [comment]
Makes absolutely sense, `scrollIntoView` currently is only supported for web environments and this could make it cross platform compatible. Will update the issue.

**Comment by jayandran-Sampath** [comment]
With current version of appium

its kind of straight forward to implement scrolltoview for android which uses UiAutomator as automation framework (http://appium.io/docs/en/writing-running-appium/tutorial/swipe/android-simple/) Since UiAutomator provide that feature by default

But for Android using Espresso framework & IOS -> it needs some amount of changes in Appium side to support this solution

**Comment by diego-epicura** [comment]
Bump.
Meanwhile the only working workaround I found is

`await driver.touchAction([{ action: 'longPress', x: 30, y: 500 }, { action: 'moveTo', x: 20, y: 100 }, 'release'])`

**Comment by christian-bromann** [comment]
#9344 implements support for mobile for now, but it would be great to have native mobile support as well (using Appium's swipe command or other native supported interactions).

**Comment by christian-bromann** [comment]
Implemented in #13870

**Comment by kirksl** [comment]
@christian-bromann Greatly appreciate you adding this for native mobile.  It would be nice if any command targeting an element could opt-in to this scroll into view mechanism (as opposed to having to explicitly call this).  That would really level the playing field with how this is done automatically in desktop web.

**Comment by christian-bromann** [comment]
> That would really level the playing field with how this is done automatically in desktop web.

The problem with that is that in desktop web, doing a scrollIntoView operation is relatively cheap and fast. In mobile it requires much more commands and time, e.g. in iOS we may have to do multiple swipes up and down to find the element within the view. I agree though that this could be something configurable in WebdriverIO. Mind raising an issue for it?

cc @wswebcreation

**Comment by kirksl** [comment]
Done
https://github.com/webdriverio/webdriverio/issues/14283

Agreed on cost.  I think there should definitely be a mechanism to opt-in so that users can control scrolling expense.

**Comment by wswebcreation** [comment]
I like the idea, but let me share my 2‍-cents here

**Costs:**
The costs would be very high without knowing the context as a user. When comparing the HTML source vs. Appium source for HTML, only **one** call to `elem.scrollIntoView()` is sufficient, no matter where the element is (top or bottom) on the page. 
I realize that these costs are also there if you manually add the `element.scrollIntoView()` command before the action, so this might not be a valid argument if we make this very clear to the users when they only use the action and it automatically scrolls.

**Source:**
The Appium source is different, 
- iOS **might** have all elements in the source, even if you don't see them, 
- Android will **only have the elements in the source that are in the view.** 

Taking the above into consideration and also thinking about the fact that there is no "similar" Appium `scrollIntoView()` method that would find elements no matter where they are located makes this very complex, and a lot of logic needs to be built to automatically scroll to the element. Assuming the default "swipe up" (to "scroll down") is not always accurate because, from an automation perspective, we do not always know where we are on the screen. 

**Arguments overkill per action**
Having said that, the logic is already in the mobile-`scrollIntoView` method. If we add this to "all" element interactions, all actions will be "bloated" with all options like `direction|maxScrolls|scrollableElement|percent`. Not sure if we want that


If we agree that this is not an issue, then I'm happy to implement it.
