### ISSUE TITLE
document how to set browser profiles

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#654]
Explain how to use:

- chromeoptions (see https://sites.google.com/a/chromium.org/chromedriver/capabilities)
- firefox options (see #240)
- and other

**Comment by stoffeastrom** [comment]
@christian-bromann  

FYI: Tried using a firefox profile in the `wdio.conf.js` and the only way I got it working was
```
capabilities: [{
  browserName: "firefox",
  firefox_profile: "your base64 encoded firefox profile"
}]
```
Since using the `firefox-profile` `encoded` method is async I couldn't use it any proper hook where it is possible to set it dynamically. The `capabilities` seems to be detached and not configurable in any of the existing hooks.

**Comment by christian-bromann** [comment]
@stoffeastrom I see, thanks for the info. Maybe in makes sense to add that project as a dependency then. The advantage would be that we can make it pretty easy for the user to make firefox profiles with WebdriverIO. On the downside it is something that should be encapsulated since it is not really within the scope of WebdriverIO.

**Comment by christian-bromann** [comment]
We now have a service to create firefox profiles within the wdio config file. Something similar will be published soon for chrome. With that this issue got obsolete
