### ISSUE TITLE
@wdio/cli jest tests give surprising results and pass

### ISSUE THREAD

**Issue by RossVertizan** [webdriverio/webdriverio#6593]
**Environment (please complete the following information):**
 - **WebdriverIO version:** Latest version pulled from github
 - **Mode:** Running Jest tests
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.2
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 88
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** None

**Config of WebdriverIO**
webdriverio/packages/wdio-cli/tests/__fixtures__/wdio.conf.js

**Describe the bug**
When running the Jest test watcher.test.ts -> watcher -> should initialise properly, it references the config file:
```webdriverio/packages/wdio-cli/tests/__fixtures__/wdio.conf.js```

The config file has the specs line:
```specs: [path.join(TEST_ROOT, '*.js')],```
where TEST_ROOT points to the guineapig directory, which contains test1.js, test2.js and test3.js.  So this spec line will expand to: 
```
['__dirname/guineapig/test1.js',
'__dirname/guineapig/test2.js',
'__dirname/guineapig/test3.js']
```

The exclude line is:
```
exclude: [
        path.join(TEST_ROOT, 'test2.js')
    ],
```
when this is applied to the above, it should result in the following (i.e. test2.js removed):
```
['__dirname/guineapig/test1.js',
'__dirname/guineapig/test3.js']
```

However, in the Jest test watcher.test.ts -> watcher -> should initialise properly:
```
describe('watcher', () => {
    it('should initialise properly', async () => {
        const wdioConf = path.join(__dirname, '__fixtures__', 'wdio.conf')
        const watcher = new Watcher(wdioConf, {})
        expect(watcher['_specs']).toEqual([
            './tests/test1.js',
            './tests/test2.js'
        ])
    })
```
The golden result in the test is:
```
['./tests/test1.js',
'./tests/test2.js']
```
... and this test passes.  Not only is test2 included, but also the path is completely different to the expected.

Changing the conf file has no effect.

It is not clear to me what this is testing and where the result comes from.  I accept this may be my ignorance of the testing framework, but it sure does look strange.

**To Reproduce**
Simple run the Jest test: watcher.test.ts -> watcher -> should initialise properly

**Expected behavior**
I expected the result to be (something like):
```
['__dirname/guineapig/test1.js',
'__dirname/guineapig/test3.js']
```

**Comment by christian-bromann** [comment]
I looked into this and even though it seems weird it behaves as expected. Note that we try to keep dependencies across sub packages to a minimum. If writing tests for a file it often makes sense to mock classes and functions from other modules so that tests can run independent from them. In this case the Launcher class was mocked [within the test file](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/tests/watcher.test.ts#L9-L37) as well as the config parse which was mocked by the [`@wdio/config`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/tests/__mocks__/@wdio/config.ts#L7-L30) package itself.
