### ISSUE TITLE
Incorrect typing for browser.call

### ISSUE THREAD

**Issue by giacomomagini** [webdriverio/webdriverio#6622]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 7.2.3
 - **Mode: standalone
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: 14.15.1
 - **NPM version: 6.14.8
 - **Browser name and version:
 - **Platform name and version: MacOS Catalina

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Typing for `browser.call` doesn't seem correct
![image](https://user-images.githubusercontent.com/16667545/112338724-50f7ee80-8cbf-11eb-98c2-f7549efbb2f9.png)

**To Reproduce**

Follow the typescript setup.
I use VScode and `typescript 4.0.5`.

**Expected behavior**
The return type of `call` is the return type of the function passed as argument.

**Comment by christian-bromann** [comment]
This works for the async types, e.g.:

![Screenshot 2021-03-25 at 12 04 53](https://user-images.githubusercontent.com/731337/112463388-7427aa00-8d62-11eb-83c6-726705e3420f.png)

but since we transform the sync types from the async types all generics get lost. The solution to this is to overwrite the derived types here: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts#L15-L26

Any contributions would be appreciated.

**Comment by giacomomagini** [comment]
Hi @christian-bromann, I'll try open a PR in the next days. Thanks for confirming the issue and pointing out the relevant code!

**Comment by giacomomagini** [comment]
Opened a PR https://github.com/webdriverio/webdriverio/pull/6625

**Comment by christian-bromann** [comment]
Let's continue conversation in #6625
