### ISSUE TITLE
clickWhenEnabled troubles

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#663]
I have this helper command:

```coffee
    clickWhenEnabled: (selector, cb) ->
      client
        .waitForEnabled(selector)
        .click(selector, cb)
```

but it doesn't work very well. Sometimes the click never occurs. Probably because it waits until it gets enabled but it is already enabled or so? No idea if the above can be improved? Just want to click on the button when already enabled or wait until it gets enabled. Should cover both scenarios.

Thanks for your advice!

**Comment by christian-bromann** [comment]
I would first recommend to get rid of callbacks. v3 supports but should better be used with promises. So why not doing this:

```js
client.addCommand('clickWhenEnabled', function(selector, timeout) {
    return this.waitForEnabled(selector, timeout).click(selector);
});
```

> Sometimes the click never occurs

Maybe because the selector does not exist and since you can't call the cb function in your example above this function stales the queue forever. Therefor it is better to use promises.

> Should cover both scenarios.

No actually your example should work.

You could also try to increase the timeout of the waitfor command

**Comment by binarykitchen** [comment]
wonderful, this helped a lot - problem solved here
