### ISSUE TITLE
Output thrown exceptions in command callbacks

### ISSUE THREAD

**Issue by Demango** [webdriverio/webdriverio#664]
I would propose thrown exceptions to be output in the callback as a parameter, currently the catching behaviour requires something like this:
```javascript
client.isExisting(selector)
    .catch(function(err){
        //handle
    })
    .then(function(exists) {
        cb(exists);
    });
```
, which can make it awkward to properly detect if an exception has been thrown, and make you return a callback as finished, when it has in fact failed and thrown an exception.

I suppose this would be more desirable, since you could just check if an exception has occurred easily:
```javascript
client.isExisting(selector)
    .then(function(exists, err) {
        if(err) {
            //handle
        }
        cb(exists);
    });
```

Or am I missing some obvious existing behaviour?

**Comment by christian-bromann** [comment]
> Or am I missing some obvious existing behaviour?

Yes :wink: .. then functions can take two functions: one if the promise got fulfilled and one if it gets rejected. I am assuming that your callback should return with true or false depending on whether or not the selector is existing. Do it this way:

```js
client.isExisting(cb, cb.bind(null, false));
```

Actually I don't see why isExisting should throw an error but this is also useful for other commands. Also, I would recommend to make use of promises instead of using callbacks.

**Comment by Demango** [comment]
Cheers for that, I did see it in the Q documentation, but didn't put two and two together, I suppose.
