### ISSUE TITLE
[webdriverio/(sync|async)] typescript approach recommendation with typeRoots

### ISSUE THREAD

**Issue by FrederickEngelhardt** [webdriverio/webdriverio#6649]
# Description
Using typescript I am unable to get type resolution for `driver` or `$` or `$$`. These types come from `webdriverio/sync`. 

According to the [documentation](https://webdriver.io/docs/typescript/), all @wdio and webdriverio packages require you to manually import all of your typescript types. 

The `types` approach requires you to have to manually import all your other types from other packages which does not makes sense time wise on large projects.

This is not the only option. We can import things like this.

```
   "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types", // works
      "./node_modules/webdriverio/sync", // does not work
      "./node_modules/@wdio/appium-service", // works
    ]
  },
```

With this approach all of the `@types` and other libraries specified have their typing resolve if their typeRoots are not orphaned from the package.json.

It looks like `webdriverio/sync.d.ts` and `webdriverio/sync.d.ts` are orphaned from the package.json because they override specific declarations from the `index.d.ts`.

**Describe the solution you'd like**
1. Combine the types that collide so that they all can be exported together under the webdriverio library
2. Use enums (or something) to specify which type is meant for what
3. Update the recommended documentation to showing typeRoots and an alternative

**Describe alternatives you've considered**
Alternative solution
1.  Update the documentation on how to use typeRoots instead of types and requiring manual resolution for each npm package with types you have.
2. For webdriverio/sync document the workaround below

1. Create a index.d.ts file in your directory
2. Make sure the index.d.ts file is under an included or typeRoots folder.
2. Import the `webdriver/sync` into that index.d.ts declaration file (ignore the module error)

index.d.ts
```
// @ts-ignore
import('webdriverio/sync');
```

Your types will resolve.

**Alternatively 2**
Make an `@types/webdriverio/sync` and `@types/webdriverio/async` and publish those packages to that repo.

**Comment by erwinheitzman** [comment]
From what I understand this is happening because this setting is to be used when there's no .d.ts files directly in the root of the non package (which is where the compiler looks for these files by default). The typeRoots allows you to specify a different root which fixes this issue. However the way you use it seems like it's not the way that it is meant to be used.

This is based on the documentation and information that I have read about this option.

**Comment by christian-bromann** [comment]
> The `types` approach requires you to have to manually import all your other types from other packages which does not makes sense time wise on large projects.

I believe the maintenance effort to add a wdio package to the `types` list fairly reasonable for smaller as well as for large projects. Can you elaborate why you think it doesn't make sense?

> With this approach all of the `@types` and other libraries specified have their typing resolve if their typeRoots are not orphaned from the package.json.

What is the advantage of using `typeRoots` over `types`? It seems you still have to add the paths for individual packages too.

> 1. Combine the types that collide so that they all can be exported together under the webdriverio library

We need to type some globals, e.g. `driver`, `browser`, `$` and `$$` to work either with a synchronous setup or asynchronous one based on whether the user is using `@wdio/sync`. We can't export both types within one package which is why we ask users to either add `webdriverio/sync` or `webdriverio/async` to their types list.

Overall I don't believe using `typeRoots` has any advantages over the current approach. Can you please elaborate on your points? Maybe I am missing something.

**Comment by christian-bromann** [comment]
ping @FrederickEngelhardt

**Comment by FrederickEngelhardt** [comment]
@christian-bromann 

🤦 looks like this approach does not make a difference at least for me since I have only 3 different global scope types I'm using. 

Following typescript  documentation, **"types"** does not override basic `node_modules/@types` imports. Utilizing **"typeRoots"** would be the same thing.

> I believe the maintenance effort to add a wdio package to the types list fairly reasonable for smaller as well as for large projects. Can you elaborate why you think it doesn't make sense?

Use case would be for devs with projects that have maybe 20+ (different packages) that have global scope types which are being used within their app. This way the devs don't have figure out each global dependencies they need to pull in to get type completion working properly for webdriverio.

> What is the advantage of using typeRoots over types? It seems you still have to add the paths for individual packages too.

Looks like there's none here.
