### ISSUE TITLE
Can't change window size for the multiremote mode

### ISSUE THREAD

**Issue by kongory** [webdriverio/webdriverio#6760]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.16.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**

**Describe the bug**
 Can't change sizes of multiremote instances in test.

**To Reproduce**
Have such configuring in the 'it':
```
const browser = await multiremote({
      userA: {
        capabilities: {
          browserName: "chrome",
          chromeOptions: {
            args: ['window-size=1920,1080']
        }
        },
      },
      userB: {
        capabilities: {
          browserName: "chrome",
          chromeOptions: {
            args: ['window-size=1920,1080']
        }
        },
      },
    });
```
When I use
`await browser["userA"].setWindowSize(1920, 1080);`
have an error: _"Cannot assign to read only property '_NOT_FIBER' of object '#<MultiRemoteDriver>'"_, but with
```
await browser["userA"].setWindowSize(1920, 1080);
await browser["userB"].setWindowSize(1920, 1080);
```
nothing happens.

**Expected behavior**
Sizes are changed.

**Log**
[Logs](https://gist.github.com/kongory/9af17a86ad2c08df5dd8a15a51a00bc5.js)

**Comment by christian-bromann** [comment]
It seems that when calling the `setWindowSize` we loose the scope of the browser instance. This error likely happens somewhere where we [attach the browser to the main instance](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/multiremote.ts#L55). Any contributions on this would be appreciated.

**Comment by elaichenkov** [comment]
Hey @kongory 

Can you please provide a fully reproducible example and logs?

**Comment by christian-bromann** [comment]
@elaichenkov using the [multiremote example](https://github.com/webdriverio/webdriverio/tree/main/examples/wdio/multiremote) allowed me to reproduce it by replacing everything with:
```js
describe('multiremote example', () => {
    it('should open chat application', () => {
        browser.url('https://socketio-chat-h9jt.herokuapp.com/')
        browser["browserA"].setWindowSize(1920, 1080)
        browser.pause(5000)
    })
})
```

**Comment by elaichenkov** [comment]
Hi @christian-bromann 
Thanks for your reply.

In this case, the error occurs not on the `browser["browserA"].setWindowSize(1920, 1080)` step, it happens on the `browser.url('https://socketio-chat-h9jt.herokuapp.com/')` step and we will see this error every time when we are trying to use `browser` without specifying exact browser, in this case, it's `browserA`.
So, I believe that problem is [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/multiremote.ts#L40). 
We don't have the `writable` property, hence the property may not be changed with an assignment operator and that's what we can see in the error.
I've created a [PR](https://github.com/webdriverio/webdriverio/pull/6761), please take a look. Moreover, I need help, because I'm not sure which kind of tests should be updated.

**Comment by christian-bromann** [comment]
Thanks @elaichenkov , let's continue our convo there.
