### ISSUE TITLE
selendroid doesn't like loggingPrefs

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#684]
The Selendroid driver that Saucelabs is currently using doesn't appear to support any loggingPrefs being passed. Even with an empty object, it generates this error:

```
io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
SEVERE: Error occurred while starting Selendroid session
java.lang.ClassCastException: org.json.JSONObject cannot be cast to org.openqa.selenium.logging.LoggingPreferences
```

Unfortunately, with this change there is no way to exclude loggingPrefs from being sent, since the deepMerge is smashing the object back onto capabilities.

**Comment by toddhgardner** [comment]
Address in https://github.com/webdriverio/webdriverio/pull/709

**Comment by christian-bromann** [comment]
Fixed and published with `v3.2.0`

**Comment by stantaylor** [comment]
I'm getting the same problem with selendroid and SauceLabs (only  with browser tests on Android devices). The problem seems to be that if the keyword 'loggingPrefs' is in the desired capabilities, regardless of the values, selendroid chokes on it. I tried adding "loggingPrefs": {} and "loggingPrefs": "" to my specified desired capabilities, and it still choked. For now--in order to get my tests to run--my only option is to fork webdriverio and remove the code that sets loggingPrefs. Not sure what the long term solution should be.

**Comment by Ranatchai** [comment]
@stantaylor I had the same problem, and your solution is the only one that work.

thank you very much
