### ISSUE TITLE
Forced chaining in v3 for async

### ISSUE THREAD

**Issue by bonjonbovi87** [webdriverio/webdriverio#694]
I've built a lot of code up around referencing the same client object from different files/objects, and as a result, chaining every single command is not doable without an extreme overhaul in my code base.

This used to work fine, but now with the integration of Q and promises, it will print in the "incorrect" order.  
```javascript
driver.pause(2000, function(){ console.log(" I will execute first "); });
driver.pause(1000, function(){ console.log(" I will execute second "); });
```

A good example is the `webdriverio.addCommand.js` script which no longer works, as it calls `.end();` before anything in the addCommand can get kicked off in the `searchGoogle()` function.  Yes there are examples on how to 'convert' to the new style, but dong this to hundreds of functions is not viable.

I understand the change and the perks that come along with v3, but unless there's a update planned that will have better backwards compatibility, I think I'm going to have to stay on v2 :disappointed:

**Comment by christian-bromann** [comment]
Sorry for the inconvenience. Moving to a promise based chaining system was the right way to go even though it requires to rewrite tests. Maybe it is easier for you if you use the new wdio runner and make use of yield, so this

```js
yield driver.pause(2000, function(){ console.log(" I will execute first "); });
yield driver.pause(1000, function(){ console.log(" I will execute second "); });
```

would work as expected. I noted your comment. Please bare with our decision to move forward in order to take advantage of all the "new" features we've got in node and iojs. Btw: I am fiddling around with the fibers package in order to bring the old synchronous behaviour back. If everything works out as expected developer will be able to chose their way of handling async with WebdriverIO
