### ISSUE TITLE
Ability to fail from hooks

### ISSUE THREAD

**Issue by mkrakker** [webdriverio/webdriverio#7032]
**Is your feature request related to a problem? Please describe.**
Exceptions thrown in hooks have no effect on the test execution (except for onPrepare and onComplete), however it'd be probably useful to have the ability to fail a scenario from a before/after hook.
Example usecase: I'd like to fail from an afterScenario hook should any console errors been registered in the browser. For this I'd need a hook per scenario and with the browser context still available - therefore onComplete is not sufficient. Any exceptions thrown in these hooks are being logged to the console, however they are not failing the tests.

**Describe the solution you'd like**
I understand that modifying the default behaviour of the hooks and breaking the test lifecycle is probably not acceptable, however extending [Service Error Handling](https://webdriver.io/docs/customservices#service-error-handling) to be applicable to other hooks (or Service Workers) might be feasible I hope...
Handling `SevereServiceError`s thrown in hooks similarly to what’s described for setup and teardown while swallowing all others like now would be my proposal.

**Additional context**
This can be traced back to https://github.com/webdriverio/webdriverio/blob/8e7a78c83e7a684694b2a8779d9a8b1e10efee5d/packages/wdio-utils/src/shim.ts#L14 where all exceptions / promise rejections thrown by the hooks are being swallowed if I'm not mistaken.

**Comment by christian-bromann** [comment]
> Example usecase: I'd like to fail from an afterScenario hook should any console errors been registered in the browser. For this I'd need a hook per scenario and with the browser context still available - therefore onComplete is not sufficien

You can do that by using Cucumber hooks. These should cause your test to fail.

Please validate this approach first before we are looking into modifying existing hook behavior. Happy to re-open then.

**Comment by RossVertizan** [comment]
I am developing a service and I am detecting a fatal problem during the beforeSession hook and I can't detect it earlier e.g. in one of the launcher hooks.  I  am throwing a ```SevereServiceError``` as described in the [Service Error Handling](https://webdriver.io/docs/customservices/#service-error-handling) section, with the expectation that this would stop anything further from happening, so I can stop neatly at the point where the error occurred.

However, this is not what happens.  The error is thrown, but everything continues as before, the browser is launched etc. , but then in my case hangs because of the issue I already detected and has to be killed with a Ctrl-C.

I notice the example shows it in use in an onPrepare hook, which is a launcher hook and not a worker hook.  I have tested it in the onPrepare hook and indeed it stops the runner.  

So:
1. Is there a different error I need to run in worker hooks that has the same effect?
OR
2. Do I need to look after stopping the session myself, in which case how would I set about doing that?

If this question does not belong here, I am happy to move it to a new issue, but I felt it was close enough to keep them connected.

**Comment by christian-bromann** [comment]
> 1. Is there a different error I need to run in worker hooks that has the same effect?

No. By design WebdriverIO hooks don't interfere with the test process.

> 2\. Do I need to look after stopping the session myself, in which case how would I set about doing that?

You can try to end the session manually or call `process.kill(1)`

> and I can't detect it earlier

Why is it not possible to detect it earlier?

**Comment by RossVertizan** [comment]
I can't detect it earlier because I am checking if I have successfully connected to a cloud service and this necessarily is done at the worker instance level.

**Comment by RossVertizan** [comment]
@christian-bromann thanks for the other answers, this is clear.
