### ISSUE TITLE
Protocol Documentation regarding webdriver findelement, getactive element etc are unclear

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7113]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

Webdriver protocol methods like findELement ([link](https://webdriver.io/docs/api/webdriver/#findelement)) , Findelements etc returns element reference than actual wdio element. so user is not able to understand what to do next with the element reference. Non of the wdio element methods works as the returned item is just a object

**Suggested improvement**

![image](https://user-images.githubusercontent.com/45095911/125037995-c334e900-e08c-11eb-82d6-2b88298e53b5.png)

**Comment by christian-bromann** [comment]
@praveendvd I agree with you that they could use more information on how to actually get WDIO elements from them. I suggest to update the protocol docs in `@wdio/protocols`. You can also add code examples, e.g. this [command](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/protocols/saucelabs.json#L7-L44). A bunch of protocol commands like this are semi useful and WebdriverIO provides an enhanced implementation of it, e.g. `findElement` vs. `$`. We want users to use WebdriverIO implementations given they come with a lot of additional features and safe guards, which is why these protocol commands don't have that much of a popular appearance.

**Comment by praveendvd** [comment]
@christian-bromann  will take up in a week if its still open

**Comment by praveendvd** [comment]
@christian-bromann  Could you help me in this one , is there a way to add info to the protocol documentation , i am not able to figure out how to do . Thanks in advance . 

If info is not required i can add :

![image](https://user-images.githubusercontent.com/45095911/134790537-c2051c79-49cd-4ed2-a205-7e71d6666416.png)

is this enough

**Comment by christian-bromann** [comment]
Yes, this is totally enough. Let's continue convo in #7472
