### ISSUE TITLE
@wdio/config:ConfigParser: Failed loading configuration file: C:\*******\config\suite.local.js: Unexpected token '.'

### ISSUE THREAD

**Issue by rige24** [webdriverio/webdriverio#7139]
Hi,

I've upgraded from @wdio/cli version 6.X to 7.7.5. Since this, I got the following error message, during test execution:
```
@wdio/config:ConfigParser: Failed loading configuration file: C:\*******\config\suite.local.js: Unexpected token '.'

C:\*******\node_modules\wdio-cucumberjs-json-reporter\dist\reporter.js:112
        const keyword = stepData?.keyword
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
```

suite.local.js looks like
```
const merge = require("deepmerge");
const wdioConf = require("./suite.js");

exports.config = merge(wdioConf.config, {
  backendPort: 3002,
  filesToWatch: [
  ],
  logLevel: "info",
}
```

I've the following set up
```
    "@wdio/cli": "~7.7.5",
    "@wdio/cucumber-framework": "~7.7.5",
    "@wdio/junit-reporter": "~7.7.5",
    "@wdio/local-runner": "~7.7.5",
    "@wdio/spec-reporter": "~7.7.5",
    "@wdio/sync": "~7.7.5",
    "cucumber-html-reporter": "~5.4.0",
    "wdio-cucumberjs-json-reporter": "~4.0.0"

Node version is 12.19
```

If I remove the **const wdioConf = require("./suite.js");** line at suite.local.js all is working fine, but I need a multiple environment.

Is that a bug or have I done a mistake?

Best regards!

**Comment by christian-bromann** [comment]
Which Node.js version are you using?

**Comment by christian-bromann** [comment]
See above issue. Any contributions are appreciated.

**Comment by omkar220** [comment]
got this error  while executing test case  in node v-18.13.0   

ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/Users/HP/Desktop/projectdemotp/wdio.conf.ts: Unexpected token 'export'
C:\Users\HP\Desktop\projectdemotp\wdio.conf.ts:1
export const config = {

**Comment by 7999** [comment]
> got this error while executing test case in node v-18.13.0
> 
> ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/Users/HP/Desktop/projectdemotp/wdio.conf.ts: Unexpected token 'export' C:\Users\HP\Desktop\projectdemotp\wdio.conf.ts:1 export const config = {

same issue in node -v16.15.0

**Comment by christian-bromann** [comment]
This issue is resolved, if you still experience it you likely don't have the correct TypeScript setup. I recommend start a fresh WebdriverIO project via `npm init wdio@latest ./test` and check the setup used there.

**Comment by coyr** [comment]
I am getting a similar message in mac

```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/user/vue-forge-episode-4/wdio.conf.ts: Unexpected token 'export'
/Users/user/vue-forge-episode-4/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module.m._compile (/Users/user/vue-forge-episode-4/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/vue-forge-episode-4/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by christian-bromann** [comment]
> I am getting a similar message in mac

Please set `"type": "module"` in your package.json to make your project use ESM.

**Comment by iqbalpa** [comment]
> > I am getting a similar message in mac
> 
> Please set `"type": "module"` in your package.json to make your project use ESM.

this works for me, thank you

**Comment by parvkhanna** [comment]
The error you're encountering suggests that the wdio.conf.js file is being treated as an ES Module, but the require() function used in the WebDriverIO codebase doesn't support ES Modules. This can happen if the wdio.conf.js file is written using ES module syntax (like import/export statements) instead of CommonJS syntax (like require/module.exports).

Steps to Resolve the Error:
Check the wdio.conf.js File:

Make sure your wdio.conf.js file uses CommonJS syntax. For example:


*****CommonJS syntax*******
exports.config = {
  // Your WebDriverIO config settings
};
---------------------------------------------------------------------------------------------------------------------

If you specifically want to use ES modules (import/export syntax), you need to ensure that Node.js is set up to handle them. To do this, rename your configuration file to wdio.conf.mjs and use the following syntax:
javascript


**** ES Module syntax********

export const config = {
  // Your WebDriverIO config settings
};
Additionally, ensure your package.json has "type": "module" set if you're working with ES modules across your project.
