### ISSUE TITLE
pseudo element finding and clicking on mobile browser

### ISSUE THREAD

**Issue by RollerIn** [webdriverio/webdriverio#7373]
Hello,

I have spent lot of time to get solution by browsing across different sources but did not get any solution .

our application having left and right arrow buttons to turn pages left to right and vice versa , these buttons will be displayed only when we focus on them
source of html:
![image](https://user-images.githubusercontent.com/17290705/131682965-80503b40-56e1-4f7e-b309-d2bbe4d59127.png)
![image](https://user-images.githubusercontent.com/17290705/131683102-93c1ad23-f519-48a9-a8ef-c97a765987db.png)
![image](https://user-images.githubusercontent.com/17290705/131683143-9b0d1080-2953-4aa3-ab06-7f4ed3a73283.png)

can someone help me ,how can I handle these elment using WebdriverIO?

tried different approaches but didn't work 
one of the approach
const arrows=await $$('.navigationArrow__icon hidden');
      console.log('rightArrow length;'+arrows.length)

      rightArrow=arrows[1]
      const rightExit=await $(rightArrow).isDisplayed()
      console.log("right exist:"+rightExit); 

      if(rightExit){
        $(rightArrow).moveTo()
        $(rightArrow).click()
      }else{
        console.log('right arrow did not exist ')
      }

**Comment by christian-bromann** [comment]
A reproducible example would be helpful, otherwise I can only make suggestions. Maybe a little pause is necessary between moveTo and click to make this work.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you need further assistance.
