### ISSUE TITLE
Support waitForAngular

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#7400]
Hi team!

In the https://github.com/angular/protractor/issues/5502, @kyliau proposed for the `waitForAngular` to become an independent library that test frameworks could use to synchronise with Angular-based apps.
An example implementation is available at https://github.com/kyliau/angular-wait/blob/main/server/server.ts

Perhaps this functionality could be introduced as a WebdriverIO service? Or do you think that frameworks based on WebdriverIO, such as Serenity/JS, should implement it themselves?

Having it as part of WebdriverIO would allow folks for easier migration from Protractor, having it in a higher-level framework would allow for the functionality to be toggled dynamically.

Thoughts?

**Comment by christian-bromann** [comment]
Hey Jan,

I think we both chatted with @kyliau who afaik mentioned that Angular apps don't have anything special compared to other frameworks, that would need attention. For example if you open an Angular app today and fetch an element to click on it, WebdriverIO would automatically wait for that element to appear. If you do other, non element related things, like `performAction`, I believe it makes more sense to wait for an element to appear rather than using `waitForAngular`.

So in my opinion there is no need to implement `waitForAngular` at all.

**Comment by StanislavKharchenko** [comment]
@christian-bromann Unfortunately no. Even if you wait until element present on page it could not be intractable, or nothing will be if you click on element until it was completely rendered by Angular. 
Thats why this feature was implemented in Protractor, and that's why Protractor doesn't use simple like "waitForPresence" because for Angular this make tests unstable.

BTW @kyliau no longer works on Angular.

**Comment by christian-bromann** [comment]
@StanislavKharchenko understand. Can you think of an example app where I can test this?

Also if I remember correctly @kyliau said that the framework stabilizer that `waitForAngular` uses is not supported in the newer framework versions anymore. Is that correct?

**Comment by BorisOsipov** [comment]
@christian-bromann angular has build-in features https://angular.io/api/core/Testability that protractor uses.
But it sometimes doesn't work and sometimes requires chagnes in application under test.

A nuance that angular test abilities are not available in production build - that makes them useless for testing in staging\production like environments.

**Comment by StanislavKharchenko** [comment]
@christian-bromann I think https://angular.io is a simple example with latest angular v12 is ok.
I don't know what @kyliau meant but waitForAngular feature works in the latest v12 and yes, it was provided by Angular core functionality.
The actual Protractor implementation is here:
https://github.com/angular/protractor/blob/master/lib/browser.ts#L514

**Comment by StanislavKharchenko** [comment]
@BorisOsipov window.getAllAngularTestabilities(), whenStable and all related are available in prod mode.

**Comment by BorisOsipov** [comment]
@StanislavKharchenko seems true. thank you

**Comment by kyliau** [comment]
Chiming in since I've been tagged multiple times 😛 cc my coworker Doug @dgp1130 who's now in charge of Protractor.

`waitForAngular()` should be implemented as a standalone library, because it does not require any special instructions / APIs from the testing framework. It taps into the Testability module provided by Angular core. 
As shown in the [example](https://github.com/kyliau/angular-wait/blob/5052a542209b89830df85492f3ef49e563ee7433/server/server.ts#L39) I created, as long as you can execute a script snippet in the browser, you can "wait" for the application to become stable in your tests.

> Angular apps don't have anything special compared to other frameworks, that would need attention.

What I meant here is that _going forward_, Angular users should reduce the reliance on `waitForAngular()` and instead write the tests as if they have no knowledge of the framework. In practice this means waiting for a particular condition to occur to determine if the app is stable using the wait primitives provided by the testing platform.

While it is nice to know exactly when the application becomes stable via `waitForAngular()`, it is better to test the application like an end user - perform an action, wait for a condition to become true, then proceed with the assertions.

**Comment by christian-bromann** [comment]
> Even if you wait until element present on page it could not be intractable, or nothing will be if you click on element until it was completely rendered by Angular

@StanislavKharchenko can you provide a concrete example where this would fail? Until Angular renders something into the browser the DOM element won't be there and won't be found which causes WebdriverIO to continue looking for it. If I understand you correctly, there seem to be a situation where an element is rendered but not interactable? Can you elaborate on that?

I second @kyliau opinion on testing from the user perspective. From the e2e experience an Angular app should be no different from a React or raw JS application. `waitForAngular` has been introduced as there have been no automatic waits within Selenium/Protractor. I would vote for finding framework independent ways to introduce more stability in tests.

So it would be interesting to get more informations where WebdriverIOs current auto-waits are not efficient enough. I would be very interested to improve that.

**Comment by StanislavKharchenko** [comment]
@christian-bromann We're investigated ability to use WDIO with Angular and found that it is not enough to just wait until element "isPresent" or "isEnabled" in DOM.
I propose to investigate by your team using Angular application which has some complex controls on page. Unfortunately I can't share example of our app since it fully corporative.

I don't know how Angular generate DOM, but sometimes, e.g., you have button in DOM, it really present and enabled, but clicking on it doesn't have any effect, since some actions are not loaded yet.
Another example - some dropdown. It present and enabled, but during click on it focus lost quickly since application still is in rendering process.
 
We also saw, that in Playwright and Cypress this works even without checking for "presence" or "enabled". Perhaps these frameworks have some hooks under the hood which automatically wait, like it has in Protractor.

I'm not agree with Keen regarding user knowledge of framework. These knowledges help to make tests more stable and avoid "flaky" states. 
The "Selenium" is just a library and yes it doesn't have some hooks. So, users are free to choose this library (aka selenium) and implement wait hooks, or choose frameworks which has such useful functionality under the hood.

**Comment by christian-bromann** [comment]
> this library (aka selenium)

WebdriverIO is not based off Selenium. It is an independent implementation of the W3C WebDriver protocol.

> I propose to investigate by your team using Angular application which has some complex controls on page.

Happy to do my own investigations but would be awesome if you have an example "complex" Angular application I could use for that.

**Comment by christian-bromann** [comment]
It seems that this conversation went stale and I don't see anything actionable at this point. I would love to make things more stable but I would advocate to make these approaches framework agnostic. If anyone can provide a concrete example where WebdriverIO fails to automate a process due to a frontend framework specific behavior/action I am happy to re-open this.
