### ISSUE TITLE
Better protection against stale element reference (feature request)

### ISSUE THREAD

**Issue by kblcuk** [webdriverio/webdriverio#748]
It would be nice if webdriverio will try to re-fetch the stale element if such error occurs.
Or would it?

For instance I was having some problems testing button with a counter, where waitForCountToIncrease would fail very often because webdriver would get counter reference, but before next check the count updates and re-renders the whole button, and then webdriver check fails.

Natural place would probably be [waitUntil](https://github.com/webdriverio/webdriverio/blob/ce51baa448714e69f19899718236f988417b4b3d/lib/commands/waitUntil.js#L93), with similar check to timeout but using attempts counter, I guess.

Thanks!

**Comment by christian-bromann** [comment]
@kblcuk could you provide a piece of code that led to that error? The problem is that usually if you interact with an element in WebdriverIO, it automatically calls element for you everytime (e.g. getText(selector) calls element(selector) and then the elementIdText command). Afaik Selenium caches the element id until a new page was loaded. If this is the case then I don't see how we can prevent the stale element error from happening.

**Comment by georgecrawford** [comment]
I don't want to hijack this issue, but I can certainly recreate a race condition resulting in a StaleElementReference exception.

```js
	yield browser.url('/');
	yield browser.waitForVisible('#splash', 20000, true);
	yield browser.url('http://google.com');
```

This (using Mocha and wdio) mostly passes. When it does, I see an element request by ID, with an empty response because `#splash` has been removed:
```
[13:51:12]:  COMMAND	POST 	 "/wd/hub/session/ef772ed2-3e23-4dcb-9f97-208fb197ccf3/elements"
[13:51:12]:  DATA		 {"using":"id","value":"splash"}
[13:51:12]:  RESULT		 []
[13:51:12]:  COMMAND	POST 	 "/wd/hub/session/ef772ed2-3e23-4dcb-9f97-208fb197ccf3/url"
[13:51:12]:  DATA		 {"url":"http://google.com"}
    ✓ should be able to see the homepage after start (7289ms)

[13:51:15]:  COMMAND	DELETE 	 "/wd/hub/session/ef772ed2-3e23-4dcb-9f97-208fb197ccf3"
[13:51:15]:  DATA		 {}


1 passing (10.80s)
```
But occasionally I see this:
```
[13:51:23]:  COMMAND	POST 	 "/wd/hub/session/e5ca487c-a4fb-46bc-915b-e980873a0d5e/elements"
[13:51:23]:  DATA		 {"using":"id","value":"splash"}
[13:51:23]:  RESULT		 [{"ELEMENT":"1"}]
[13:51:23]:  COMMAND	GET 	 "/wd/hub/session/e5ca487c-a4fb-46bc-915b-e980873a0d5e/element/1/displayed"
[13:51:23]:  DATA		 {}
[13:51:23]:  RESULT		 true
[13:51:23]:  COMMAND	POST 	 "/wd/hub/session/e5ca487c-a4fb-46bc-915b-e980873a0d5e/elements"
[13:51:23]:  DATA		 {"using":"id","value":"splash"}
[13:51:24]:  RESULT		 [{"ELEMENT":"1"}]
[13:51:24]:  COMMAND	GET 	 "/wd/hub/session/e5ca487c-a4fb-46bc-915b-e980873a0d5e/element/1/displayed"
[13:51:24]:  DATA		 {}
[13:51:25]:  ERROR	StaleElementReference	An element command failed because the referenced element is no longer attached to the DOM.
			stale element reference: element is not attached to the page document
  (Session info: chrome=44.0.2403.157)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.4 x86_64) (WARNING: The server did not provide any stacktrace information)

[13:51:25]:  COMMAND	DELETE 	 "/wd/hub/session/e5ca487c-a4fb-46bc-915b-e980873a0d5e"
[13:51:25]:  DATA		 {}
    1) should be able to see the homepage after start



0 passing (8.80s)
1 failing

1) should be able to see the homepage after start:
element (#splash) still  visible after 20000ms
running chrome
Error: element (#splash) still  visible after 20000ms
```
Although I understand the element caching in Selenium that you describe, I wonder if it's possible to work around this error, since my app and tests are correctly written. The splash screen _does_ disappear, and yet the test fails to subsequently navigate to google.com, and there is error noise in the log.

Could `waitForVisible` (and similar methods) swallow this error, and try another fetch to refresh the Selenium cache if one is encountered?

**Comment by kblcuk** [comment]
Thanks, @georgecrawford , that's actually more or less what I experience as well.

**Comment by jwalton** [comment]
I'm running into this too.  My problem is, I have a bunch of old test cases written against webdriverJS, and some... dubious use of promises by someone from a long time ago.  In my case, my application is a configuration system, so there's lots of pages for creating users, or locations, or whatever...  All these pages have a .btn.save which will either say "Create" or "Save" on it.  When you click "Create" to make a new object, there's a roundtrip to the server (this isn't a one page app) and the new page should now have a "Save" button in it's place.

So there's lots and lots (and lots) of tests which will click "Create", then they'll wait for the page load by continuously `getText('.btn.save')` until they get back a "Save" instead of "Create".  Only, sometimes this code is a little too fast, and the first call into `getText()` ends up fetching the old "Create" button, and then the button gets removed from the DOM. and then getText() tries to read text from the button, and this exception happens.  (It seems like the ancient webdriverJS we were running just ate the exception, so things just continued on without waiting at all... -_-)

**Comment by christian-bromann** [comment]
I kinda now how to fix this issue but I don't like the way how I would need to implement it. I am still looking for an easier way.

**Comment by kblcuk** [comment]
@christian-bromann but that's great news already! Can't wait to see the solution, this problem drank too much of my blood :)

**Comment by georgecrawford** [comment]
@christian-bromann Out of interest, can you describe your potential solution?

________________



George

**Comment by christian-bromann** [comment]
@georgecrawford there are only a handful commands that could trigger this error. Basically all commands that fetch an element first and then do an action on them. I can check each rejected command if the error was due to a StaleElementReference and just rerun the command. Not sure yet if this works for all cases but better than nothing.

**Comment by georgecrawford** [comment]
That's exactly what I was going to hack into my test cases, so it'd be ideal if that could happen at the command 'sugar' level. Thanks!

**Comment by georgecrawford** [comment]
A nice repeatable test case for you:

```
<html>
	<body>
		<h1>Test case 1: StaleElementReference on isVisible()</h1>
		<ul class="container"></ul>
		<script>
			'use strict';
			var container = document.querySelector('.container');

			var count = 0;
			function add() {
				count++;
				var oldRow = document.querySelector('.row-' + (count-1));
				if (oldRow) oldRow.parentNode.removeChild(oldRow);

				var newRow = document.createElement('li');
				newRow.classList.add('row');
				newRow.classList.add('row-' + count);
				newRow.innerHTML = count;
				container.appendChild(newRow);
			}

			setInterval(add, 200);
		</script>
	</body>
</html>
```

```
			browser.url('TEST_CASE_URL');

			let i = 1;
			while (i < 100) {
				console.log(i, 'isVisible', browser.isVisible('.row'));
				i++;
			}
```

This runs a few times then hits a `StaleElementReference` due to the race condition discussed above.

**Comment by georgecrawford** [comment]
This actually works nicely:

```
		browser.addCommand('safeIsVisible', function(selector) {
			try {
				return browser.isVisible(selector);
			} catch (err) {
				if (err && err.message.indexOf('stale element reference') >= 0) {
					console.log('[safeIsVisible] Got stale element reference; trying again...');
					return browser.safeIsVisible(selector);
				}
			}
		});
```

Gives these results with the test I posted above (note that pass 52 works fine, and that 53 initially hits a race condition and throws a staleElementReference exception, but is retried with an updated DOM).
```
[17:57:53]:  COMMAND	POST 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/elements"
[17:57:53]:  DATA		 {"using":"css selector","value":".row"}
[17:57:53]:  RESULT		 [{"ELEMENT":"11"}]
[17:57:53]:  COMMAND	GET 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/element/11/displayed"
[17:57:53]:  DATA		 {}
[17:57:53]:  RESULT		 true
52 'isVisible' true
[17:57:53]:  COMMAND	POST 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/elements"
[17:57:53]:  DATA		 {"using":"css selector","value":".row"}
[17:57:53]:  RESULT		 [{"ELEMENT":"11"}]
[17:57:53]:  COMMAND	GET 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/element/11/displayed"
[17:57:53]:  DATA		 {}
[safeIsVisible] Got stale element reference; trying again...
[17:57:53]:  COMMAND	POST 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/elements"
[17:57:53]:  DATA		 {"using":"css selector","value":".row"}
[17:57:53]:  RESULT		 [{"ELEMENT":"12"}]
[17:57:53]:  COMMAND	GET 	 "/wd/hub/session/b0a2b4e3-794c-409d-af68-a70c207db4bf/element/12/displayed"
[17:57:53]:  DATA		 {}
[17:57:53]:  RESULT		 true
53 'isVisible' true
```

**Comment by christian-bromann** [comment]
Thanks for your help @georgecrawford .. looking into it asap to get this shipped.
