### ISSUE TITLE
WaitForExist wrongly assumes timeout when cannot understand selector

### ISSUE THREAD

**Issue by latobibor** [webdriverio/webdriverio#759]
Hi!

  I have an issue with  `WaitForExist`.
Consider this search for a link:
    `this.waitForExist('div.sidebar a=Sales', 30000);`

WebDriver here does not wait for 30 secs. In fact, it instantly returns this Error message:
    `element (div.sidebar a=Sales) still not existing after 30000ms`

Please return at least the original error message, or the better would be to support this CSS selector:
    `this.waitForExist("div.sidebar a:contains('Sales')", 3000);`

Thank you!
András

**Comment by christian-bromann** [comment]
`'div.sidebar a=Sales'` is not a valid selector. You can't use nested css link texts. The following should work though:

```
this.element('div.sidebar').waitForExist('a=Sales', 30000)
```

See also http://webdriver.io/guide/usage/selectors.html. The error message is correct because there was no element like `<a=Sales />` on the page. There is definitely room to improve the selector parser but since you can easily select any element on the page in almost all cases this isn't really a high prio task.

**Comment by latobibor** [comment]
Thanks for the alternative!
Though I don't agree with you on the error message. This is completely misleading!
If the parser cannot parse it, then please throw "Invalid selector" or something like that. "Still not existing" suggests that it was **in fact** waiting for the element, but that never happened. If you don't set ridiculously long wait times you won't even notice that in fact it didn't wait at all.

So please reopen it and fix it, because bad error messages consumes people time. A lot. And yours as well reading my rants. And someone else will come and won't understand. And you will have to tell him, that it is completely normal for a 30sec wait to end instantly stating *"I have waited for 30 secs and still not found your object. Sorry."*, because it's a totally different error.

:)
