### ISSUE TITLE
webdrivercss  can't make a screenshot  ,error

### ISSUE THREAD

**Issue by worry127722** [webdriverio/webdriverio#769]
I want to use "webdrivercss" to make a screenshot , but png did not be creaeted.(the browser is open)
webdrivercss version:1.1.1
webdriverio version: 2.4.3
 
my code :  
var webdriverio = require('webdriverio');
var client = webdriverio.remote(options);
require('webdrivercss').init(client,{
screenshotRoot: xpath + '/' + time
});
client
.init()
.url(url)
.setViewportSize({
width: 1280,
height: 800
})
.webdrivercss('screenshot',[
{
name: 'screenshot',
elem: 'body'
}
], function(err, res) {
console.log(err);
})
.end();

my  error:
{ [Error: [webdrivercss("screenshot",[])] <= 
[saveDocumentScreenshot("/workspace/test_webd/tieba.baidu.com/L3AvMzUzMDM5Nzg2OD9fX3FhX3BhZ2VfZGlmZj0x/1441678124472/screenshot.png")] <= 
Command failed: gm convert: Unable to open file (/workspace/test_webd/node_modules/webdrivercss/lib/../.tmp/0-1.png) [No such file or directory].
] code: 1, signal: null }

**Comment by christian-bromann** [comment]
This is almost the same issue you posted before -.- . I would really appreciate it if you check out [these points](https://github.com/webdriverio/webdriverio/issues/768#issuecomment-138424316) again. I don't want to be a douchebag about this but you need to help me to understand your issue here.

Could you share the Selenium logs so I can see what happened? Don't know how you run your Selenium tests (see that's why you need to be as descriptive as possible) so I can't advise you how to grab them but you will probably know.
