### ISSUE TITLE
[🐛 Bug]: browser.execute not working with latest chrome

### ISSUE THREAD

**Issue by prasant-sethi** [webdriverio/webdriverio#7872]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

v12.22.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
   browserName: "",
   browserVersion: "96.0.4664.110",
   platformName: "macOS 11.3.1"
}
```

### What happened?

browser.execute seems to be not working with latest Chrome.

const title = await browser.execute('return document.title');

This doesn't work. throws error:
Evaluation failed: Error: eval is disabled.

### What is your expected behavior?

Expectation is to return the value 

### How to reproduce the bug.

const title = await browser.execute('return document.title');
console.log(`title = ${title}`);

### Relevant log output

```typescript
Error: Evaluation failed: Error: eval is disabled
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@prasant-sethi thanks for filing the issue.

My first assumption was that Chrome doesn't support `eval` anymore which I believe was discussed but still not executed. After a quick look I discovered that this error comes from the page you are testing has disabled `eval` calls through CSP settings.

In order to work around this I recommend to setup Chromedriver and run your tests via WebDriver.
