### ISSUE TITLE
uploadFile for Firefox

### ISSUE THREAD

**Issue by sankalpguptasymphony** [webdriverio/webdriverio#8115]
### Is your feature request related to a problem?

Can't use uploadFile API when running tests in Firefox.

### Describe the solution you'd like.

Can we upgrade uploadFile API to support Firefox please.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Can't use uploadFile API when running tests in Firefox.

Unfortunately Firefox doesn't support this command. There is nothing WebdriverIO can do about it.

**Comment by yangzeqiminichris** [comment]
I‘m using the devtool protocol and firefox to test my case, but when I used setValue api, it failed in the elementSendKeys.js at await elementHandle.uploadFile(...paths); Does this happened because  Firefox doesn't support uploadFile api?

The error log:
[Firefox 124.0 win32 #0-0] Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:18:5
[Firefox 124.0 win32 #0-0] Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:18:5
[Firefox 124.0 win32 #0-0] UnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:101:7
[Firefox 124.0 win32 #0-0] execute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13
[Firefox 124.0 win32 #0-0] receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45
[Firefox 124.0 win32 #0-0]
[Firefox 124.0 win32 #0-0] ProtocolError: Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:18:5
[Firefox 124.0 win32 #0-0] UnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:101:7
[Firefox 124.0 win32 #0-0] execute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13
[Firefox 124.0 win32 #0-0] receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45
