### ISSUE TITLE
[💡 Feature]: Enable new Cucumber API to run the tests

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#8149]
### Is your feature request related to a problem?

A [new API](https://github.com/cucumber/cucumber-js/blob/v8.0.0-rc.3/docs/javascript_api.md) is now available to run Cucumber tests.
webdriverIO would benefit a lot from it.

Currently, there are a great number of Cucumber features that webdriverIO users are locked out of.
This is preventable with the new API as we are no longer limited in the way we can run Cucumber under the hood.

Examples of shortcomings:
- If users want to run tests in parallel, they have to rely on other webdriverIO extensions.
Users relying on [wdio-cucumber-parallel-execution](https://github.com/SimitTomar/wdio-cucumber-parallel-execution) cannot use latest features like the `Rule` keyword.
- If users want reports , they also have to rely on other webdriverIO extensions.
Cucumber already offers many reporting options, like JSON and HTML
To have these, users have to rely on two separate extensions
  - [wdio-cucumberjs-json-reporter](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter)
  - [multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter), which depends on the previous reporter.

### Describe the solution you'd like.

Invoke the [new API](https://github.com/cucumber/cucumber-js/blob/v8.0.0-rc.3/docs/javascript_api.md) when running Cucumber tests, making sure all Cucumber options passed in the config are respected, allow for reports to be generated and perhaps even enable native block-level parallelism.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> * If users want to run tests in parallel, they have to rely on other webdriverIO extensions.

This won't change with the new API. WebdriverIO by design runs a spec file per capability in a separate worker process. Switching to this API won't change that. If you want to run more things in parallel, split your scenarios into multiple feature files. Running all scenarios in their own browser session is not always a good idea as it requires a lot of resources.

> * If users want reports , they also have to rely on other webdriverIO extensions.

Same here. Every worker will create their own report and WebdriverIO has to do the job of merging it.

That said, switching to that API is definitely worth doing and it simplifies our integration to the framework drastically. Any contributions are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
@nextlevelbeard you want to help us on this effort?

**Comment by christian-bromann** [comment]
Implemented by @tamil777selvan in #11010
