### ISSUE TITLE
[🐛 Bug]: Number of workers created not filtered by cucumber tags

### ISSUE THREAD

**Issue by darnold24** [webdriverio/webdriverio#8253]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.16

### Node.js Version

16.3.0

### Mode

WDIO Testrunner

### What happened?

When running `yarn test:features` in the root of the cucumber-boiler plate project (link provided in steps to reproduce), the number of workers created does not take cucumber tag filtering into account. In the file `cucumber-boilerplate/wdio.conf.ts` on line 176, if I replace `tagExpression: 'not @Pending',` with `tagExpression: '@test',` and then add the @test tag to 3 cucumber scenarios I see the following in the terminal.

```
╰─ yarn test:features
yarn run v1.22.10
$ wdio run wdio.BUILD.conf.ts

Execution of 30 workers started at 2022-04-19T21:06:27.792Z
```
This does not prevent the tests from starting, however in the case of our project, 280 workers created for large feature files is causing a 15 minute delay before the tests start.

### What is your expected behavior?

If there are 3 scenarios tagged in 3 separate feature files, it should create 3 workers, not 30.

Please note, it is possible to create only one worker by adding an inner array to the array of spec files.
```
specs: [
        ['./src/features/**/*.feature'],
    ],
```
However I expect the behavior to be one worker per feature file so it is reported correctly at the end. See this article here: [https://webdriver.io/blog/2019/11/01/spec-filtering/](url)

### How to reproduce the bug.

You can reproduce this in the cucumber boilerplate project here: [https://github.com/webdriverio/cucumber-boilerplate](url)

Steps to Reproduce:

1. Clone the above project
2. Run yarn install in the projects root directory
3. Change line 176 in the file cucumber-boilerplate/wdio.conf.ts from `tagExpression: 'not @Pending',` to `tagExpression: '@test',`. 
4. Add the @tag tag to 3 different scenarios in 3 different feature files located in `cucumber-boilerplate/src/features`. The tag should be added in the line above the scenario name as such:
```
@test
    Scenario: Test if element responds to button press
        Given the element "#testKeyResponse" not contains any text
        When  I press "b"
        Then  I expect that element "#testKeyResponse" not contains the text "65"
```
5. In the root directory of the project run `yarn test:features`

### Relevant log output

```typescript
yarn run v1.22.10
$ wdio run wdio.BUILD.conf.ts

Execution of 30 workers started at 2022-04-19T21:06:27.792Z
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by julianfarizi** [comment]
Same Issue here.
Using cucumber framework 
Framework will start more than 100 workers and 78 will be executed at the end
issue about time will grow exponentially with the amount of feature files for sure.
Any idea how to fix it?
Happy to share more details if it will help to fix this behavior .. wondering that not more people report this issue :)

**Comment by christian-bromann** [comment]
> Any idea how to fix it?

Please get involved and help us find a fix for this. Thanks!

**Comment by esnoar** [comment]
> > Any idea how to fix it?
> 
> Please get involved and help us find a fix for this. Thanks!

I'm facing this issue too and I'd be happy to contribute and help fix it. However, I don't have experience contributing to open-source projects and don't know what part of the code should I look at to debug this. Any suggestions?

**Comment by esnoar** [comment]
@christian-bromann I debugged the code with the cucumber example located in `examples/wdio/cucumber` and I found that the method you mentioned is [called](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L119) after the workers have been initialized.

I dove deeper into other packages and found that the `getSpecs()` method defined in [`packages/wdio-config/src/lib/ConfigParser.ts`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/lib/ConfigParser.ts#L230) is the one that is called before the workers initiate and it returns the spec files that will be executed. 

This method is called in [`packages/wdio-cli/src/launcher.ts#L91`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/launcher.ts#L91) where the total number of workers is calculated.

My superficial analysis suggests to fix the issue by using this `_hasTest()` [calculation](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L119) in the `getSpecs()` method to verify that each of the spec files has at least one test that matches the tag filter. Then, a worker is initiated per each file that met that condition. I think this can vary from framework to framework too.

As I mentioned before, I have very limited knowledge about JS/TS and OpenSource projects so I don't know if this would be a valid solution or even the best one. Let me know if I can do something else to contribute to this issue.

**Comment by christian-bromann** [comment]
> Let me know if I can do something else to contribute to this issue.

Thanks for the analysis. It is hard to say what is going without debugging the issue. Unfortunately I don't have the capacity right now as I am working on the new `v8` release. I am happy to support anyone who takes a stab at this.

**Comment by erwinheitzman** [comment]
@esnoar thank you for taking a look at this!

Since the issue seems quite specific to Cucumber, my guess would be that the tag filtering might not be working as expected which can be found here https://github.com/webdriverio/webdriverio/blob/c74ad391f1e8d353e9e7dbc78a3b1c857480604a/packages/wdio-cucumber-framework/src/cucumberEventListener.ts#L437

I think you are able to place a console.log and verify what the output of this is.

PS: I'm not saying you are wrong with your analysis, it's just a gut feeling that I have that it might be the above so I'm just sharing what I feel might be worth debugging :)

**Comment by erwinheitzman** [comment]
@esnoar nice going with the debugging. A few things that I noticed:

 1. I think that in order to skip the feature file you would have to put the tag at the feature level. I have tried that but it made no difference as of right now but when the feature is fixed, I do think this is needed.
 2. I found the original implementation which might help to verify some assumptions https://github.com/webdriverio/webdriverio/pull/4531/files
 
 By comparing the current code with the code from the original implementation I think we should be able to figure out what has been changed so that we can fix it :)
 
 @christian-bromann it's a really big PR and I personally have no idea where to start looking at the moment, do you have any tips? I'd also like to know if I am making this bigger then it has to be by sharing this because I have a feeling I might be. It's a way of working that I often apply, when something is broken I go back and see what has changed ^^
 
 So @esnoar no need to dive into the big PR I linked completely as I might be putting you on the wrong path but it might help at the same time as it's how this was originally implemented.
 
 Again thinks for looking into this and don't worry about the formatting of your last message, it's looking fine to me and I have seen much much worse haha.

**Comment by djv1001** [comment]
I'm currently experiencing this after upgrading from v7 to v8.

**Comment by sushantsoni5392** [comment]
This issue happens for `jasmine` framework as well when jasmine `grep` options are used.
