### ISSUE TITLE
how to set user agent for phantomjs

### ISSUE THREAD

**Issue by shawnLiujianwei** [webdriverio/webdriverio#841]
hi 
i'm going to use phantom in webdriverio 

i have run phantom js  "phantomjs --webdriver=9444"

they tried to init client . is there any way i can set the userAgent ?

**Comment by christian-bromann** [comment]
Just set the user agent option within your capability:
```js
        { browserName: 'phantomjs',
          "phantomjs.page.settings.userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.54 (KHTML, like Gecko) Version/9.0 Safari/601.1.54"
        },
```

**Comment by mrft** [comment]
I have been bitten by this issue: https://github.com/webdriverio/webdriverio/issues/414

So I m using selenium  ( starting with java -jar selenium-server-standalone-2.48.2.jar ) combined with phantomjs 1.9.18, which does work, but the suggestion here:

<pre>
options = { 
    desiredCapabilities: { 
        browserName: 'phantomjs',
        "phantomjs.page.settings.userAgent": "SOMEVALUEFORTESTING"
    } 
}
</pre>
doesn't seem to have an influence, because when I 
<pre>
var client = require( 'webdriverio' ).remote( options ).init().url(...);

client.execute( function() { return navigator.userAgent } ).then( value )
</pre>
later on I get 'Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34'

which doesn't reflect the settings I wanted.

Any ideas?

**Comment by mrft** [comment]
For some reason, setting another option first works for me:

<pre>
options = { 
    desiredCapabilities: { 
        browserName: 'phantomjs',
        "phantomjs.page.settings.javascriptCanOpenWindows": true,
        "phantomjs.page.settings.userAgent": "SOMEVALUEFORTESTING"
    } 
}
</pre>

Strange...

**Comment by shawnLiujianwei** [comment]
{ browserName: 'phantomjs',
          "phantomjs.page.settings.userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.54 (KHTML, like Gecko) Version/9.0 Safari/601.1.54"
        }
this works fine for me

**Comment by monolithed** [comment]
@christian-bromann, is there any way to modify user agent for phantomjs in run time / hooks (eg. beforeSuite)?

**Comment by christian-bromann** [comment]
@monolithed only in the desired capabilities
