### ISSUE TITLE
[🐛 Bug]: Be more explicit when configuration file is missing

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8592]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

any

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
any
```

### What happened?

When you pass in a configuration that does not exist, e.g.:

```sh
npx wdio run ./path/to/non/existing.config.js
```

The CLI fails saying, can't run _due to missing configuration file_. Let's be more specific and clearly state which configuration file is missing.

### How to reproduce the bug.

Just run

```
npx wdio run ./path/to/non/existing.config.js
```

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by vjuturu** [comment]
Hi @christian-bromann ,
I am able to reproduce the issue using command given. I am interested to fix this issue. Do you think below "Expected error message" clearly indicates which config file missing. Please advise.

**Issue Reproduction:** npx wdio run ./path/to/non/existing.config.js
 Error: Could not execute "run" due to missing configuration. Would you like to create one?

**Expected error message:**   Error: Could not execute "run" due to missing Testrunner configuration. Would you like to create one?

where "run" will replaced with "install" based on command.

**Comment by christian-bromann** [comment]
The new error message should have the path of the file that wast tried to be run in it, so e.g.

```
Error: Could not execute "run" due to missing configuration, file "./path/to/non/existing.config.js" not found! Would you like to create one?
```

Happy with other suggestions too.

**Comment by perillai** [comment]
> The new error message should have the path of the file that wast tried to be run in it, so e.g.
> 
> ```
> Error: Could not execute "run" due to missing configuration, file "./path/to/non/existing.config.js" not found! Would you like to create one?
> ```
> 
> Happy with other suggestions too.

Have raised a PR doing the suggested changes. Kindly approve the workflow in the PR. Thanks.

**Comment by christian-bromann** [comment]
I am going to close this, thanks for the PR @perillai 👍
