### ISSUE TITLE
[💡 Feature]: Allow for coercing of ChainablePromiseElements arrays into a ChainablePromiseArray

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#8609]
### Is your feature request related to a problem?

It's cool that we can do this
```ts
const texts = await browser.$$('h3').map((img) => img.getText())
```

but that's because `$$` returns a ChainablePromiseArray.

If I make my own array of `ChainablePromiseElement<WebdriverIO.Element>` that I grab from my page/screen objects, I cannot, leaving me to rely on `Promise.all` or `Promise.allSettled`

```ts
const elemsToAssert = [
  PageObject.myNeatInput,
  PageObject.myCoolButton
]

// This doesn't work, let's make it work!
const texts = await elemsToAssert.map(elem => elem.getText())

// This works but it's a pain and not noob friendly
const texts = await Promise.all(elemsToAssert.map(elem => elem.getText()))
```

### Describe the solution you'd like.

Maybe a way to do this is to allow an array of elements to be coerced into an `ChainablePromiseArray` by throwing them inside `$$` ?

```ts

const elemsToAssert: ChainablePromiseArray<ElementArray> = $$([
  PageObject.myNeatInput,
  PageObject.myCoolButton
]) 

// Now it works!
const texts = await elemsToAssert.map(elem => elem.getText())

// Or all together like
const texts = await $$([
  PageObject.myNeatInput,
  PageObject.myCoolButton
]).map(elem => elem.getText())
```

### Describe alternatives you've considered.

N\A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I like the idea of:

```ts
const elemsToAssert: ChainablePromiseArray<ElementArray> = $$([
  PageObject.myNeatInput,
  PageObject.myCoolButton
]) 
```

Any contributions are welcome! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by erwinheitzman** [comment]
@nextlevelbeard thank you for the suggestion, it's great to see you involved!

I would like to discuss this a bit a bit though.

I find that replacing one wrapper with another doesn't really add any value, especially considering that Javascript knowledge is required in order to use the tool.

Comparing them hopefully shows that it is just a replacement of words:
```js
const texts = await Promise.all(elemsToAssert.map(elem => elem.getText()));
// vs
const texts = await $$(elemsToAssert).map(elem => elem.getText());
```

Don't get me wrong, I'm all for helping out any of our users but the way that I look at it right now is that just wrapping native Javascript functionality like this feels like a bad thing to do.

**Comment by nextlevelbeard** [comment]
@erwinheitzman thanks for the feedback on this, glad to be in the community

Well, this is something not crucial and just a "nice to have".
I understand your point and agree, to an extent.
We can't put out convenience code for everything, where would we stop, right?


But maybe the community feels strongly about it and can pick it up for you.
In order for that to happen, it needs to be "accepted" by the steering committee.
I'm just curious:

> wrapping native Javascript functionality like this feels like a bad thing to do

Why do you feel like **_this_** a bad thing, which shouldn't be "accepted", compared to all the similar work already done to help our users move from sync to async in v7?

Where do you draw the line? 😄

**Comment by erwinheitzman** [comment]
@nextlevelbeard can you share a reference to the work you are talking about specifically? That way I can give a better answer as you are asking where we draw the line relatively compared to other work.

Regarding why I feel that we shouldn't do this, I feel that the only thing it adds is more maintenance on our side (think of code but also documentation) while not providing value to our users as they would first have to read and understand how this command works (not realizing that it's actually a Promise.all that they should have been using).

Furthermore, if instead we would document this pattern instead of implementing your suggestion, we would be teaching our users a way of working that goes beyond the framework and will teach them a better understanding of not only how WebdriverIO works but Javascript itself as well.

All of that said, I'm not going say no to the implementation itself if any other member then me is for this change after reading this as this is just my point of view that I'm sharing and it's not something very impactful (as in, it won't cause problems / has high risks). You can see me like a gatekeeper, it's not that I'm not letting you in but my role is still to guard 😄

**Comment by christian-bromann** [comment]
@erwinheitzman thanks for chiming in and raising your concerns. You made a great comparison:

```ts
const texts = await Promise.all(elemsToAssert.map(elem => elem.getText()));
// vs
const texts = await $$(elemsToAssert).map(elem => elem.getText());
```

this indeed is not much of a difference. However your example only works for `map` in this case but not for other Array methods like `find`, `some` or `reduce` which are supported when wrapping them into a `ChainablePromiseArray`. For example:

```ts
[1, 2, 3, true, false].findIndex(async () => false)
// returns `0`
```

because the `findIndex` iterator receives a promise rather than `false`. With the `ChainablePromiseArray` the iterator promise is resolved and returns the right value, e.g.:

```ts
var pIteration = require("p-iteration")

console.log(await pIteration.findIndex(['a', 'b', 'c', 'd'], async (char) => char === 'c')) // returns 2
console.log(['a', 'b', 'c', 'd'].findIndex(async (char) => char === 'c')) // returns 0
```

Therefore I think it definitely makes sense to include this, so people can loop over the individual elements.

**Comment by erwinheitzman** [comment]
@nextlevelbeard I had a quick chat with Christian to verify some things and I now see that there's definitely more reasons then the example you shared originally. You have my blessing haha, jokes aside I think this will be a great addition!

**Comment by nextlevelbeard** [comment]
great to hear @erwinheitzman blessing much appreciated

I had a look at the code, building a chain-able promise array requires that you specify a selector for the elements.
As in one selector for all of them.
I believe this is for re-fetching purposes.

That's all fine and dandy for `$$` use with a string selector, but when building this feature and passing elements retrieved from different selectors, that won't quite work. 🤔

**Comment by christian-bromann** [comment]
> That's all fine and dandy for `$$` use with a string selector, but when building this feature and passing elements retrieved from different selectors, that won't quite work. 🤔

That seems to be about right. I guess we should look improving the re-fetching logic then for this case.

**Comment by christian-bromann** [comment]
I've implemented this feature, so the following is now possible:

```ts
await browser.url('http://guinea-pig.webdriver.io')
const red = await browser.$('.red')
const green = await browser.$('.green')
const elems = browser.$$([red, green])
console.log(await elems.map((e) => e.getAttribute('class')))
```

**Comment by nextlevelbeard** [comment]
@christian-bromann

Types might need some polishing:

With `map`, usage is correctly Inferred as (in this example) `boolean[]`
```ts
const displayed: boolean[] = await $$([elem1, elem2]).map((e) => e.isDisplayed())
```

But with `find`, it is not inferred as an element, but rather `unknown`
```ts
const elem: WebdriverIO.Element = await [elem1, elem2].find((e) => e.isDisplayed()) // Inferred as unknown
```

I assume `find` is also supported, as mentioned in the [Async migration:](https://webdriver.io/docs/async-migration/) docs:

> The map as well as all other iterator methods of Arrays like find, every, reduce and more are implemented via the [p-iteration](https://www.npmjs.com/package/p-iteration) package and are therefor simplified for using them in an async context.

**Comment by christian-bromann** [comment]
Thanks for the feedback @nextlevelbeard , you like to take a stab at this?
