### ISSUE TITLE
[💡 Feature]: add code executed as a string into onTestxxx hooks (for usage in reporter)

### ISSUE THREAD

**Issue by talbss** [webdriverio/webdriverio#8759]
### Is your feature request related to a problem?

Coming from protractor + mocha + mochawesome reporter.
The reporter offers the possibility to include function body code into reporter for better readability (test result + code + screenshot for each test).

https://github.com/mochajs/mocha/blob/ac43029d6a86150a48ccd59e50e89ca10c72a9c0/lib/runnable.js#L37
https://github.com/mochajs/mocha/blob/ac43029d6a86150a48ccd59e50e89ca10c72a9c0/lib/test.js#L99

### Describe the solution you'd like.

I would like to have a key named **code** in testStats object argument for all onTestxxx hooks (when applicable) allowing to includes the code exectuted by the test into the reporter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

I am open to the idea of providing the code of the test function in the reporter event. In order to have a similar experience with different frameworks we should check if we can get this information in Jasmine, Cucumber and Mocha.

Any contributions are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
