### ISSUE TITLE
@types/mocha

### ISSUE THREAD

**Issue by Semigradsky** [webdriverio/webdriverio#8940]
### Is your feature request related to a problem?

Currently `@wdio/mocha-framework` package has `"mocha": "^10.0.0"` and `"@types/mocha": "^9.1.1"` in dependencies. Looks like it should be `"@types/mocha": "^10.0.0"`

### Describe the solution you'd like.

Change dependency to `"@types/mocha": "^10.0.0"`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

You are right, the new version for `@types/mocha` was released 2 days ago and our automated dependency update hasn't kicked in yet. Feel free to raise a PR with a fix otherwise @dependabot will go ahead and probably do that next Monday.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
