### ISSUE TITLE
[🐛 Bug]: browserstack-service - insights POST returns 401

### ISSUE THREAD

**Issue by SCG82** [webdriverio/webdriverio#9513]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.0

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'Chrome',
    browserVersion: 'latest',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
        args: [
            '--ignore-certificate-errors',
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            '--disable-renderer-backgrounding',
            '--disable-background-timer-throttling',
            '--disable-backgrounding-occluded-windows',
        ],
        perfLoggingPrefs: {
            enableNetwork: false,
            enablePage: false,
        },
    },
    'bstack:options': {
        projectName: 'MyProject',
        buildName: `${gitBranch()} - ${commitHash()} - ${new Date().toISOString()}`,
        consoleLogs: 'verbose',
        networkLogs: false,
        seleniumVersion: '4.4.0',
        buildTag: new Date().toISOString(),
        os: 'OS X',
        osVersion: 'Monterey',
        sessionName: 'MyProject - MacOS - Latest Chrome',
        resolution: '1920x1080',
        idleTimeout: 300,
        local: false,
        debug: false,
    },
}
```

### What happened?

Receiving a 401 response to the POST to  https://collector-observability.browserstack.com/api/v1/builds

### How to reproduce the bug.

If unable to reproduce, let me know.

### Relevant log output

```typescript
@wdio/browserstack-service: Data upload to BrowserStack Test Observability failed either due to incorrect credentials or an unsupported SDK version or because you do not have access to the product.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SCG82** [comment]
@nagpalkaran95

**Comment by sourav-kundu** [comment]
@SCG82 
It is the intended behavior since the insights is a new product offering from BrowserStack which is agnostic of where the test is running. Since the user does not have access to the insights product or has not accepted the product's terms yet, this message is being shown in debug and trace log levels. But I agree that the message currently has too many OR statements and is confusing.

We will make changes in the following manner:
- If credentials are incorrect, we will send 401 and a respective message to be shown in the error log level.
- If the user does not have access to the insights product yet, we will send 403 status with a respective message back from the server to be shown in the info, debug, and trace log levels such that they can visit our dashboard and get access to the product.

**Comment by SCG82** [comment]
sounds good, thanks
