### ISSUE TITLE
How to get element's element?

### ISSUE THREAD

**Issue by yhjor1212** [webdriverio/webdriverio#960]
as title

**Comment by christian-bromann** [comment]
What do you mean by that?

**Comment by yhjor1212** [comment]
Just like when I use watir webdriver, there are functions like `lis` to get a list of `li` element, and functions like <element>.parent to go back to parent element.

Such binding would save so much time to developers to locate element's element.

**Comment by christian-bromann** [comment]
You can chain the `element` commands in order to navigate through the dom, e.g.
```js
browser
    .element('#someElem') // intial element
    .element('..') // parent of #someElem
    .element('#someElem2') // children of the parent element
```

**Comment by sanyco92** [comment]
For me this issue is actual. Could you help me? 
I have iOS table of Cells, I can find it with accessibility id `"~Test"` or with XPath `//XCUIElementTypeTable(@name='Table')`
But the problem is that with XPath it takes around 2-3 mins to find the element. So I wanted to find the element of the table, and inside the table find the cell with specific text.
So, let's imagine the following hierarchy:
- XCUIElementTypeTable[@name='Table']
-- XCUIElementTypeCell
    ---XCUIElementTypeStaticText[@name='TextName1']
-- XCUIElementTypeCell
    ---XCUIElementTypeStaticText[@name='TextName2']
-- XCUIElementTypeCell
    ---XCUIElementTypeStaticText[@name='TextName3']
-- XCUIElementTypeCell
    ---XCUIElementTypeStaticText[@name='TextName4']
-- XCUIElementTypeCell
    ---XCUIElementTypeStaticText[@name='TextName5']

How to find the element of XCUIElementTypeCell with TextName4? Not text exactly, I need exactly Cell element.
