### ISSUE TITLE
Add pCloudy service in Webdriverio

### ISSUE THREAD

**Issue by Advinsteve** [webdriverio/webdriverio#9703]
### Is your feature request related to a problem?

Hi Guys ,

I am working with the pCloudy [A cloud platform for web and application testing] I like to integrate the pCloudy service with WDIO
we have a huge customer base who where moving towards WDIO , so we would like to integrate our service with Webdriverio 

### Describe the solution you'd like.

I request you to please recommend  anyone who can help me to integrate or any documentation

### Describe alternatives you've considered.

We have couple of capabilities through which we can connect [like ..username, API-Key] 

### Additional context

Website : https://device.pcloudy.com/

It's our official website we host couple of services you can have a look for it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Hey @Advinsteve ,

there are some ways you can integrate pCloudy into WebdriverIO to improve the user experience:

- the [`detectBackend`](https://github.com/webdriverio/webdriverio/commit/d2f13f9fb877921c41927d33f1819174e44d7817) function that allows to determine the pCloudy connection data based on provided user credentials so that user don't have to set them themselves
- enhance the [config wizard](https://github.com/webdriverio/webdriverio/blob/ef9b5e6915fad46026aa7ef7f4b8079df40eb713/packages/wdio-cli/src/constants.ts#L175-L182) to allow pick pCloudy and create a `wdio.conf.js` that is preconfigured for the user to connect to your backend
- our docs for [cloud services](https://github.com/webdriverio/webdriverio/blob/fca9082b61da2bbceedf7c68897d07f59f715f0a/website/docs/CloudServices.md) can be enhanced if there are special instructions for user to know

If you like to build a service plugin, I would advice to create and publish it under your organisation. E.g. you can create a [`wdio-pcloudy-service`](https://www.npmjs.com/package/wdio-pcloudy-service) that helps manages session and add convenient features for users.

Let me know if you have any further questions. We provide [office hours](https://webdriver.io/community/openofficehours) to support with contributing to the project.
