### ISSUE TITLE
waitForExist (reversed) always says element still exists (even if nonsense)

### ISSUE THREAD

**Issue by kierenj** [webdriverio/webdriverio#974]
This code:

    browser
      .waitForExist('#nonsense', 5000, true)
      .call(callback);

Always yields:

`element (#nonsense) still  existing after 5000ms`

No matter what I put as the selector - `#nonsense` does not exist, of course!

Just did a fresh npm install - am on version 3.4.0 (was on 3.3.something when first occurred).  Any ideas or anything I can do to help?

(The same for `waitForVisible` reversed, too - even if the element doesn't exist, it says it's still visible after the timeout)

**Comment by christian-bromann** [comment]
Can you provide a simple example script that reproduces this behavior? I tried `.waitForExist('#nonsense', 5000, true)` and it queried the element without luck and moved forward (since `#nonsense` obviously doesn't exist). Then I tried `.waitForExist('body', 5000, true)` and the command failed with `element (body) still  existing after 5000ms` which is the expected error.

**Comment by kierenj** [comment]
Will be happy to help - when you say script, checking you mean a nice little self-contained example?  So conf file plus minimal spec (in my case a .feature and  a steps.js file - using cucumber)?

**Comment by christian-bromann** [comment]
Yes, this would help me a lot to identify the problem. Thanks!

**Comment by kierenj** [comment]
Ta-da! found a good hint, too: https://github.com/kierenj/webdriverio-repro

'master' is broken, 'working' is not.

The problem occurs when I set up with `browser.timeouts('implicit', timeout);`

**Comment by chill117** [comment]
@kierenj Thanks! Been dealing with issue for a few hours.

This problem still exists as of version 4.0.3

**Comment by christian-bromann** [comment]
@chill117 can you give me a reproducible example?

**Comment by chill117** [comment]
@christian-bromann I've created a [sample node project](https://github.com/chill117/webdriverio-implicit-timeouts-bug) which reproduces the bug. If you have anymore questions, just let me know.

**Comment by kierenj** [comment]
Was my repro project not working @christian-bromann ? :)

**Comment by christian-bromann** [comment]
@kierenj just curious if it is the same issue

**Comment by jancarloviray** [comment]
I was having the same exact issue as well. Happens with waitForExist, waitForVisible

This fixed it:

> The problem occurs when I set up with browser.timeouts('implicit', timeout);

**Comment by mmcculloch15** [comment]
+1

**Comment by patthiel** [comment]
I am wondering if this is still an issue with latest changes to the waitFor commands. Could anyone from this thread confirm?

**Comment by chodorowicz** [comment]
I'm experiencing this problem still for `4.2.15`

**Comment by christian-bromann** [comment]
@patthiel nope, this is not an issue anymore. Wasn't able to reproduce in standalone and wdio mode.

**Comment by DominikGuzei** [comment]
@christian-bromann we still ran into that bug on webdriver 4.8.0

**Comment by taylor-faragher** [comment]
@christian-bromann Seeing this issue in 4.9.11 as well

**Comment by christian-bromann** [comment]
@DominikGuzei @taylor-faragher please provide a reproducible example

**Comment by igerasimov23** [comment]
@christian-bromann 
I following example when element is visible:
 console.log(browser.waitForExist("input[name=userid][placeholder=Email]"));
 console.log(browser.waitForExist("input[name=userid][placeholder=Email]", true));

output:
true
true

**Comment by AnnikaNissen** [comment]
I thought, that I experience the same bug using WebdriverIO 4.13.2, but after some debugging, it turned out that this seems to be a **raise-condition that occurs when the `waitFor`-timeout is equal (or shorter) then the implicit-wait timeout. When the `waitFor`-timeout is bigger then the implicit-wait timeout, everything works as expected.**

**Case: waitFor-timeout equals implicit-wait, element is visible on the page but disappears within the waitFor-timeout (removed from DOM)**
```javascript
browser.timeouts('implicit', 10000); // 10 seconds
browser.waitForVisible('#somethingThatDisappears', 10000, true); // 10 seconds
```
This leads to the following timeline:

| ms | state |
| --- | --- |
| 0ms | `waitForVisible` requests `element('#somethingThatDisappears')` to determine if it is visible. `true` is returned as the element still is visible |
| ~200ms | `#somethingThatDisappears` is removed from the DOM, hence not visible any more |
| 500ms | `waitForVisible` requests new status for `element('#somethingThatDisappears')` |
| 10000ms | `waitForVisible` fails, as the `element` didn't return (due to the implicit-wait of 10 seconds) | 
| 10500ms | `element` would return 'notFound' and `waitForVisible` would succeed |

I hope this helps others to understand this problem/bug.

@christian-bromann   
A possible fix could be, to provide methods like `waitForInvisible()` and/or `waitForNotExists()` that bypass the implicit-wait. This would also make the test faster, as no implicit-wait is needed, when we are expecting that elements don't exist in the DOM.

**Comment by christian-bromann** [comment]
> 10500ms	`element` would return 'notFound' and `waitForVisible` would succeed

I think this is the problem that needs to be fixed. If the element is not found the `isVisible()` command should return false.

**Comment by AnnikaNissen** [comment]
@christian-bromann  

> I think this is the problem that needs to be fixed. If the element is not found the isVisible() command should return false.

It does! The problem, in my opinion, is, that the implicit-wait causes `browser.element()` to wait up to Xms, so that the correct value for `isVisible()` isn't returned before the timeout for `waitForVisible('selector', undefined, true)` is exceeded.

**Comment by christian-bromann** [comment]
Why do you use implicit timeouts anyway? It should be either set to `0` or not changed at all. Their usage is kind of not recommended.

**Comment by AnnikaNissen** [comment]
I can't remember why I added the implicit timeout. Probably because the auto-waiting-behaviour sounds cool in the first place ;-).  
I will probably re-evaluate the use of implicit timeouts after today and see what it means to my tests.
