### ISSUE TITLE
[🐛 Bug]: Scroll Into View issues with scrolling to an element

### ISSUE THREAD

**Issue by kevin-longmate** [webdriverio/webdriverio#9805]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.9

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
This is happening on all capabilities I've tried - chrome, firefox and safari latest and older versions through browserstack so don't believe it matters
```

### What happened?

We have recently updated from version 7.26 to 8.3.9 and noticed a number of issues where our tests are scrolling elements in to view

When scrolling in to view an element on a page, when the element is near the top of the page, or above the currently displayed part of the website, webdriver appears to scroll down taking the element out of view instead.

See attached video and code to reproduce below. There are two scrolls in each test, the element used in all cases is 
`//h3[text()="Get Started With WebdriverIO within Seconds"]`

The first test, I scroll to it normally and it works (although the scroll puts it behind the navbar at the top of the page). Then I scroll with the options `{block: "center"}`, which should put the element in the middle of the page (scrolling up from where we are) however it instead scrolls down so that the "Watch talks about webdriver io" is displayed at the top of the page, which is below the element I want. The element I want is then further out of view above the visible part of the page.

The page reloads for the second test and I use scrollIntoView with `{block: "center"}` first, which works ok and the element I want is in the middle of the page. I then scroll again to that element without using `{block: "center"}` and once again it sends is up above the visible area of the page so that I'm looking at the "Watch talks about webdriver io" bit, with the element I want to be in view well above the top of the page.

Video taken from browserstack
https://user-images.githubusercontent.com/46672685/220308880-15a032c5-26f7-48a4-867c-f0c697e5d2ba.mp4

### What is your expected behavior?

When calling scroll in to view with any options, the element should be scroll in to view correctly. Using this without any options should have it show at the top of the page, using it with `{block: "center"}` should show it in the middle of the page

### How to reproduce the bug.

describe("scrolling tests", () => {
it("scroll testing 1", async () => {
    await browser.url("https://webdriver.io/");
    await browser.maximizeWindow();
    await browser.pause(5000);
    const element = await $(
      "//h3[text()="Get Started With WebdriverIO within Seconds"]"
    );
    await element.scrollIntoView();
    await browser.pause(5000);
    await element.scrollIntoView({ block: "center" });
    await browser.pause(5000);
  });

  it("scroll testing 2", async () => {
    await browser.url("https://webdriver.io/");
    await browser.pause(5000);
    const element = await $(
      "//h3[text()="Get Started With WebdriverIO within Seconds"]"
    );
    await element.scrollIntoView({ block: "center" });
    await browser.pause(5000);
    await element.scrollIntoView();
    await browser.pause(5000);
  });
});

### Relevant log output

```typescript
na
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

The `scrollIntoView` command should behave the same way as defined in the [Web spec](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) just implemented through WebDrivers action API. If this is not the case this would be a bug.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by kevin-longmate** [comment]
First time I've contributed here so not sure if I've forgot to do anything, but I managed to get this working in the PR above.

Changing the `origin` of the scroll to be `browser` rather than `this` makes the reproduced example above work as expected, and it's started passing my tests for work as well

**Comment by OBe95** [comment]
Hi @christian-bromann @kevin-longmate 
I think we can use `html` element (used to calculate the deltas) as the `origin`
It also seems that the `deltaY` is wrongly based on the `height` instead of the `width`
I opened a PR for it with an e2e test, @kevin-longmate can you check if it correctly fixes your scenarios ?

**Comment by christian-bromann** [comment]
> It also seems that the `deltaY` is wrongly based on the `height` instead of the `width`

I don't quite understand this. For the y delate (vertical delta) we don't look at the height of the element?

**Comment by OBe95** [comment]
My bad, got confused with the deltas
Now they're both computed from the `height`, it should be correct for `deltaY` but `deltaX` should use the `width`

**Comment by kevin-longmate** [comment]
@OBe95 I've tried these changes on my tests and the test file I have in the bug description but it's not worked unfortunately.
Attached a video using these changes on the reproduced example above.
The element `//h3[text()='Get Started With WebdriverIO within Seconds']` first has a standard `.scrollIntoView()` which should take it to the top of the page, but it's near the bottom.
It should then scroll to be in the center of the page (`.scrollIntoView({block: "center"})`), which works ok but I think that's a coincidence.

The page reloads, and the element should scroll to the center of the page but it's nowhere in view, then it should scroll to the top but it again goes to the middle

https://user-images.githubusercontent.com/46672685/222407699-2f8b01de-fe8a-40db-a455-943ebf18b142.mp4

Thanks for noticing the deltaX stuff, I missed that but think I've seen another bug on this bit starting on line 76:
```
} else if ((options as ScrollIntoViewOptions).block === 'center') {
            deltaX += Math.round((viewport.width - elemSize.width) / 2)
        }
```
According to the spec https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView using `block` should be for vertical alignment while using `inline` should be for horizontal alignment, should this be changed to using `inline` rather than `block` here, given it's dealing with the width?

```
} else if ((options as ScrollIntoViewOptions).inline === 'center') {
            deltaX += Math.round((viewport.width - elemSize.width) / 2)
        }
```

**Comment by OBe95** [comment]
@kevin-longmate @christian-bromann I pushed a new commit, this time I dropped the usage of the `origin` as I'm not sure why we have the `- windowSize.height` [here](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/performActions.ts#L205), dropping the `origin` param will make it processed by the second if block (based on current element position and `delta` for center position)

**Comment by kevin-longmate** [comment]
@OBe95 those most recent changes are good, the test file from the issue is doing what I expect and the tests I have for work are all passing again 👍

**Comment by OBe95** [comment]
Thanks for the feedback @kevin-longmate 
I pushed a recent update to support the other options (`end`/`nearest`)

**Comment by Jasonizl** [comment]
Hello,

after reading through most of the comments and PRs I'm not sure if this Problem is fixed. We're currently trying to transition from v7 to v8 but the scrollIntoView causes a lot of problems right now.

We have the same experience as @kevin-longmate and can't get it to work by any means. I thought first this may be because of how I have the current Header setup which overlays the button, but it also happens with elements randomly on the page.

**Comment by kevin-longmate** [comment]
@Jasonizl haven't seen any issues since this latest update myself...

Could you give an example of what code you're running on which website? Might be worth opening a new bug for it as there's been another bug logged / PR made for scrollIntoView since I made this one

**Comment by Jasonizl** [comment]
To cut it short, in one of the test cases the following is tested:
`1. open startpage -> 2. search item ->3. put item into cart -> 4. proceed to cart -> 5. proceed to checkout  -> 6. verify that the checkout is ready by scrolling to a element further below -> 7. go back by pressing the back button -> ...`

So the scrolling works throughout the test well, but where it fails is between 6. and 7.
The code to scroll to a button looks like this:

`  await (await $(buttonToClick)).scrollIntoView({ block: 'center' });
  await (await $(buttonToClick)).click();`

However upon the scrollIntoView being called, it will scroll up - but not so far so that it is interactible in the viewport. It is hidden behind the Header. (I can't really do screenshots without editing because the software is under NDA)

Previously in version 7 it would just scroll as far as it could, when we `block: 'center'` anything. If the element is located at the top of the page, the function would scroll it as far into the center as it could - making it interactible since the Header is not overlapping.

So yeah thats the issue we face. I also took a manual look and got it fixed by editing/adjusting the https://github.com/webdriverio/webdriverio/blame/d5e477a7f61c533cf9aadcada1d58ada38fcfc75/packages/webdriverio/src/commands/element/scrollIntoView.ts#L57 (I removed the if condition just above so that it does that regardless of device/browser and it works like before)
My guess is that all the logic that comes below that, is having some issues.. Need to see if I have some time to analyze more

And yes I also found this open issue: #10369 which may have the same problem. (I don't use github that often, should I rather write there again since this issue is closed?)

**Comment by shlomo100** [comment]
I also get this error in version 8.15.9 and as soon as I do it on the browser's scrollIntoView directly everything works

**Comment by christian-bromann** [comment]
@shlomo100 @Jasonizl can you provide a minimal reproducible example?

**Comment by shlomo100** [comment]
@christian-bromann After setting up a clean project from the auto-generated example and running the provided tests, I noticed an unexpected behavior related to the scrollIntoView functionality. 

```typescript
it("scroll into view - getStarted with href selector - works fine", async ()=> {
    await browser.url('https://webdriver.io/');
    const whoIsUsingLogos = $('.logos_YIMf');
    const getStarted = $('[href="/docs/gettingstarted"]');
    await whoIsUsingLogos.scrollIntoView();
    await expect(await whoIsUsingLogos).toBeDisplayedInViewport();
    await getStarted.scrollIntoView();
    await expect(await getStarted).toBeDisplayedInViewport();
});

it("scroll into view - getStarted with class selector - doesn't work", async ()=> {
    await browser.url('https://webdriver.io/');
    const whoIsUsingLogos = $('.logos_YIMf');
    const getStarted = $('.buttons_pzbO a');
    await whoIsUsingLogos.scrollIntoView();
    await expect(await whoIsUsingLogos).toBeDisplayedInViewport();
    await getStarted.scrollIntoView();
    await expect(await getStarted).toBeDisplayedInViewport();
});
``` 

In the above tests, the behavior of the scrollIntoView method seems inconsistent when using different selectors.

P.S. I also encountered this error when using scrollIntoView: ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds

**Comment by shlomo100** [comment]
@christian-bromann [#11056](https://github.com/webdriverio/webdriverio/issues/11056)
