### ISSUE TITLE
Rename `.url` to `.open`

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#986]
`.url` and `.getUrl` are confused. 
It would be nice to rename `.url` to `.open`

`.open` is used by [Casper](http://docs.casperjs.org/en/latest/modules/casper.html#open), [Zombie](https://github.com/assaf/zombie), [Horseman](https://github.com/johntitus/node-horseman), navit ...

**Comment by christian-bromann** [comment]
I don't think we can change this. WebdriverIO commands follow a certain convention based on the JSONWire protocol:

`/session/:sessionId/url` -> url
`/session/:sessionId/timeouts/implicit_wait` -> timeoutsImplicitWait
`/session/:sessionId/element/:id/click` -> elementIdClick
...

I am not sure if it makes sense to break this convention. Also people using WebdriverIO are used to use url already so I don't think it is a big issue.

**Comment by monolithed** [comment]
> WebdriverIO commands follow a certain convention based on the JSONWire protocol

But `WebdriverIO` is a wrapper around `JSONWire protocol` ))
For example, the `intern` uses [`.get`](https://theintern.github.io/leadfoot/Command.html#get)

What do you think about `aliases` section?

```
{
   alises: { url: 'open' }
}
```

**Comment by christian-bromann** [comment]
> But WebdriverIO is a wrapper around JSONWire protocol

That's right but since day one of this library all protocol commands follow this convention.

> What do you think about aliases section?

Good idea. We introduced services in v4 which do all sorts of things during the test process. I could imagine this to be a `wdio-aliases-service` that reads that property and creates that commands in the before hook of the service.

**Comment by christian-bromann** [comment]
Checkout [wdio-sauce-service](https://github.com/webdriverio/wdio-sauce-service) to see what I mean by service

**Comment by monolithed** [comment]
Really, thanks for you work!
Is there an issue what will be introduced in v4?

**Comment by christian-bromann** [comment]
I am working right now (once I have time) on a revamp of the website. Since all commands will work synchronously a lot of documentation changes. Therefor we need to deploy the website in different versions for the first time basically. Once that is done there will be a "What's new" page that will introduce that.

**Comment by christian-bromann** [comment]
In the meantime feel free to create that service based on that prototype and be the first service contributor for new wdio services ;-) and don't forget to put your service in [here](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/cli.js#L31-L33) then.
