### ISSUE TITLE
Problem using isVisibleWithinViewport command

### ISSUE THREAD

**Issue by patthiel** [webdriverio/webdriverio#988]
Hi,

I'm having using the isVisibleWithin viewport command. I am running the test against 

http://anthropologie.com/anthro/index.jsp 

Here's my test.. 

``` javascript
it('should confirm given a small screen, the responsive menu displays', function() {

		return browser
			.setViewportSize({width: 970, height: 720}, false)   // width < 989 will update the header navigation to small screen version
			.url('/')
            .waitForExist('.anthro-modal-close',15000).then(function(){
            	 browser.click('.anthro-modal-close');  // Close the email signup modal
            })
			.isVisibleWithinViewport('.stitch1').then(function(visibility){ // Confirm if an element in the small screen navigation is visible
				console.log(visibility);
				expect(visibility).toBe(true);
			})
			.isVisibleWithinViewport('.sn-ACCESSORIES').then(function(visibility) { // Confirm an element in the large screen nav is not visible
				console.log(visibility);
				expect(visibility).toBe(false);
			})
			
});
```
However, updating the test to use the .isVisible command results in the test passing as expected. Not sure if I'm doing something wrong here, if there's a bug in the isVisibleWithinViewport implementation.

Any help would be appreciated!

**Comment by christian-bromann** [comment]
I debugged it and it turns out that your header element (`.header-rwd-app`) has a weird position:

![screen shot 2016-01-07 at 14 42 30](https://cloud.githubusercontent.com/assets/731337/12171807/16b6d9ec-b54d-11e5-9274-9b441015eb4e.png)

It is somewhere 5876px from the top of the page but also the same amount from the bottom of the page. This causes the script to return false. I guess the `isVisible` check is sufficient for your purposes. However I think this can be fixed by subtracting the bottom from the top to get better results.

**Comment by patthiel** [comment]
thanks 👍
